### ISSUE TITLE
Need rename tllphoenix (name already exist for arm T2...)

### ISSUE THREAD

**Issue by skymyj** [techannihilation/TA#1016]
I propose to revert the request. 
New name : Condor

**Comment by nixtux** [comment]
Do it

**Comment by skymyj** [comment]
https://github.com/techannihilation/TA/pull/1010 => for revert.

**Comment by skymyj** [comment]
Revert first, or there will be many conflicts.

**Comment by nixtux** [comment]
Fix, closing
