### ISSUE TITLE
Valiant is a core unit

### ISSUE THREAD

**Issue by skymyj** [techannihilation/TA#1018]
Maybe we should add for Core T5 lab. 
I have a good ship for TLL : 
![image](https://user-images.githubusercontent.com/2990630/37673524-b85ea12a-2c70-11e8-9d3d-6474d533cb8a.png)

**Comment by nixtux** [comment]
Do we have textured ship and fully working script for this unit?, if not I'm closing issue

**Comment by skymyj** [comment]
We have not yet. I will not work for nothing. 
If you like this idea, I can work on this.

**Comment by skymyj** [comment]
Script takes 1 hour of work.
More complicated now it's texture

**Comment by skymyj** [comment]
I propose to move Valiant in T5 Lab Core. 
I 'd like to give him other  core weapon.
For Arm, we can take the Zweistein Ship missile
