### ISSUE TITLE
Super Vulcan 

### ISSUE THREAD

**Issue by ghost** [techannihilation/TA#103]
Increase cost by 40% ?  or nerf ?

Why so?:

- its easy to build it kinda early, and enemy will have issues with defend that
- its easy to build it kinda early and end game early so we see T4 fights rather rare

**Comment by ZweisteinT** [comment]
Feels like a yes to me. 

On tech 2 level you need "some" t2 eco before you can go vulcan. I think we should have the same balance for t4 vulcans. So you should need at least some t4 extractors and some of those super mega fusions before you can build any super weapon. 

I suggest also we test how many shields you need to stop t4 vulcan. i feel like you should not need more than ... lets say 4... shields to stop vulcans?

**Comment by Antarac** [comment]
Increase cost by 40% is a really good start.
Strong Players often mention op T4 cannons.

**Comment by nixtux** [comment]
is this still valid ?

**Comment by Antarac** [comment]
I would say yes.

**Comment by skymyj** [comment]
Time to close it
