### ISSUE TITLE
T3 Bertha Model

### ISSUE THREAD

**Issue by skymyj** [techannihilation/TA#1041]
After changed t1 bertha : 
![image](https://user-images.githubusercontent.com/2990630/38162811-61165626-34e8-11e8-95fa-5b81ab369a82.png)
Then T2 with known model. 
Then I propose new models for T3 : 
![image](https://user-images.githubusercontent.com/2990630/38162827-b13632a2-34e8-11e8-9034-b17218a7c300.png)
![image](https://user-images.githubusercontent.com/2990630/38162834-dd8ae794-34e8-11e8-83d9-dd30167955c7.png)
![image](https://user-images.githubusercontent.com/2990630/38162852-0fcc4040-34e9-11e8-962c-db15f17c9ed3.png)

**Comment by skymyj** [comment]
![image](https://user-images.githubusercontent.com/2990630/38165677-84416d3c-3517-11e8-8ba8-2eba274196cc.png)

**Comment by nixtux** [comment]
Done
