### ISSUE TITLE
Need feedback to continue RC Work

### ISSUE THREAD

**Issue by skymyj** [techannihilation/TA#1074]
https://1drv.ms/v/s!AgjKPxaKD1zLllbgSrNn2fcPKDRX

Do you validate these models ? 
If yes, I will work on these models to delete piece for t3/t2/t1 RC.

Thanks

**Comment by keijj0** [comment]
Yes, those look great. Imo they need combined radar/jammer added to them

**Comment by ksilversurfer** [comment]
yeah its nice
