### ISSUE TITLE
cdevastator : Proposition to change 3do model

### ISSUE THREAD

**Issue by skymyj** [techannihilation/TA#1076]
ATM, the main weapon is not a beam. It's more a laser or canon.
I propose this weapon : 
![image](https://user-images.githubusercontent.com/2990630/39065331-cd83f5ea-44d1-11e8-8318-8600647629fb.png)
![image](https://user-images.githubusercontent.com/2990630/39065494-3f8eba9e-44d2-11e8-8602-0ce54da595c3.png)

**Comment by ksilversurfer** [comment]
i like it !!!
