### ISSUE TITLE
Need scale up armmcv

### ISSUE THREAD

**Issue by skymyj** [techannihilation/TA#1079]
By 10-15%
![image](https://user-images.githubusercontent.com/2990630/39084346-9cd5d00a-4574-11e8-9263-d4166b877619.png)

**Comment by skymyj** [comment]
![image](https://user-images.githubusercontent.com/2990630/39084353-b9d1a6e8-4574-11e8-98b1-9a64895f5973.png)

**Comment by skymyj** [comment]
ATM, armmcv has 3* armbats HP.
There is nosense

**Comment by ksilversurfer** [comment]
yep agree

**Comment by skymyj** [comment]
With new ratio : (1.15)
![image](https://user-images.githubusercontent.com/2990630/39115823-2da01b3a-46e3-11e8-9e24-8606bc27aa40.png)
![image](https://user-images.githubusercontent.com/2990630/39115878-485600d4-46e3-11e8-9872-447b263fd216.png)

**Comment by skymyj** [comment]
Increase turret too : 
![image](https://user-images.githubusercontent.com/2990630/39117019-2acdb5c2-46e6-11e8-9263-248563940330.png)
