### ISSUE TITLE
Broken fix asap

### ISSUE THREAD

**Issue by nixtux** [techannihilation/TA#1142]
[f=0000302] Warning: [MapScriptToModelPieces] could not find piece named "shad4b" (referenced by COB script "scripts/armolympus.cob")
[f=0000302] Warning: [GetTexture] unknown 3DO texture "packpanellight00" for piece "body"
[f=0000302] Warning: [GetTexture] unknown 3DO texture "packpanellight00" for piece "body"
[f=0000302] Warning: [GetTexture] unknown 3DO texture "snw2light00" for piece "turret1"
[f=0000302] Warning: [GetTexture] unknown 3DO texture "snw2light00" for piece "turret1"
[f=0000302] Warning: [GetTexture] unknown 3DO texture "snw2light00" for piece "turret2"
[f=0000302] Warning: [GetTexture] unknown 3DO texture "snw2light00" for piece "turret2"
[f=0000302] Warning: [GetTexture] unknown 3DO texture "snw2light00" for piece "turret2"
[f=0000305] Error: [COBThread::ShowError] unitID=29154 defName=tllburner error="[US::GetUnitVal] CobError: unknown get-constant 0 (params = 0 0 0 0)" (in scripts/tllburner.cob:UnitSpeed at f21)

**Comment by skymyj** [comment]
You can close it
