### ISSUE TITLE
Copter Strategy

### ISSUE THREAD

**Issue by skymyj** [techannihilation/TA#1169]
I have many trouble with these units : 
- Models : we can't let them in the mode cause they are from antiquity age
- Strategy : there are already Air gunship. If you take Blade (Flak resistant), there are no interest to make them. For T1, it just a metal lost.
---------------------
In thinking from long time, I propose to add a new armorclass. This class could be hit by ground and air. The strategy here is to have powerfull and rapid units but weak because all could destroy them.
Cruisealt low but higher than hover or gravity tank.
So, We could add them for each T1 Cons.
About units, we need : 
- T1 Cons copter
- T1 Fast Battle Copter
- T1 AA Copter
- T1 Missile BattleCopter
- T1.5 Strong (canon and missile) BattleCopter
--------
All battle units need to have special damage VS copterclass
----------
IF and even if we go in this direction, we can let copter in TA mode. Or it just a nonsense.
Thanks.

**Comment by Antarac** [comment]
🚁 🌤 🚁 🚁

**Comment by skymyj** [comment]
Hi Antarac. We didn't see you for long time. When do you come back ? There are many new things to test !

**Comment by Antarac** [comment]
Ta is updated now and i watched a game. Let me see if i have time to play.

**Comment by skymyj** [comment]
Have time to take fun :)

**Comment by Antarac** [comment]
I would love to play more but rl, you know...

**Comment by Antarac** [comment]
Changing to more nice
models is no problem.

Changing the weapons is fine to me.

Dunno if people wanna go for
more complicated height levels?

**Comment by skymyj** [comment]
With Talon faction, we could add them. I explain : core have turtoise, tll turtle, arm spider...
Talon could have copter factory.

**Comment by Antarac** [comment]
Tortoise and Turtle is same thing.
Choppers have nothing in common with turtle and spider.
Talon isn't even there yet.

There is also robots and vehicles that do same thing than spiders,
and noone delete it, just cause it's two time same thing.
