### ISSUE TITLE
Decrease size buzz vulc, hydre, cordoom1, armanni1 T4

### ISSUE THREAD

**Issue by skymyj** [techannihilation/TA#1172]
All T4 Rapid plasma need decrease size by 20%.
They have ATM same size than Tsar.

**Comment by skymyj** [comment]
I add the Tachyon, cordoom with this list

**Comment by Antarac** [comment]
You could also make TSAR bigger instead many cannons smaller.

**Comment by skymyj** [comment]
I proposed but was rejected by nix and silver

**Comment by Antarac** [comment]
Tsar musst be not necessarily bigger than the others, does it?
