### ISSUE TITLE
TLL Lacking L2 Hovercraft

### ISSUE THREAD

**Issue by Leggir** [techannihilation/TA#1174]
TLL Lacking L2 Hovercraft. There was a user who created both Arm and Core T2 hovers for TA called GroundZero. Among the units pictured, top left, the Minotaur had a shotgun like blast that fired 20 PeeWee like canon fire in a cluster. Top right, Sea Ghost, cloaking and medium laser. Middle left Jaguar has a gauz like rifle that can shoot through 3 or 4 units all lined up. Middle right, the Atomizer, has a canon that's effectively a tactical nuke, but takes 20-30 seconds to reload. Lower left, Zenith, LRPC. Lower right, Asp, Heavy Laser. Next page, Alligator (Almost a T3 Hover), Gatling plasma canon on one side, lightning gun other side, with heavy AA missile. These would be a great add-on for TLL. 

I have the files if you want to see them. I'd love to be able to provide 3D models but I don't know how  to make them (if you can point me to some tutorials that'd be great).

![gz hovers2](https://user-images.githubusercontent.com/5009817/40816934-d0ec0b54-650c-11e8-95a5-27cc7b35cdea.png)

**Comment by skymyj** [comment]
Atm, there is a t2 Hover with morphing.
https://media.discordapp.net/attachments/431389653174845441/437692471527473163/unknown.png?width=658&height=676

Now, TLL have Turtle. I think, we don't have obligation to give them T2 hover. 
If you think yes, we should take models from ground zero. I will see.

I will soon make a tuto to explain how integrate the model from another mod. And a second with create a new unit from .wings file. If you want, there is a big folder with many models here : https://www.tauniverse.com/forum/showthread.php?t=44575&page=3
You have to download Wings 3D (x64) 2.1.5 to open files.

**Comment by skymyj** [comment]
Can i have the link ? For this mode ?

**Comment by Leggir** [comment]
[GZ_Hovers_V1.zip](https://github.com/techannihilation/TA/files/2065668/GZ_Hovers_V1.zip)

**Comment by skymyj** [comment]
I will add them.
