### ISSUE TITLE
Airports are impossible to target.

### ISSUE THREAD

**Issue by Leggir** [techannihilation/TA#1175]
Here's a screenshot of 30 units shooting this airport and it took 10 minutes to destroy it even with no one repairing it. All fire goes over it.

![screen00067](https://user-images.githubusercontent.com/5009817/40822833-394bd058-652b-11e8-83c8-f841699320b7.jpg)

**Comment by nixtux** [comment]
Fixed in https://github.com/techannihilation/TA/commit/75715f72047794d2db95faf3710a12103be592e7
