### ISSUE TITLE
Remplace Vengence (akmech) Model

### ISSUE THREAD

**Issue by skymyj** [techannihilation/TA#1184]
Why this request : #1151 

Cause : 
- The AKmech is an AK model from Core.
- the Script is bugged. The blue laser works only at 50%.
- The leg animation are too fast : he looks like running and not walking.

We can change vs a new proper model with less weapon (easier for novice players) 
https://onedrive.live.com/?cid=cb5c0f8a163fca08&id=CB5C0F8A163FCA08%212950&ithint=video,mp4&authkey=!AHFgbOsUVyVgroE

**Comment by Leggir** [comment]
I don't mind the existing one, but that's just me.
