### ISSUE TITLE
So where are we moving to? 

### ISSUE THREAD

**Issue by nixtux** [techannihilation/TA#1186]
Github is now gone, so where do we go!

**Comment by skymyj** [comment]
omg !

**Comment by skymyj** [comment]
Is not gone. Just under Eye of Sauron

**Comment by pcdummy** [comment]
I have my private gitlab instance, may move there?

**Comment by Antarac** [comment]
Just no more support or servers down?
Github status says its fine o.O

**Comment by ksilversurfer** [comment]
imo Github is fine, i dont understand why all afraid of microsoft :D
I was looking some info what will change, but seems like nothing much, maybe some ads they will add :P

**Comment by ksilversurfer** [comment]
One thing is missing on github: to pin important Issue/thread on top of the list.
Does GitLab have this?

**Comment by Antarac** [comment]
Since i just bought my first Smartphone ever i made a github button =)
