### ISSUE TITLE
New organisation gameplay for RC

### ISSUE THREAD

**Issue by skymyj** [techannihilation/TA#1187]
I propose this new organisation with 4 new cons ship : 
![proposition](https://user-images.githubusercontent.com/2990630/40966041-b25c29fc-68af-11e8-9017-2fa5a071cfa7.PNG)

With these balance, it will be better. ATM, the T1 RC cons with T2 RC can make strong units like Sumo.. With this balance, it will be better and we will see more units like T3 Hover  Turtoise lighting tank...

For BattleCom, I suggst it could make the T1 RC Cons, Assault, the T2, Star the T3...

BattleCom have to be increased, cause Eco Com & RC will be more choosen to build these constructors.
I propose to increase Buildpower, and energy/metal income (+125E/S and 2.5M/S).

What do you think ?

**Comment by ksilversurfer** [comment]
First to do: Builder lvl1 - shoud cost a bit more like 800metal

**Comment by skymyj** [comment]
I'm ok. They have to be same metal cost than Lab

**Comment by skymyj** [comment]
![image](https://user-images.githubusercontent.com/2990630/41089694-c13b99be-6a42-11e8-8882-5d08d729bbc7.png)
Need your mind @nixtux  to continue

**Comment by nixtux** [comment]
Fine
