### ISSUE TITLE
Units guarding won't move to defend units.

### ISSUE THREAD

**Issue by Leggir** [techannihilation/TA#1189]
I'm not sure how difficult this is to add. However it'd be great to assign units to guard another, and have them move relative to their movement freedom to engage and protect their assigned units. For example, TLL T4 Shield bot, you could assign several units to guard it, and when berthas start firing on it, they could walk out and engage them or other units. Currently they only stay close and will engage only if they have a line of sight and the units close enough, which would be fine on "hold position". However on "Maneuver" they should move a moderate distance to guard. On "Roam" they should move to anywhere on the map they can reach to assault the units that are attacking the units they are guarding.

**Comment by skymyj** [comment]
No priority
