### ISSUE TITLE
T3 Sub OTA icons

### ISSUE THREAD

**Issue by skymyj** [techannihilation/TA#1208]
![corbsub](https://user-images.githubusercontent.com/2990630/41670954-0cb397f2-74b6-11e8-8396-89c3e7dfa327.png)
![armbsub](https://user-images.githubusercontent.com/2990630/41670955-0ce7df08-74b6-11e8-986b-ca22f59557e1.png)

**Comment by Leggir** [comment]
If its a choice, I prefer the 2nd one.

**Comment by skymyj** [comment]
No choice here. There is for arm and core :)

**Comment by skymyj** [comment]
And soon : TLL : 
![image](https://user-images.githubusercontent.com/2990630/41702389-4664465c-7530-11e8-8562-b5bd2d9fe85e.png)
