### ISSUE TITLE
T3 TLL Bomber tllanhur => new job

### ISSUE THREAD

**Issue by skymyj** [techannihilation/TA#122]
Actually, this bomber is a torpedo bomber cause there was no T3 ship.

Now we have T3 ship, maybe change this job for Ultimate Air Paralyser Bomber

**Comment by ZweisteinT** [comment]
lol :D

or make the two t3 bomber one lightweight and the other heavy one.

**Comment by Antarac** [comment]
Paralyser Bomber would be used by players mostly to disable enemy
shields/anti nuke/defence/units.

If it's meant as Anti Ship Bomber how about a "Sea Wave Bomber" that damages Ships by creating big water waves with bombs. Modified EMP particle/animation could do the visual Job.
https://en.wikipedia.org/wiki/Rogue_wave
