### ISSUE TITLE
Missile truck

### ISSUE THREAD

**Issue by skymyj** [techannihilation/TA#1226]
On ba : 
it's same cost. HP = 735 vs 1065 ba
But they have extra damage vs air. 

Damage ground unit is 19.16/s vs 15 in TA.
same range (600 in ba vs 605 ta)

I think, we have to increase at 20 and 25 for adv.

**Comment by Antarac** [comment]
little bit more HP should be fine.

**Comment by skymyj** [comment]
#1273
