### ISSUE TITLE
Research Center build list

### ISSUE THREAD

**Issue by Antarac** [techannihilation/TA#1228]
The "Research Center" model got changed and it looks from start like a factory.
I don't know whats the idea behind it but seems there is units needed for the build list?

**Comment by Antarac** [comment]
Smaller flying Constructors for T1-T3
that must be somewhat special cause
there are plane constructors already.

Build smaller spaceships in it like
Frigates and Corvette before you
reach the Cruiser and Capital
with extra factory on T4?

**Comment by Antarac** [comment]
In other games with space ships you have usually figthers, corvette, frigate, cruiser, capital.

Corvette could be built in the Research Center on Tech 2 and Frigates on Tech 3.

**Comment by skymyj** [comment]
So, you jst want to change unitname ?

**Comment by Antarac** [comment]
I mean class for new units that you could build in RC.
Smallest = Figthers/Bombers built in airport
Corvette = Big fighters
Frigate = Small Capital class
Biggest = Capital/Cruiserbuilt in T4 Factory

**Comment by Antarac** [comment]
no, i mean spaceship classes.
Corvette is like big fighters.
Frigates are like Small Cruiser.

We got now cons there so maybe forget about it.
