### ISSUE TITLE
Construction Units and Guard order

### ISSUE THREAD

**Issue by Antarac** [techannihilation/TA#1229]
If a construction unit is on guard and i add a build queue the unit wont move.
Is it possible to skip guard if the player gives a builder new build order?

Cause i see many people falling over that in the last years.
They dont see/ forgot unit got guard and give orders.
Some time later when they get back to unit nothing
has been built which makes the players very angry.

You might say now, thats the system/ thats how it works/ etc so no change.
But its obvious if player gives new build order he wants it to be built.
To chancel guard in this case for the cons would help a lot to make players not go mad.

Hard to describe that issue but i think its really important
cause that small thing cause lots of trouble sometimes.

**Comment by ksilversurfer** [comment]
can you explain more?

**Comment by Antarac** [comment]
You give some cons the order to guard a t2 con.
20 minutes later you click one of that cons and give a build queue with shift key.
But con will not build cause it is still guarding.
People often miss that thing and get really mad.

I'm the player, i gave a order.
If i give another order,
i want it to be done ofc.
So earase old guard order.
I would never make a queue if i
know its not working afterwards.

**Comment by ksilversurfer** [comment]
good idea

**Comment by skymyj** [comment]
No time ATM to implement this feature
