### ISSUE TITLE
Double sided textures

### ISSUE THREAD

**Issue by Antarac** [techannihilation/TA#1230]
Are all Textures in TA double sided?

**Comment by skymyj** [comment]
Yes.

**Comment by Antarac** [comment]
Im asking cause double sided textures need more computer power than one sided.
But i guess change not possible or to much work.

**Comment by skymyj** [comment]
Changes are easy and take 5 min.
Sometimes, some models have bugged texture and it's impossible to have texture on other side. 
Wich are the unit you think with miss two sided texture ?

**Comment by nixtux** [comment]
Closing pointless thread
