### ISSUE TITLE
Upgrade center upgrades future factory units. *FEATURE*

### ISSUE THREAD

**Issue by Leggir** [techannihilation/TA#1232]
One of the best features of TA is the ability to morph units obviously. It'd be great if you could research the upgrades to units at the research center, and have the units be built at the factory already morphed. Primarily this would be useful at level 1. For example, upgrading the unit Core Storm to Distant Storm, Thud to Massive Thud. This would allow T1 factory to remain more useful beyond the opening stages of the game.

**Comment by skymyj** [comment]
Hey leggir. Can you make a list with unitname (ex:armsam=>armsam1). You have this with space bar after select a unit.
Thanks

**Comment by Leggir** [comment]
Sorry for the delay. I'm going to the USA for 3 weeks for some job training and a short vacation, so I've been busy getting my affairs in order.

Here's a list of Core Units at Level 1 and 2 that could benefit from research at the research center. I'll add other units as time permits.

Level 1
Core CORRAID -> CORRAID1
Core CORSTORM -> CORSTORM1
Core CORTHUD -> CORTHUD1
Core CORLEVELR -> CORLEVLR1
Core CORAK -> CORAK1
Core CORWOLV -> CORWOLV1

Level 2
Core CORGOL -> CORGOL1
Core CORSUMO -> CORSUMO1
