### ISSUE TITLE
TLLDB doesn't  rotate when firing.

### ISSUE THREAD

**Issue by Leggir** [techannihilation/TA#1239]
![screen00161](https://user-images.githubusercontent.com/5009817/41966473-732ebf38-79bc-11e8-8734-5153312d38cb.jpg)

**Comment by Leggir** [comment]
On build 8660

**Comment by skymyj** [comment]
I will check this evenning for TLL.

**Comment by nixtux** [comment]
@skymyj 'indeed. The model is not finished. It's same for core T3 flak, there are no sleeves to rotate barrel in X axis.'. What are you talking about, the issue with tlldb has nothing todo with that at all, what it happening is tlldb only rotates to target when weapon 1 is aiming as in the picture above its a missile firing not weapon 1(flak) it does not rotate to target, I will add correct fix later

**Comment by skymyj** [comment]
I just want to say the core model is not finished too.

**Comment by nixtux** [comment]
@skymyj so what do you think is wrong with corpre ? As atm i see nothing wrong there

**Comment by skymyj** [comment]
Well nothing. It just to quick speed for turrets. 1000 is too high. 
200 could be fine in cob

**Comment by nixtux** [comment]
Lmfao 200 is way too low before you start picking numbers out of thin air go check other units, let me save you some time t2 flaks are 700, so 1000 at this point does not seem high at all

**Comment by skymyj** [comment]
In my experience, many barrels speed are set to 500 or NOW status. 
So, we need to consider 500 like instantaneously.
I'm for to decrease all flak at 300. ATM, these t3 are just too quick and there is a nonsense.

**Comment by nixtux** [comment]
Ohh look at BA values for t2 https://github.com/Balanced-Annihilation/Balanced-Annihilation/blob/master/scripts/armflak.bos#L67

Now this conversion is stopping here your idea are unfounded
