### ISSUE TITLE
TLLNANOTC2 and TLLNANOTC3 don't appear to be building.

### ISSUE THREAD

**Issue by Leggir** [techannihilation/TA#1240]
Just with build 8660, this started. Without highlighting them, they point at what they're working on and do aid in the construction or repair, but do not show they are.

![screen00159](https://user-images.githubusercontent.com/5009817/41966697-0a092f56-79bd-11e8-9761-66c9e0fd2e97.jpg)
![screen00158](https://user-images.githubusercontent.com/5009817/41966699-0a3e90ec-79bd-11e8-8c3b-b52cd885f8c7.jpg)

**Comment by nixtux** [comment]
Which lups effect are you using for nano's laser or particles, can you post infolog.txt from game (pastebin please)
