### ISSUE TITLE
Additional graphics options for TA

### ISSUE THREAD

**Issue by Antarac** [techannihilation/TA#1242]
I have a bad computer, which is good for testing.

My biggest problem is "low framerate" in late stage of big games.
We want big TA games so whats possible to help people with weak computer?
Possible to make for example crazy option for turning off textures completly?
Ofc i would not play all time without textures, but if i could avoid to "lag out" i would use it.
Or other options that have hughe impact on frames?

**Comment by nixtux** [comment]
Everything on low, enable dynamic lups
