### ISSUE TITLE
New models for V1

### ISSUE THREAD

**Issue by skymyj** [techannihilation/TA#1246]
Atm, many units, have same models after morphing.
I propose these new models for llt and chainsaw : 
https://cdn.discordapp.com/attachments/431389653174845441/460454274489384960/unknown.png
https://cdn.discordapp.com/attachments/431389653174845441/460475712319782913/unknown.png
https://cdn.discordapp.com/attachments/431389653174845441/461245726912020501/unknown.png
https://cdn.discordapp.com/attachments/431389653174845441/454305801083944971/unknown.png

You could change models for t3 shields
https://cdn.discordapp.com/attachments/431389653174845441/459118752525451269/unknown.png
https://cdn.discordapp.com/attachments/431389653174845441/459119452496199680/unknown.png

And other models for HLT
https://cdn.discordapp.com/attachments/431389653174845441/460449523005652996/unknown.png
https://cdn.discordapp.com/attachments/431389653174845441/460448759801708545/unknown.png

**Comment by Antarac** [comment]
Looks good so far, but which model for which faction?

**Comment by nixtux** [comment]
When making request like this for example I will need to see all hlt in one screenshot ie basic, upgraded and vhlt.

**Comment by skymyj** [comment]
Hey. I m motived to take time to make new model or unit. 
Before i spend time for create an unit, i have to know if concetp can be accepted. It s why i post on new unit channel or issue.
So if yes i can make a request with video image...
