### ISSUE TITLE
tsar

### ISSUE THREAD

**Issue by Antarac** [techannihilation/TA#1254]
People complain about TSAR to delete it.
No good idea to delete it tho.
People build it faster now tho cause of more experience.
How about to decrease damage range?
Fine if damage is more, but range gets less.

Target is that might not all enemys get killed if TSAR hits.
I just look for a change cause people ask for it.

**Comment by skymyj** [comment]
Anta, I think you talk about the AOE. 
I'm for increase Range at 12K, reduce the AOE by 2, and why not increase damage at 1M.
And I'm for add special damage for commander like 15K. The weapon kill all com except the supreme.

**Comment by skymyj** [comment]
If Eco chain, the com will die anyways

**Comment by Antarac** [comment]
Please no special damage cause only 10% of people gonna know about that.

**Comment by Antarac** [comment]
I would rather close threads instead doing special damage :-s
