### ISSUE TITLE
Add Shield for Battle Com

### ISSUE THREAD

**Issue by skymyj** [techannihilation/TA#1255]
I think, we could add them.
They will become a nice def unit.
And they will be limited vs laser def.

**Comment by Antarac** [comment]
Commander specials are always good =)
If shield is not to strong could be really nice!

**Comment by Antarac** [comment]
Battle Commander Constructor now also available at
Research Center so yeah, add shields for balance!

**Comment by Antarac** [comment]
Sky, if people don't like shields maybe add build option for defense?
