### ISSUE TITLE
Core Helicopter Factory

### ISSUE THREAD

**Issue by Antarac** [techannihilation/TA#1258]
Core Helicopter Factory is too small cause when you build big Helicopters its really hard to click the Factory.

**Comment by skymyj** [comment]
!vote delete copter

**Comment by nixtux** [comment]
!vote delete skymyj xD

**Comment by Antarac** [comment]
Ye, delete it along with all six legged spiders ^^

**Comment by skymyj** [comment]
Could we delete temporaly these copter, the time to develop them better : #1169
As i said in this other issue, we should rework them in term of strategy.

**Comment by skymyj** [comment]
With Talon faction, we could add them. I explain : core have turtoise, tll turtle, arm spider... 
Talon could have copter factory.

**Comment by skymyj** [comment]
When i said develop them better, i speak about the lab too. I have one in my stock (very nice model)

**Comment by nixtux** [comment]
We are not going to delete them, I will increase unit size

**Comment by Antarac** [comment]
Ty!

**Comment by Leggir** [comment]
I think copters could be reworked. There's not much differentiating each apart. There's also not many reasons to build them vs airplanes. Anti-submarine copter could be awesome, hovering over the sub dropping depth charges for example. Perhaps a heavy lifter copter like the Chinook. Maybe a Apache like unit with multiple weapons and agile enough to avoid level one AA or to avoid 50% of AA rounds.
