### ISSUE TITLE
Texture missing for Adv Rocket Core (cormist1)

### ISSUE THREAD

**Issue by skymyj** [techannihilation/TA#1260]
![image](https://user-images.githubusercontent.com/2990630/42294772-fc3b021e-7fe3-11e8-846c-a82920139bb4.png)

**Comment by skymyj** [comment]
Script prob too. The turret doesn't go down / up

**Comment by skymyj** [comment]
![image](https://user-images.githubusercontent.com/2990630/42419435-4cde6bc4-82b5-11e8-8b0d-e691ff258d57.png)

**Comment by skymyj** [comment]
![image](https://user-images.githubusercontent.com/2990630/42419443-7bc652d0-82b5-11e8-94fa-2be79491248d.png)

**Comment by skymyj** [comment]
![image](https://user-images.githubusercontent.com/2990630/42421967-8ee407b2-82de-11e8-8c5a-0dee116da4bc.png)
New t1.1 textured

**Comment by nixtux** [comment]
Can you make pr for missing texture, (I know it feature freeze) but it's an old bug that need fixing
