### ISSUE TITLE
Shortened Old Weapon List

### ISSUE THREAD

**Issue by Antarac** [techannihilation/TA#1265]
Shortened Old Weapon list:
Anti Bomb Laser	-	Shoots and destroys bombs before they reach the ground.			
Grenade thrower	-	Grenades bounce and explode on collision or after a set time.
Heat ray blaster	-	Melts metal.
Ice cannon		-	Freeze robots.
Intelligent Rocket	-	Fire and forget.
Interceptor tower	-	Fires Interceptors that do a single attack and fly back to the tower.
Laser Reflector		-	Reflects enemy lasers.	
Solar Laser		-	Like Geo Behemoth.
Taser Turret		-	Taser units to stun them.

**Comment by nixtux** [comment]
Can you move this to a wiki page please?
