### ISSUE TITLE
Team1

### ISSUE THREAD

**Issue by Antarac** [techannihilation/TA#1266]
Team1 observes now the carrots from below.
Team1 got shampoo in the eyes.
Team1 fell out of the bed.
Team1 went to get cigaretts and didn't come back.
Team1 outsmart itself.
Team1 failed at bungeejumping.
Team1 ran out of fuel.
Team1 left the U-Boat door open.
Team1 was to fast.
Team1 didn't understand english.
Team1 might get excavated by archaeologists someday.
Team1 might have another live.
Team1 still thinks it won.
Team1 is unconcious.
Team1 had no ticket.
Team1 stood in front of a Cliff and now it is already one step further.
Team1 didn't fall, it attacked the ground.
Team1 smiled, cause it could be more worst, and it came more worst.
Team1 visits the fish on the ground.
Team1 were faster than it's guardian angel could fly.
Team1 got burnout.
Team1 didn't laugh last.
Team1 lost it's lollipop.
Team1 took the blue pill.
Team1 took the wrong medication
Team1 had no towel.
Team1 knew, blue is greener than yellow.
Team1 was allergic.
Team1 well...

**Comment by nixtux** [comment]
Can you move this to a wiki page please?
