### ISSUE TITLE
TLL JetPack Kbot (T2)

### ISSUE THREAD

**Issue by skymyj** [techannihilation/TA#1268]
ATM, it's the more complicated gameplay unit. 
Even with many trains, I can't do properly maneuvers, fight micro and select good weapon.

I propose : 
- to delete the button and the script to choose between the 2 weapons.
- immunize this unit vs EMP
- delete explosion from bomb. Just keep EMP and damage and increase reload like 12s.

It will be better.
Thanks

**Comment by skymyj** [comment]
If you want keep this setting. 
At least, add a touch command like "B".

**Comment by nixtux** [comment]
We have no spare keys left, there all used

**Comment by nixtux** [comment]
https://github.com/techannihilation/TA/blob/master/luaui/configs/techa_hotkeyinfo.lua#L90
Next time please check this file before you request hot keys as it's already used

**Comment by skymyj** [comment]
Ok. So no possibility for space key.
But is it possible : 

    to delete the button and the script to choose between the 2 weapons.
    immunize this unit vs EMP
    delete explosion from bomb. Just keep EMP and damage and increase reload like 12s.

**Comment by nixtux** [comment]
Space key is meta can't be used

**Comment by skymyj** [comment]
Whatever the space key was bad option anyways. 
Just if possible delete button and script please

**Comment by nixtux** [comment]
please see https://github.com/techannihilation/TA/commit/0e43c83d571218a4058131d3d9a8764aef438f0a
