### ISSUE TITLE
Sound design

### ISSUE THREAD

**Issue by Antarac** [techannihilation/TA#1269]
Hard to describe this. Not really a issue.
More of a question or possibility about "sound scenery".

If you have big game with spam
and defense shooting constantly,
the sound is like "one fluent noise".

Thats from explosions mostly i think.
I seen many people turning down volume at that point.
Cause it sounds somewhat bad.

Possible to make explosions very little bit more quiet for example?
Add more different sounds to change sound scenery positive way?

So close this bullshit, or interesting thought?

**Comment by ksilversurfer** [comment]
you are 100% right Antarac, sounds balance need to be reworked

**Comment by skymyj** [comment]
ATm, silver works on sound
