### ISSUE TITLE
Olympus balance

### ISSUE THREAD

**Issue by skymyj** [techannihilation/TA#1278]
ATM, useless unit. 
Please, change this lighting weapon. Didn't match with bertha type.
Best imho, is to revert into gauss canon with impressive effect if not much particules.

**Comment by nixtux** [comment]
Best imo you stfu, its only aoe 212 > 192

**Comment by skymyj** [comment]
:) have you tested your balance ?

**Comment by skymyj** [comment]
I think not

**Comment by nixtux** [comment]
https://github.com/techannihilation/TA/commit/a8bb1e7fafe922d8ec0211102bd3f7f8d0652dc

**Comment by nixtux** [comment]
Back to original stats

**Comment by skymyj** [comment]
I just saw it. Same result. Sorry to say you, but the gausscanon didn't work with this config.

**Comment by nixtux** [comment]
Your a fine one to comment on testing.........

**Comment by skymyj** [comment]
So this config = 1000 dmg/s for main weapon

**Comment by nixtux** [comment]
Original stats https://github.com/techannihilation/TA/blob/9575ad0b4d6c28b9b50573dc2424f6e4e082bf03/units/armolympus.lua

Now https://github.com/techannihilation/TA/blob/master/units/armolympus.lua

I never change damage or reload so what are you talking about.

**Comment by skymyj** [comment]
The gauscannon type doesn't work. 
Gauscannon or EmgCannon is like armorco or champion tank. Goal is to pass over all unit/obstacle.

I think, it's the line explosiongenerator = "custom:Explosion_Barret_Tesla" that make bug.
gausscannon has no explosiongenerator. 
From : https://springrts.com/wiki/Gamedev:WeaponDefs#EmgCannon

A line-of-sight weapon. Visually drawn as a billboarded sprite very similar to that of the #Cannon, however not as customisable, or a 3D model. The name is another OTAism.
There are no tags specific to this WeaponType.

**Comment by nixtux** [comment]
That tag tells spring with explosion to draw (and I only mean draw) nothing todo with damage or anything else, please test don't think
