### ISSUE TITLE
Battlecom should be more badass

### ISSUE THREAD

**Issue by killfreekill** [techannihilation/TA#1280]
Currently you can choose either Eco or Combat commander morph.
Choosing either locks the other away and Combat com being kind of weak/unworthy and not used in games.

I suggest following options to make Combat com more appealing:
- Combat com should be able to build all that combat engineer can build
- Combat com should have increased metal and energy output
- Increase Combat and/or Assault com weaponry, to be at least 2x T1.5 LLT or HLT 
  (with full or reduced range)
- Assault com should be able to build t1.5 eco, and have increased metal and energy generation
- Assault com being able to build tech level 2 combat engineer

**Comment by skymyj** [comment]
I will add Engineer for assault and star and supreme
