### ISSUE TITLE
Install Problems

### ISSUE THREAD

**Issue by Antarac** [techannihilation/TA#1281]
Two of my friends allowed me to install spring lobby on their Computer.
I installed different mods like BA, TA and others to test how well the installation works.

Was quiet of a desaster cause all mods install easy, but not TA.
Loads of error messages spam when downloading TA.
TA download often just fails without showing a reason.

If i don't use all my knowledge like deleting rapid folder, no chance to get TA installed.
Really bad if new players wanna play TA cause without help it takes ages to make TA work.

**Comment by nixtux** [comment]
Any chance of seeing those errors? Can't fix without it

**Comment by Antarac** [comment]
I deleted the "portable spring lobby" and all stuff in "mygames/spring folder".
Installed again spring lobby and downloading TA and i got way lesser errors now :-s
I will try repeat this on other systems to get the errors again.
Stupid i didn't keep the errors.

![errors](https://user-images.githubusercontent.com/24976973/43003519-1490f2d8-8c2d-11e8-86c5-7bd1940e42a6.png)
.

**Comment by Antarac** [comment]
I downloaded "tech annihilation test-8750-5a9907c" today.
Why do i get errors that seem to belong to other games?

![zws](https://user-images.githubusercontent.com/24976973/43366199-0d4033f4-933a-11e8-91f3-22c06163baa5.png)
