### ISSUE TITLE
Bugs for Sumo 

### ISSUE THREAD

**Issue by skymyj** [techannihilation/TA#1299]
Too much visual bugs.
Now, i can't not see them when i play.
https://cdn.discordapp.com/attachments/428484858818330624/471384361393061929/unknown.png

**Comment by Antarac** [comment]
That arrow on ground should be removed, yes ^^
The hovering Turret should be connected, yes =)

The distance between body and "shoes" could be like magnet system.
The texture on the "shoes" looks like there is some kind of technics.
Or would you insist to change that too?

I'm fine with changes but unit needs to look same from top view!
So for l

**Comment by skymyj** [comment]
Change just for turret. Players will see nothing.

**Comment by nixtux** [comment]
Fixed here with updated smoother animation https://github.com/techannihilation/TA/commit/d7b97d333b88c79ca9be440e7aee77e9b56ffdf9
