### ISSUE TITLE
 turret and sleeve speed 

### ISSUE THREAD

**Issue by skymyj** [techannihilation/TA#1370]
Atm speed is instantanetly.
I know in Ba.. it's the speed chosen.
But I played some space ship wargame anjd it's difficult for a stationnery AA weapon to shoot a fighter or someting else. In star wars, it's very hard that a destroyer shoot a x-wing cause of the projectile speed and speed tower.
At 225 until 300 speed, the tower can easely kill targets and there is sense. instantanetly kill logic. And it can be a nerf for op flak in the game

**Comment by nixtux** [comment]
But this game is techa not star wars, and was once based of BA. It's a no from me
