### ISSUE TITLE
TTL units start missing from lab build menu during game

### ISSUE THREAD

**Issue by killfreekill** [techannihilation/TA#1399]
TTL units produced by lab tend to get missing from lab's build menu during game play

**Comment by nixtux** [comment]
Which units from what labs?

**Comment by killfreekill** [comment]
As an example TTL Rez kbot from T1.5 lab or command vehicle (shooting blue goo) from T4 lab

**Comment by killfreekill** [comment]
https://replays.springrts.com/replay/55b5cc5b0c51618c630e7cedafa4adf3/

check killfree's T4 lab at around 64:00, the dreadnought and bahamut goes missing from that lab's build menu.
