### ISSUE TITLE
tll sea stationary shield not charging #bug

### ISSUE THREAD

**Issue by aronj** [techannihilation/TA#1401]
video snippet https://drive.google.com/open?id=1bduhSSVrrTrwe6fG5HCXHS2LlgJa2xyb

replay https://drive.google.com/open?id=1RCzVh5nZvbZpSJDuxKYvyEpyevBtx0ti

**Comment by skymyj** [comment]
On video, you can see the depht launcher vpulse (tlldcsta), doesn't work too.

**Comment by skymyj** [comment]
I confirm. Don't work... 
I will see, if i can do something

**Comment by skymyj** [comment]
I will create new unit and fix it
