### ISSUE TITLE
ametalmakerlvl2 - capacity

### ISSUE THREAD

**Issue by skymyj** [techannihilation/TA#1404]
In description = "Converts upto 160 Energy to Metal"
In fact = 200e
ratio M/E Balance should be 160.

**Comment by nixtux** [comment]
https://github.com/techannihilation/TA/blob/master/luarules/configs/maker_defs.lua#L29

**Comment by skymyj** [comment]
My mistake. In description is 200, in fact is 200, but on maker_defs is 160. (and should be 160).
Need change description and do something with convertion capacity. 
Was on <[KING]AutoHost2> :
![image](https://user-images.githubusercontent.com/2990630/48696994-c3360100-ebe3-11e8-942f-468ec219aad1.png)

**Comment by skymyj** [comment]
After focus, the AMetalMakerLvl1 model is an ancient model.
Best is to delete 3do, bos and lua.

So, need change the good model : https://github.com/techannihilation/TA/blob/master/luarules/configs/maker_defs.lua#L30 and https://github.com/techannihilation/TA/blob/master/units/armamaker.lua with 160 capacity
