### ISSUE TITLE
Morph's tree

### ISSUE THREAD

**Issue by skymyj** [techannihilation/TA#144]
I want to increase the battle experience for units. Goal is to give advantages for players that fight with T1 / t2 units. Many of theses morph already exist. I have  just  thinking to add news. 

My propose is about T1/T2/T3 Kbot and Vehicle. Ma propose can be modified / edited with your suggestions. We could add morph for Air or for TLL too.

With these change, we need to have 2 others modification : 
- Come back this unit. we have to transform it into T2.5 Fast green Laser (low range) with low HP : 
![nsacskv](https://cloud.githubusercontent.com/assets/2990630/24653588/ac0a4724-1936-11e7-9387-d7ce729169ca.png)
- Transform this unit into T2.5. we have to increase a little stats :
![corparrow](https://cloud.githubusercontent.com/assets/2990630/24653618/cfd1512a-1936-11e7-9251-b42c8d781f54.png)
- I didn't add the Anti Air Kbot and Vehicle. But I'm for these.

On green square : Easy to morph into this unit (like 0.1 ~ 0.15 XP)
On orange square : Medium to morph (like 0.15 ~ 0.75 XP)
On Red square : Hard or Incredibly Hard (like 0.80 ~ 2.0 XP)

https://1drv.ms/w/s!AgjKPxaKD1zLk0d3Y0n60kS9JnpZ

**Comment by skymyj** [comment]
Link updated

**Comment by ksilversurfer** [comment]
lot of work here skymyj :) nice !
I think we can change morph tree in a way you showed in document.
But any morph cant be too OP 🗡  :D
