### ISSUE TITLE
Light fusion Size 

### ISSUE THREAD

**Issue by skymyj** [techannihilation/TA#1474]
They produce 50% less than fusion, but they are so big structure..
They need decrease by 40% min, and maybe 50%
![image](https://user-images.githubusercontent.com/2990630/54072464-66865100-427b-11e9-80eb-803eba48504b.png)

**Comment by skymyj** [comment]
What do you think ? 
![image](https://user-images.githubusercontent.com/2990630/56446243-ce5f9b00-6301-11e9-8b5e-2e95ee468d18.png)

**Comment by skymyj** [comment]
![image](https://user-images.githubusercontent.com/2990630/56446356-81c88f80-6302-11e9-9090-9c0cc0e99b97.png)

**Comment by ksilversurfer** [comment]
agree to reduce size
