### ISSUE TITLE
Permissions and credits for TA:Escalation assets in Tech Annihilation

### ISSUE THREAD

**Issue by TheRegisteredOne** [techannihilation/TA#1536]
Hello, my user name, and Wotan's user name on the credits page are incorrectly spelled: https://github.com/techannihilation/TA/blob/master/credits.txt#L27. Please spell it as "TheRegisteredOne", and "Wotan". Please list all the units that used our models in the credits and provide a link to taesc.tauniverse.com. List the credits in this repo's README.md.

Also clarify the license of this repo as non-permissive. Someone took the assets from this repo and released a game on Steam with monetized DLCs: https://store.steampowered.com/app/671690/MARS_Total_Warfare/, including some of our assets as well. These devs claim Tech Annihilation is under GPL, which cannot be the case considering the copyright of the assets used.

Looking through the commit history of this repo, many newer models were appropriated from TA:Escalation without reaching out to us for additional permissions. You can't just take our assets as soon as we release them.

**Comment by skymyj** [comment]
Hey RegisteredOne. I begin to add all units and I edit username.

**Comment by skymyj** [comment]
Again thank you to permit to use your contents.
If we can share some units you need, it will be nice.
