### ISSUE TITLE
Talon permissions

### ISSUE THREAD

**Issue by TheRegisteredOne** [techannihilation/TA#1552]
I am the person who created most of the assets in the Talon race: https://www.moddb.com/mods/talon-race. Your credits are incorrect in this case, and you never asked for permissions for use.

Furthermore, please add a README.md file to this repo clearly stating all relevant assets used in this mod and clearly state that this mod includes non-GPL compliant assets that cannot be used by others.

README.md example: https://gist.github.com/pedronauck/5573168

**Comment by nixtux** [comment]
Sky do you even have permission to use talon if not remove it or I will

**Comment by sqrtone** [comment]
I want ask same question. Do you have permission Skymyj for to use talon?

**Comment by nixtux** [comment]
Actually that question is aimed at  TheRegisteredOne? Does skymyj have permission to use talon if not I will remove.

**Comment by skymyj** [comment]
I contacted TheRegisteredOne : Hi man, 
You posted few months ago on github/techannihilation about talon permission. 

We added README.md but but maybe you wanted a text that protects even better what exists.

In case you do not wish to give your agreement, we will remove the faction this week.

No matter what happened, I enjoyed developing this faction and made a few additions to it. I could send them to you.

Waiting for an answer.

skymyj

I'm waiting his answer.

**Comment by nixtux** [comment]
Well until he reply you should disable talon.

**Comment by nixtux** [comment]
Also also information about licence talks should be done here and not by private message

Quick note current licence on readme.md breaks springs licence

**Comment by TheRegisteredOne** [comment]
Hey, the license is still under MIT license. Which is incorrect. Talon and TA:Esc cannot be included under a project with MIT license.

The credits are also very incomplete. The TA:Esc unit credits are WIP for the past 5 months. The Talon dev team also cannot take credit for all of the units you added to Talon because we didn't make all of them, they should be properly attributed.

**Comment by nixtux** [comment]
Hi TheRegisteredOne can you give me unitnames for TA:Esc units which are being used without correct permission I will disable them for now, sorry I know it's a lot of work.

**Comment by skymyj** [comment]
Can't we take the problem upside down?
Instead of deactivating a faction and losing hundreds of hours of work, is it possible to change our license?

**Comment by nixtux** [comment]
You need to change it anyways it wrong. And that would be a start in the write direction

**Comment by nixtux** [comment]
Sky you can't take someone work and put it under another licence, even my work in techa you can't, it has to be under the original licence i used.

**Comment by skymyj** [comment]
The licence has changed in readme.md and we added more protection in credit.txt
Is it enough or some works is needed to be ok with TheRegisteredOne ?

**Comment by TheRegisteredOne** [comment]
Hi. Thanks for updating the license. I think the most important thing is to prevent people from using these assets in commercial products.

**Comment by skymyj** [comment]
Hey TheRegisteredOne, 
Can I have a Link on the TAESC/Talon licence ? I searched but not find.
With this, I could adapt the licence for more protection about TALON/TAESC units used here.
Thank.

**Comment by TheRegisteredOne** [comment]
There is no license. We don't intend to grant any sort of open permissions for anyone to use our content. Also, the formats for the content is all proprietary to Wargaming.net, and only exists because Total Annihilation developers have historically left modding alone since TA mods explicitly require the original game to run.

**Comment by TheRegisteredOne** [comment]
The only reason Tech Annihilation has been granted limited permissions to use TA:Escalation content is because some content was added without permissions initially, and we didn't want to force you guys to remove it, undoing your work.

**Comment by Leggir** [comment]
Whew, I'm glad Talon is staying, the content is really nice, especially the power plants. Kudos to the developers.
