### ISSUE TITLE
To do

### ISSUE THREAD

**Issue by skymyj** [techannihilation/TA#1553]
TALON : 

add t3 fus uw 
-change model turret t1 t1.5 talon

TLL : 
add t3 fus u
-Change green beam by lightning for tll t1 t1.5 and t2

ARM;
- change t3 arm plasma.by spider.

**Comment by skymyj** [comment]
Fix gadget : 
- Initial queue (Error when TLL Menu Panel selected )
https://github.com/techannihilation/TA/blob/master/luaui/widgets/unit_initial_queue.lua
- Commander Counter doesn't count Talon Commander. https://github.com/techannihilation/TA/blob/master/luarules/gadgets/mo_com_counter.lua

**Comment by sqrtone** [comment]
Disable Talon or ask spring devs to increase command cache (which is unlikly to happen):
`Warning: [CmdDescrCache::GetPtr] too many unique command-descriptions`
Spring even crash now at beginning of games (10-20min), sometimes warns about too many unique command-descriptions.
sometimes do not output any infolog.. 
adding another unit "Add T4 TRans Air" make it worse
There is cache overflow - easy fix reduce number of units in:
https://github.com/techannihilation/TA/tree/master/units
rename to *.xxx or delete

It's clear there is too many different units in game.
