### ISSUE TITLE
talon spy plane decloak

### ISSUE THREAD

**Issue by ceddralTAissues** [techannihilation/TA#1554]
TA version: Tech Annihilation test-927402191d07
Engine version: 104.0.1-1333-gce618bd maintenance

Talon T2 spyplane is not decloaked when flying through enemy fighter shield.
Spyplanes fly lower than fighters, therefore avoid hitting them directly.
Spyplanes do decloak when landed DIRECTLY on top of a landed enemy plane,
however offset of roughly half spyplane size is enough for it to not decloak.

**Comment by skymyj** [comment]
Thank for reporting. 
Should be ok with : https://github.com/techannihilation/TA/commit/4a10d08102186daecdad24539b8aa2e920a9d84b
