### ISSUE TITLE
talon_covertopscenter can not be attacked

### ISSUE THREAD

**Issue by ceddralTAissues** [techannihilation/TA#1557]
TA version: test-9278-aa0c8d0
engine version: 104.0.1-1333-gce618bd-maintenance

tested with
armraz1, airwolf3g, armpers, armorion. cortitan, talon_independence, corcom7

only corcom7 autotargeted and obeyed attack orders with its laser weapon.
all other units ignored the talon_covertopscenter.
set target can not be aimed at talon_covertopscenter.
dgun only works by aiming at ground near the building since the commander
can not get close enough to its center.

**Comment by skymyj** [comment]
They ca nbe attacked with unit at range 300+
