### ISSUE TITLE
talon gun range

### ISSUE THREAD

**Issue by ceddralTAissues** [techannihilation/TA#1558]
TA version test-9281-f7cbb04
engine version 104.0.1-1333-gce618bd maintenance

talon gun range seems to to be calculated as a cylinder,
however damage from the weapon seems to be cut off
at some spherical distance.

When a talon_llt is placed atop a high cliff, e.g. Tabula-v4 left top hill, it
will automatically target a unit at the foot of that hill but will be unable to deal any damage as the shots disappear before reaching the unit. This can prevent the turret from shooting
at a valid target.

**Comment by skymyj** [comment]
I will do test this evening. 
IT's possible to change the positionnement of aimpoint

**Comment by skymyj** [comment]
Tested and see the bug.
The shot pass over the target but inflict no damage. 
 I don't know to fix this Atm. The aimpoint is correct. I think it's about the weapontype : laser

**Comment by ceddralTAissues** [comment]
might as well be an engine bug

**Comment by skymyj** [comment]
i think it's this line : targetmoveerror = 0.1,
To test soon

**Comment by skymyj** [comment]
After test, same prob...

**Comment by sqrtone** [comment]
a lot of talon UNITS need rebalance of range, this issue is old, we need refresh it
