### ISSUE TITLE
unit_windmill_control.lua

### ISSUE THREAD

**Issue by ceddralTAissues** [techannihilation/TA#1560]
TA version: test-9294-9722a57
engine version: 104.0.1-1333-gce618bd maintenance

unit_windmill_control.lua spams errors into chat if a tllawindtrap is present on the map.

**Comment by skymyj** [comment]
I will fix it. thank.
https://github.com/techannihilation/TA/commit/eb974f6b95b0ee0d7f5f68c4efae0ae825afa43d
