### ISSUE TITLE
talon constructors ignore build orders

### ISSUE THREAD

**Issue by ceddralTAissues** [techannihilation/TA#1561]
TA version: test-9300-31e6262
engine version: 104.0.1-1333-gce618bd-maintenance

tested with: talon_psyker, talon_psyker1, talon_ack, talon_ack1, talon_aca, talon_eck

talon_aca and talon_eck are not affected

the other four ignore their first build order under certain conditions.
ignore means they stare at where they are supposed to build something
but do not build it. after some timeout the constructor proceeds to the next
element in its build queue and also stares at the location instead of building it.

steps to reproduce:
- build, morph or give one of those four cons
- do not give it a move order
- place a queue of buildings (e.g. a line by holding shift) outside the cons reach

the cons will walk towards its queue and just stare at it.

the cons can be "freed" from this behaviour by giving it some order it is able
to execute. afterwards this behaviour is no longer reproducable.

for talon_ack and talon_ack1 this also occurs if the first order is placed
within their reach.

**Comment by skymyj** [comment]
Done with : https://github.com/techannihilation/TA/commit/24fd6477dd4615de2576a3cadb0986cf361ae8d9
