### ISSUE TITLE
stuck units

### ISSUE THREAD

**Issue by ceddralTAissues** [techannihilation/TA#1570]
Tech Annihilation test-9560-0862dea
spring 104.0.1-1455-g39f8fbd maintenance

units built in an arm t3 veh lab are very often unable to leave the lab.
tested on techno lands v3.1 and blue fields with t3 construction vehicle,
command vehicle, anti t3/t4 and cryptoblaster.

**Comment by skymyj** [comment]
Fixed with : https://github.com/techannihilation/TA/commit/6adfb7060803300027c62768f8ecc76837c672ed
