### ISSUE TITLE
talon_planetkiller aiming model angle

### ISSUE THREAD

**Issue by ceddralTAissues** [techannihilation/TA#1571]
TA version: Tech Annihilation test-9581-36a20a2
engine version: 104.0.1-1455-g39f8fbd maintenance

The angle at which the talon_planetkiller positions itself to shoot
at a target seems to be backwards. The model points up, when
shooting at an enemy below itself and points further up the closer
that enemy is.

**Comment by skymyj** [comment]
Fixed
