### ISSUE TITLE
heros do not move

### ISSUE THREAD

**Issue by ceddralTAissues** [techannihilation/TA#1572]
TA version: Tech Annihilation test-9581-36a20a2
engine version: 104.0.1-1455-g39f8fbd maintenance

Heros do not follow move commands, they merely turn in
the direction of the move command.
Tested with abroadside and cdevasator.

**Comment by skymyj** [comment]
After make test. It works.
I will see other test and games.

**Comment by ceddralTAissues** [comment]
Still broken in
Tech Annihilation test-9587-9946424
tested with talon_independence on Techno Lands Final v3.1

**Comment by skymyj** [comment]
Fixed now
