### ISSUE TITLE
talon_planetkiller shoots through commander

### ISSUE THREAD

**Issue by ceddralTAissues** [techannihilation/TA#1573]
TA version: Tech Annihilation test-9581-36a20a2
engine version: 104.0.1-1455-g39f8fbd maintenance

At a large enough distance, talon_planetkiller's laser
passes through enemy commanders without hurting them.
It does not occur at distances strictly larger than some threshold,
but occurs with higher probability at larger distances.

**Comment by skymyj** [comment]
Fixed
