### ISSUE TITLE
exoarm not hit by ground dgun

### ISSUE THREAD

**Issue by ceddralTAissues** [techannihilation/TA#1574]
TA version: TechAnnihilation test-9581-36a20a2
engine version: engine version: 104.0.1-1455-g39f8fbd maintenance

Dgun passes through exoarm if it is aimed at the ground.
Aiming at the unit center works.
Tested only on flat surface.

**Comment by skymyj** [comment]
Fixed

**Comment by skymyj** [comment]
![image](https://user-images.githubusercontent.com/2990630/71561982-31ebbc00-2a7e-11ea-945b-43e84d75cb62.png)
Indeed, nice collision box bug
shooting foot was ignored

Thanks :)
