### ISSUE TITLE
Failed to load: gui_awards.lua  ([string "LuaRules/Gadgets/gui_awards.lua"]:72: attempt to index field 'armuwlightfus' (a nil value))

### ISSUE THREAD

**Issue by abma** [techannihilation/TA#1579]
see [infolog.txt](https://github.com/techannihilation/TA/files/4023986/infolog.txt)

**Comment by skymyj** [comment]
Fixed but need to test many times. 
I deleted many units, and i will fix proper in next version. 
Thanks
