### ISSUE TITLE
talon mines do not trigger

### ISSUE THREAD

**Issue by ceddralTAissues** [techannihilation/TA#1583]
Talon mines do not trigger if a unit is closeby. Possibly because
script = "mines_lus.lua",
is missing from their unitdefs

**Comment by skymyj** [comment]
Omg. You should be right 
Didn't see this line. 
Thank again

**Comment by skymyj** [comment]
Next talon unit will call Ceddral : 
![image](https://user-images.githubusercontent.com/2990630/72024250-45183c00-3275-11ea-8806-85f6cc7f2533.png)

**Comment by ceddralTAissues** [comment]
please ask for permission before putting my name on stuff

**Comment by skymyj** [comment]
Sorry. Do you want a unit with your surname ?

**Comment by ceddralTAissues** [comment]
sure, go ahead
