### ISSUE TITLE
Some Warnings from infolog.txt

### ISSUE THREAD

**Issue by abma** [techannihilation/TA#1593]
[f=-000001] Warning: [CreateYardMap] talon_blt1: given yardmap requires 12 extra char(s)!
[f=-000001] Warning: [CreateYardMap] talon_gen: given yardmap contains 7 excess char(s)!
[f=-000001] Warning: [GetCategory] too many unit categories (32), skipping tiny,
[f=-000001] Warning: [CreateYardMap] tllgate3: given yardmap contains 6 excess char(s)!
[f=-000001] Warning: [CreateYardMap] tllgate4: given yardmap contains 16 excess char(s)!
[f=-000001] Warning: removed the "armaahpns" entry from the "armcs" build menu
[f=-000001] Warning: removed the "cbuilderlvl2" entry from the "corcom7" build menu

Tech Annihilation test-9652-c6bf601

**Comment by skymyj** [comment]
All fixed except : Warning: [GetCategory] too many unit categories (32), skipping tiny,

**Comment by sqrtone** [comment]
It is possible to reduce number of categories in TA, need some work tho..

**Comment by sqrtone** [comment]
At the moment we have:
```
TechaCategories = {
	["all"] = 0,
	["antiflame"] = 31,
	["commander"] = 28,
	["constr"] = 1,
	["hover"] = 2,
	["huge "] = 17,
	["large"] = 3,
	["level1 "] = 14,
	["level2 "] = 29,
	["level3 "] = 27,
	["medium "] = 24,
	["mediumvtol"] = 23,
	["mine "] = 30,
	["mobile"] = 4,
	["notdefense"] = 5,
	["nothovernotvtol "] = 12,
	["notmobile "] = 13,
	["notsub"] = 6,
	["notsubnotship"] = 7,
	["notvtol"] = 8,
	["notweapon"] = 9,
	["plant "] = 15,
	["small "] = 21,
	["smallvtol "] = 25,
	["sub "] = 20,
	["supership "] = 18,
	["surface "] = 10,
	["tiny "] = 22,
	["tinyvtol "] = 26,
	["underwater "] = 16,
	["vtol "] = 11,
	["weapon "] = 19
}
```

**Comment by sqrtone** [comment]
```
constr = {aach,abuilderlvl1,abuilderlvl5,armaca,armach,armack,armacsub,armacv,armbeaver,armca,armch,armck,armcom,armcom1,armcom4,armcom5,armcom6,armcom7,armcom_fusion,armcs,armcsa,armcspider,armcv,armeca,armecs,armecv,armfark,armmin,armmls,armmlv,armsmc,cach,cbuilderlvl1,cbuilderlvl5,consul,coraca,corach,corack,coracsub,coracv,corassis,corca,corch,corck,corcom,corcom1,corcom3,corcom5,corcom6,corcom7,corcom_fusion,corcs,corcsa,corct,corcv,coreca,corecs,corecv,corfast,cormin,cormls,cormlv,cormuskrat,pinchy,talon_aca,talon_ach,talon_ack,talon_ack1,talon_acs,talon_acv,talon_builderlvl3,talon_ca,talon_ch,talon_chrysoberyl,talon_com,talon_com1,talon_com3,talon_com5,talon_com6,talon_com7,talon_com_fusion,talon_cs,talon_csa,talon_cv,talon_dioptase,talon_eca,talon_ech,talon_eck,talon_ev,talon_medic,talon_mlv,talon_psyker,tllaca,tllach,tllack,tllacs,tllacsub,tllacv,tllbuilderlvl1,tllbuilderlvl2,tllbuilderlvl3,tllca,tllchover,tllck,tllcom,tllcom1,tllcom3,tllcom5,tllcom6,tllcom7,tllcom_fusion,tllcs,tllcsa,tllcsub,tllcv,tlldoc,tlleca,tllecs,tllecv,tllhtcb,tllmando,tllmarmelade,tllmlv,tlltsetse}
```

**Comment by skymyj** [comment]
Less categories : 

["all"]
["construction"]
["structure "] 
["air"]
["surface"]
["underwater "]
["notmobile"]
["notweapon"]
["tiny "]
["small "]
["medium "]
["large"]
["huge"]
["commander"]

**Comment by sqrtone** [comment]
**looks way better skymyj**
cant figure out what purpose was of the "constr" category...
any ideas?

**Comment by skymyj** [comment]
=> These categories are enough. I think.
["structure"]
["air"]
["surface"]
["underwater"]
["tiny "]
["small "]
["medium "]
["large"]
["huge"]

**Comment by skymyj** [comment]
Do you know a tool that change all unitdef/weapondef with new values ?
Cause, we have 1000+ changes to do

**Comment by skymyj** [comment]
I think, we have to check if we delete the lvl1 2 3, a nano for example could morph into next level without these categories
