### ISSUE TITLE
Make modoption mo_impmulti permament!

### ISSUE THREAD

**Issue by ZoneTrooperTA** [techannihilation/TA#1596]
Im amazed of the gameplay and physics with this game option.
I would like to see this option be hard coded at 2.5 or 3 or be default
It adds great taste to game!

Thanks !

**Comment by skymyj** [comment]
Atm, it will stay as an option for 2 reasons :  
- there is a lack of units missing.
- some players complain.

But, I think, we could create a new weapon type to create impulse.
