### ISSUE TITLE
Failed to load: gui_awards.lua  ([string "LuaRules/Gadgets/gui_awards.lua"]:126: '}' expected (to close '{' at line 24) near 'UnitDefNames')

### ISSUE THREAD

**Issue by abma** [techannihilation/TA#1609]
[f=-000001] Error: Failed to load: gui_awards.lua  ([string "LuaRules/Gadgets/gui_awards.lua"]:126: '}' expected (to close '{' at line 24) near 'UnitDefNames')

104.0.1-1455-g39f8fbd maintenance + Tech Annihilation test-9724-270bd4b

**Comment by skymyj** [comment]
Fixed. Thanks
