### ISSUE TITLE
tllmeteor range

### ISSUE THREAD

**Issue by ceddralTAissues** [techannihilation/TA#1616]
TA version: Tech Annihilation test-9808-4ca1355
engine version: 104.0.1-1464-g4f428c8

Range of tll meteor is not actually limited to the range shown by the red range circle.
Instead it can shoot anywhere. Tested on Techno Lands Final v3.1 all the way across
the map.

**Comment by skymyj** [comment]
With the t5 gate, the range is imho not a problem
