### ISSUE TITLE
Bug with collision volume gadget

### ISSUE THREAD

**Issue by skymyj** [techannihilation/TA#1617]
[string "LuaRules/Gadgets/unit_dynamic_collision_vol..."]:379: in function 'GameFrame'
	[string "LuaRules/gadgets.lua"]:880: in function <[string "LuaRules/gadgets.lua"]:878>
	(tail call): ?"
[f=0072322] [Game::ClientReadNet][LOGMSG] sender="[FLAT]Earther" string="[Internal Lua error: Call failure] [string "LuaRules/Gadgets/unit_dynamic_collision_vol..."]:379: attempt to compare nil with number
stack traceback:
	[string "LuaRules/Gadgets/unit_dynamic_collision_vol..."]:379: in function 'GameFrame'
	[string "LuaRules/gadgets.lua"]:880: in function <[string "LuaRules/gadgets.lua"]:878>
	(tail call): ?"
[f=0072324] [Game::ClientReadNet][LOGMSG] sender="MrWeak" string="[Internal Lua error: Call failure] [string "LuaRules/Gadgets/unit_dynamic_collision_vol..."]:379: attempt to compare nil with number
stack traceback:
	[string "LuaRules/Gadgets/unit_dynamic_collision_vol..."]:379: in function 'GameFrame'
	[string "LuaRules/gadgets.lua"]:880: in function <[string "LuaRules/gadgets.lua"]:878>
	(tail call): ?"
[f=0072324] [Game::ClientReadNet][LOGMSG] sender="gopnic" string="[Internal Lua error: Call failure] [string "LuaRules/Gadgets/unit_dynamic_collision_vol..."]:379: attempt to compare nil with number
stack traceback:

**Comment by sqrtone** [comment]
Propably fixed in https://github.com/techannihilation/TA/commit/98535dfefbc1d6b62ffef32096ac4c509b9a8d24
