### ISSUE TITLE
Talon bugs/missing units.

### ISSUE THREAD

**Issue by Leggir** [techannihilation/TA#1618]
My appologies, I can't seem to remember how to get unit names for this post. 

Talon Commander, starting as Assault, Star, and Supreme, the shield won't recharge unless you order him to attack something, like the ground next to him. Not sure why. Also neither of the level 2 builder boats can build a plasma shield in water, although a level 3 is available.

Game: Test 9920
Engine: 1474

**Comment by skymyj** [comment]
Thank Leggir for your help. 
The naval shield existed but not added to cons. 
It's done. 
For com shielded, i saw the bug but atm, i don't know why. Need to fix it.

**Comment by skymyj** [comment]
Shield for commander is just Fixed
