### ISSUE TITLE
TLL Metal Storage not targetable.

### ISSUE THREAD

**Issue by Leggir** [techannihilation/TA#1620]
TLL Metal Storage not targetable. Units will just sit and shoot it all day.

Engine 1333
Game 9920

**Comment by skymyj** [comment]
Can i have unitname (on unit, push on space to see it and other stats)
I tested t1 t2 and it works

**Comment by Leggir** [comment]
Ok, I'm not sure what I'm doing wrong. Without unit highlighted or with them highlighted, i point at them and press space, nothing happens. I see a tool tip at the bottom suggesting the various commands I can do.

Also I'm not sure if this is at issue, I am testing with Engine 1333 as it is the last engine that works with AAI so I can play single player with an AI. Every newer engine just crashes before loading the level, although HughAI sometimes will play until the camera pans over, then crash. Hard to test without anyone to play against.
