### ISSUE TITLE
Too many diffrent units in game.. - test versions not playable anymore

### ISSUE THREAD

**Issue by sqrtone** [techannihilation/TA#1631]
Disable Talon or ask spring devs to increase command cache (which is unlikely to happen):
`Warning: [CmdDescrCache::GetPtr] too many unique command-descriptions`
Spring even crash now at beginning of games (10-20min), sometimes warns about too many unique command-descriptions.
sometimes do not output any infolog.. 
adding another unit "Add T4 TRans Air" make it worse
There is cache overflow - easy fix reduce number of units in:
https://github.com/techannihilation/TA/tree/master/units
rename to *.xxx or delete

It's clear there is too many **different** units in game.

At moment only 3.38 is playable tho still crash when you try "/give all" with default "WorkerThreadCount" number

https://springrts.com/mantis/view.php?id=6167

**Comment by skymyj** [comment]
thank for.this report. i will denete many unis unused.

**Comment by skymyj** [comment]
First list for disable units : 
apache.lua
armah256.lua
armblz
armcd
armcrabe
armraven1
armsh175
armscar
armlightfus
corlightfus
armrad1
corrad1
All correch / Armrech
dao

**Comment by nixtux** [comment]
No just no thoses 20 odd units will not fix your issue, you need to disable around 200+ to really fix issue and be future proof, so remove talon and be done with it, don't disable gadgets just because you added a new faction and it's causing you issue your logic is all wrong

**Comment by sqrtone** [comment]
**Best option is to remove talon, spring rts has limited cache.**
Disabling some gadgets may help and may not.
It is unsafe when you have too many diffrent units.

**Comment by skymyj** [comment]
If there is no other solution, for sure talon have to be deleted.
How proceed ? Do we remove files or transform all lua into xxx + adjust some widget/gadget ?
It will good if we can send a request on spring engine team to increase cache.

**Comment by skymyj** [comment]
After have deleted many olds units or unused, there is no bug reported from 1 week.
I think, we need fix max unit at 1286 = number atm. For each new add, we should delete 1 other unit.
I think the limit is at 1290~1300.

**Comment by skymyj** [comment]
Anyway, i didn't have more add to do for talon or tll. My job is finished about faction game design

**Comment by nixtux** [comment]
Testing with gadgets still disabled is pointless imo, enable them and try again

**Comment by sqrtone** [comment]
Crashes still happen, but less often, but still.

**Comment by sqrtone** [comment]
We just crashed after 25min of game

**Comment by sqrtone** [comment]
```
[21:50:57] <[MOL]Silver> Spring crash becouse there is too many units in definitions
[21:51:14] <[MOL]Silver> and cache overflowing from time to time
[21:51:19] <[MOL]Silver> =  crash
[21:51:20] <rX> just disable talon...

```
