### ISSUE TITLE
Widget bug

### ISSUE THREAD

**Issue by skymyj** [techannihilation/TA#1642]
In a game, if you manually deselect "defense range" widget, on next ta launch, the top right menu will disapear.

Infolog : 
[widgets.lua] Error: false
[t=00:00:17.172640][f=-000001] [widgets.lua] Error: Error in Initialize(): [string "LuaUI/Widgets/gui_options.lua"]:2749: attempt to index field '?' (a nil value)
[t=00:00:17.172640][f=-000001] [widgets.lua] Error: Removed widget: Options

Is it possible to delete this issue ?
Thank.

**Comment by sqrtone** [comment]
yes i can fix

**Comment by silvapp** [comment]
fixed
