### ISSUE TITLE
Errors from infolog.txt, i.e. could not find a parser for model "gok_amaker_dead" (+ desyncs)

### ISSUE THREAD

**Issue by abma** [techannihilation/TA#1647]
[t=00:01:10.990740][f=0018415] Error: could not find a parser for model "gok_amaker_dead" (unknown format?)
[t=00:02:23.795090][f=0027628] Error: could not find a parser for model "gok_damascus_dead" (unknown format?)
[t=00:05:38.472878][f=0045055] Error: could not find a parser for model "ametalmakerlvl2_dead" (unknown format?)
[t=00:09:48.134860][f=0064596] Error: could not find a parser for model "gok_aap_dead" (unknown format?)
[t=00:10:10.739267][f=0066391] Error: could not find a parser for model "gok_eap_dead" (unknown format?)
[t=00:10:52.043632][f=0068932] Error: [GetFeatureDef] could not find FeatureDef "heap"
[t=00:12:25.455799][f=0075877] Error: could not find a parser for model "armurad_head" (unknown format?)

[infolog.txt](https://github.com/techannihilation/TA/files/7841636/infolog.txt)

**Comment by skymyj** [comment]
Thanks abma. 
I will fix them.

**Comment by skymyj** [comment]
Fixed
