### ISSUE TITLE
tooltip, fontsize

### ISSUE THREAD

**Issue by losbellos** [techannihilation/TA#1648]
Hello Dev,

Can I ask you to make the tooltip of the unit building icon on the left. somehow available and the fontsize of those word thats shows up in the tooltip could be at least 20?
If possible.

Also I have seen in other games that the fontsize of the panel and the info box,  (hover the mouse over a unit and the infobox shows health, user owner etc), text chat., main info panel etc can be changed. Could you please read the fontsize for these from the config file? Like smallfont size and fontsize and use them instead of pre-set size. Fully for all panels info etc.

Thank You!

**Comment by silvapp** [comment]
fixed

**Comment by losbellos** [comment]
Ohj thank you so much, tell me what should I do to increase the font or it will increase by the usual custom font settings?

**Comment by losbellos** [comment]
> fixed

Hello pls can you tell me how to use this font size setting thingy because for me now working, I updated it... 
fontsize=30 and smallfontize=30 doent change a bit...
Thank you!
