### ISSUE TITLE
GOK selectable, but launches as Arm. 

### ISSUE THREAD

**Issue by Leggir** [techannihilation/TA#1658]
So I've tried two different computers, running the latest SpringLobby 0.274. The latest available Tech Annihilations (10683-10895). Engine 105. I've tried hosting a multiplayer with just my two PC's and tried doing a Single Player with a NullAI. As the game launches and just before the commander appears, the GOK build options are visible, but as soon as the game is ready to play, it launches as Arm every time. What can I do to make this work, or is this a known issue with no current workarounds?

"SpringLobby 0.273-1-g46ec86698 (windows64)
Configuration file: C:\Users\Leggir\AppData\Roaming\springlobby\springlobby.conf (writable)
LobbyWriteDir (C:\Users\Leggir\AppData\Roaming\springlobby\)
	WX: yes POSIX: yes TRY: yes
CachePath (C:\Users\Leggir\AppData\Roaming\springlobby\cache\)
	WX: yes POSIX: yes TRY: yes
ExecutableFolder (C:\Program Files (x86)\SpringLobby2\)
	WX: yes POSIX: yes TRY: yes
DownloadDir (C:\Users\Leggir\Documents\My Games\Spring\)
	WX: yes POSIX: yes TRY: yes
Current SpringData: (C:\Users\Leggir\Documents\My Games\Spring\)
	WX: yes POSIX: yes TRY: yes
Current unitsync: C:\Users\Leggir\Documents\My Games\Spring\engine\windows64\105.0\unitsync.dll
Current Spring engine executable: C:\Users\Leggir\Documents\My Games\Spring\engine\windows64\105.0\spring.exe
Portable mode: no
Compiled with wxWidgets 3.0.5.0
Global log level: 5 (up to and including Info)
PR-Downloader log level: 5 (up to and including Info)
Started with: 
C:\Program Files (x86)\SpringLobby2\springlobby.exe "

**Comment by skymyj** [comment]
Hey Leggir.
Strange, I didn't meet this issue.
In test mode from spring.exe, can you choose the gok faction ? 
Same bug with other factions ?

**Comment by Leggir** [comment]
Skymyj, 
I am able to select the the gok in Spring Test and it works correctly.
I'll try it via the SpringLobby in Multiplay
So I tried it with 0.274 and 0.270 versions of Spring Lobby, same result. Hosted new Multiplayer, launched game with the same result. I recorded a 8-second video of it...
[https://youtu.be/ajLFmszG1tw](url)

**Comment by Leggir** [comment]
I don't have any problems starting with any of the other factions.

**Comment by Leggir** [comment]
I have been trying various things. I can get the GOK to play via SpringLobby if I select them at the map startup. However usually the first time I load a new map, I have to start play on the map, quit, and restart. The 2nd time it'll show the team selector. 

BTW, is there some way to extend the team selection choice as it's probably only 2 or 3 seconds and I'd like to change to 10 seconds.

**Comment by skymyj** [comment]
If you want to play with them for testing units for example, you can play with cheat.
/cheat if you are in local, then /give gok_com
Or Lobbyserver, !send /cheat, then /give gok_com
Maybe, it's your graphics resolution.
