### ISSUE TITLE
Known issues since merging #1671

### ISSUE THREAD

**Issue by jochumdev** [techannihilation/TA#1672]
#1671 is my feat/s3o merge, it brings a lot Features but sadly also some bugs.

- [x] units and buildings are to dark (tizbac the hero fixed it)
- [x] When running over spads luaui doesn't work
- [x] All Hero's don't move.
- [x]  Some units have wrong culling
  - [x] rumad_solar
  - [x] talon_win
- [x] gui_unit_stats.lua broken
- [x] tiz portal broken collision volume
- [x] rumad_antinuke is veh again
- [x] t3 ?arm? fac has no unitpic.
- [ ] fighters have lot's of damage vs. land?

**Comment by tizbac** [comment]
- [ ] arm antinuke lvl1 has missing polygon on one of the doors
- [ ] cmetalmakerlvl2 has missing polygons on top

**Comment by jochumdev** [comment]
- [x] corarad
- [x] coralab

**Comment by jochumdev** [comment]
- [x] arm shiny
- [x] armcv
- [x] armecv
- [x] armmoho
- [x] armspid
- [x] armhope
- [x] arm_broadside
- [x] armarch

**Comment by jochumdev** [comment]
- [ ] tll weapons blink when moving, seems to be cus_gl4

**Comment by jochumdev** [comment]
- [ ] tll t2 mex ugly.

**Comment by jochumdev** [comment]
NO more relevant.
