### ISSUE TITLE
Anti Rocket/Missile Laser Units/Defense

### ISSUE THREAD

**Issue by Antarac** [techannihilation/TA#183]
Make the Player able to defend himself against
incoming Rockets and Missiles like with Shield
against Artillery and Anti-Nuke against Nuke.

Add Anti Rocket/Missile Laser to existing
Units and Defense or add new Units.

Anti-Rocket Laser could have a really high fire rate like a
Machinegun so they would look different to other lasers.
For Example a burst of 7 Shots in 0.5 seconds and
a brake of few seconds for reload/cooldown.

Add "Health Points" to Rockets/Missiles so you need many
T1 Anti-Rocket lasers to destroy a T3 Rocket/Missile.
Give "Nuke", "Anti-Nuke", "Anti-Minefield", "Tac Nuke" and "Tac EMP"
many "Health Points" and Anti Rocket/Missile Laser wont be a threat

If range of Anti Rocket/Missile Laser is small,
Rockets/Missiles should not explode if they
get destroyed by the laser.

**Comment by ksilversurfer** [comment]
I like the idea, and i think it can be done.

**Comment by nixtux** [comment]
It's can be, it's been sort of asked for before also, but more as a way to defeat tactics nukes

**Comment by Antarac** [comment]
You could use them also against tac nukes since there
is no way at all to defend yourself against them.
Its fair to have a counter strategy also for missiles and
rockets not only Anti-Nukes and Shield.

Anti-Rocket-Laser should have very small range so you would
need hundreds of them to be safe from all enemy rockets.
You can only secure small Areas against Tac-Nukes
and other incoming rockets.

They could also need to go into position like artillery
to make them slower.

**Comment by nixtux** [comment]
All rockets & missiles, does you idea include AA? It would be expensive at that point
Does it include core banisher which missile fires at 45 degrees? Would look odd same if it fired at Samson etc

**Comment by nixtux** [comment]
Or any other missile which fly close to land

**Comment by nixtux** [comment]
Also about the health point how will the user be aware of how many, drawing against a moving projectile may cause issue

**Comment by nixtux** [comment]
Added, Closing issue
