### ISSUE TITLE
Commander Slide

### ISSUE THREAD

**Issue by Antarac** [techannihilation/TA#184]
Make Commander able to slide down a Hill if it's really steep.

This works in real life with good Shoes
if its steep and you can hold balance.
Commander could have animation with one Arm in the back
like Humans do usually when they slide down a steep Hill.

Commander automatically slides down a hill if he
gets order to move down the hill/that direction.
No additional button needed for this auto feature.
It gives Commander more "Character" of a High Tech Machine.
Jump and slide could be good feature combined to attack or escape.

It could throw out little Sparks and a bit of
Smoke when Commander slides down a hill.
If he is invisible you just see Sparks and
Smoke down the Hill.

**Comment by ksilversurfer** [comment]
Nice idea, but i think it is not possible to do... becouse pathing is a engine feature.
Maybe Nix help here

**Comment by Antarac** [comment]
Only change the animation and movement speed.
Pathing should have nothing to do with it.

If the Commander is on way down the hill he basically
changes to slide animation and he gets faster.

Would be needed to detect how steep it is and if the direction is right.

**Comment by nixtux** [comment]
It's could be possible,  but the work involved outweighs the gain imo.

**Comment by Antarac** [comment]
Other Ideas for the Gentlemen? =)

"Commander Auto Drone"
Like a Pet that could repair or fight
and doesn't need/take commands from Player.

Morphed Commander could be able
to build more factorys like
tortoise, chopper, hover, etc.

Anti-Air upgrade for commander T1 - T4.
Gets more expensive with every level.

Rocket pack building for commander.
Additionally to jump building or to give
it for example to TLL only instead jump.

To many morphs but still ^^
T1 	Commander
T1.5	Battle Commander / Ecoing Commander
T2	Assault Commander
T2.5	Drone Commander / U-Boat Commander
T3	Star Commander
T3.5	Stealth Commander / Flying Commander
T4	Supreme Commander
T4.5	Transform Commander / Nuke Commander
T5	Planet Destroyer Commander

**Comment by Antarac** [comment]
I gonna close this Issue and add all ideas
for Commanders to the Weapon list.
