### ISSUE TITLE
Unit Morph Buttons

### ISSUE THREAD

**Issue by Antarac** [techannihilation/TA#187]
If you select a group of units, and among them are a few that
can be morphed, the button to morph is still greyed out. 

You need to click every single unit  to morph and you loose lots of time.
Would be good if the buttons work even if i select all my units.

**Comment by ksilversurfer** [comment]
yep its a bug in code

**Comment by Antarac** [comment]
If you can fix that would be really cool Silver!

It's a pain in the ass to search the units and the
great morph feature gets used lesser of course.

**Comment by nixtux** [comment]
I think its engine not gadget (after some debug echos), best solution would be a morphed only selection widget?

**Comment by nixtux** [comment]
Added workaround here https://github.com/techannihilation/TA/commit/0ab41870a532eef7facc7fd4717f07c0e3755bd2

**Comment by Antarac** [comment]
Cool, looking forward to test it =)

I don't know why it's "blocking",
but if i can do something just tell me.

**Comment by nixtux** [comment]
Ah the blocking label just mean this issue needs to be fixed before a release as it either a major bug or a really old issue (which it was in this case).

**Comment by Antarac** [comment]
I see, thanks for explaining.

**Comment by Antarac** [comment]
It's quiet rare but sometimes it works.
I choosen all "Crasher" aa bots, morph
symbol was greyed out, i clicked it and
a few bots started to morph.

You can see at 12:53 in the replay.
I hope that might help to find more easy
solution since it works at least sometimes.
https://www.sendspace.com/file/fgp3wj

**Comment by nixtux** [comment]
On mouseover it will now auto trim selected units to morphable only units https://github.com/techannihilation/TA/commit/3bb7a8d2f4f2b0063066b0a07b5191062bec216f
