### ISSUE TITLE
Ships "squeezed" to death in bay

### ISSUE THREAD

**Issue by Antarac** [techannihilation/TA#189]
Game time 23:00 "Enforcer - Destroyer" gets smashed at coast.
https://www.sendspace.com/file/rmgodw
A little bay, game speed 30 and a group of core T1 ships
patroling close to coast are enough to repeat the bug.

Could repeat bug on maps:
Island Paradise V2
Red_Triangle-V02
Red_Triangle_ReMake-V02
Speed_Calamity_V1
Trinity

**Comment by Antarac** [comment]
Just figured out that if you make a single ship
patrol close to coast in a bay it explodes also.

Looks like it gets "squeezed" to death between
the polygons of the maps if it wanna make a
turn but has not enough space like in a bay.

It changes position sligthly every
frame (flickering or how you call that)
when it touch the coast .

**Comment by nixtux** [comment]
Can you make me a short demo of this please

**Comment by Antarac** [comment]
I tried to squeeze the Commander too, didn't work.

http://replays.springrts.com/replay/7ef403590647373d74ca5075fe139729/

Length of unit collision box,
curve movement of ships
and shape of terrain collision
seems to be connected with
this but hard to tell.

**Comment by Antarac** [comment]
I seen a ship explode on an straight coast.
Maybe it got something to do with ships
touching the ground?
