### ISSUE TITLE
Plane-Flak-Glitch-Story

### ISSUE THREAD

**Issue by Antarac** [techannihilation/TA#199]
Once upon a time there was a T2 Flak on a hill defending an outpost.
Enemy planes landed at the feet of the hill and one surived.
The Flak kept shooting at it but were sadly only hitting the hill.
Gunships came and destroyed the outpost since
the Flak was still distracted!
A glitch was born, the game was lost...

**Comment by ksilversurfer** [comment]
hmmm need make some tests

**Comment by Antarac** [comment]
Searched often for the replay where it
happened to me but couldn't find it at all.
Made a replay with cheats.
https://volafile.org/r/cgzxq224

**Comment by ksilversurfer** [comment]
never noticed that ... !

**Comment by Antarac** [comment]
Is there actually a script that tells if units hit ground/hill not target?
