### ISSUE TITLE
Pushing units aside

### ISSUE THREAD

**Issue by Antarac** [techannihilation/TA#204]
Units are able to push others aside
to make their way trough Base and Units.
My Krogoth doesn't and gets stuck
on my tiny T1 Mine Layer Vehicle.

I observed often big bunch of Construction
Units move trough a small pass.
They push each other to make their way trough
but some get pushed into the terrain where
they cant move and they are useless unless you
take the time and lift them with Air Transport.

Which Variables does belong to this
and what can i do about it?

**Comment by Antarac** [comment]
These are all Core Units i found that can't even be
pushed aside from T4 Krogoth for some reason.

Wolverine T1 Kbot
Rocketeer T1.5 Kbot
Morty T2 Kbot
Pillager T2 Vehicle
Macross T3 Kbot
Gorilla T3 Kbot
Archdemon T3 Kbot
Juggernaut T3 Kbot
Krogoth T3 Kbot
Mauler T3 Vehicle
Kronos T3 Vehicle
Metron T3 Vehicle
MegaTron T4 Kbot
Galacticus T4 Kbot
Super Krogoth T4 Kbot

**Comment by nixtux** [comment]
All heavy units and artillery have the pushResistant unitDef tag set

**Comment by nixtux** [comment]
It's was added so small unit can't push bug units, also added so pushing does not move any artillery out of the way you had setup

**Comment by Antarac** [comment]
Krogoth behaves like he thinks he can push the unit aside.
So he treats it different than a building for example.
Is there a way he treats that units like a building, while
finding his way, instead trying to walk trough it?

**Comment by ksilversurfer** [comment]
im not sure if this is still valid
