### ISSUE TITLE
"Rollerblader Robots"

### ISSUE THREAD

**Issue by Antarac** [techannihilation/TA#205]
The walking animation of some robots is slower
than their movement speed.

Is there a Variable for "Animation Speed"
to fix rollerblade-like walking?

**Comment by nixtux** [comment]
Which units does this issue effect

**Comment by Antarac** [comment]
Most robots do, if you look more close, if i may say that.

Lets take the Commanders as an example since People look more often at it.
Its just the starting Commanders and no morphed commanders i checked.
TLL Commander walking animation is only like 10% slower than actual movement speed.
ARM Commander walking animation is like 20% slower.
CORE Commander walking animation speed seems to be 25% - 30% slower.

These Kbots are a good example.
Core Kbots Punkie and Necro walking animation speed is at least 50% slower than movement speed.

I can list more rollerblading robots if needed.

**Comment by ksilversurfer** [comment]
well maybe.. i would say its very very minor issue
