### ISSUE TITLE
New icons 

### ISSUE THREAD

**Issue by nixtux** [techannihilation/TA#211]
Please list any icon that are hard to distinguish, look strange etc

Arm t1 radar the antenna needs to be drawn 90deg to what it is now
Shipyard icon need attention it's hard to tell which lab

**Comment by nixtux** [comment]
factory icons mk2  https://www.dropbox.com/s/wd7x71c8k0o31rs/Screenshot_2017-05-03_23-02-02.png?dl=0

**Comment by nixtux** [comment]
New radar and factory icons added, I will leave issue open for now incase there are more I've missed

**Comment by Antarac** [comment]
Core T1 Floating Metal Maker, just top plate/polygons are shown. rest is missing.

Core Tortoise Factory, Hingeback and Construction Tortoise are in blue player color.

T3 Vehicle Factory, Cronos und Black Tiger diffuse.

T3 Energy Storage is in blue color.

Core AK Cannon is in blue color.

All Core Research Center pictures are diffuse.

Core T1 Airport, Fiend is in blue color.

Core Helicopters, Tyson and Apache picture is in blue player color.

Core T3 Airport, Shrike is in blue player color.



Arm Intelligence jump looks a little bit diffuse.

Arm T1 Radar Tower and Floating Radar Tower pictures are diffuse.

Arm T2 Radar Tower picture is diffuse.

Arm T2 Kbot Factory, Pelican picture is diffuse.

Arm T3 Vehicle Factory, Rex and Crypto-Blaster pictures are diffuse.

Arm T3 Airport, Air Wolf has red color instead blue.

Arm Dragons Claw picture is at least 1/4 to big.

**Comment by Antarac** [comment]
Core Nano level 2 morph called Hysteric

Core Nano level 3 morph called Super Shield and MLRS mixed? I might got it wrong.

TLL T3 Kbot, Grim Reaper picture is diffuse.

TLL T3 Vehicle Factory, Avatar picture is in blue player color

TLL Center Station picture is diffuse.

TLL T1 Vehicle Factory, Pacifier picture is diffuse.

TLL T1 Nano turret and floating nano turret picture is diffuse.

TLL Floating Radar Tower picture is diffuse.

TLL Torpedo launcher model misses the middle part on the picture.

TLL KrakeN - Floating Plasma battery picture is diffuse.

Almost all radar towers from all factions got diffuse pictures.
Dragon claws and perimeter cameras from all factions look to big.
I guess colors will stay like that but still wrote it down.
Can check again, after all changes are made, if needed.

**Comment by nixtux** [comment]
K will fix diffused later, found issue

**Comment by nixtux** [comment]
https://github.com/techannihilation/TA/commit/91a784368e7a18c171add05ce1a0eb4d7ba9909a

**Comment by nixtux** [comment]
Closing all should be fixed
