### ISSUE TITLE
TLL is lacking where

### ISSUE THREAD

**Issue by skymyj** [techannihilation/TA#22]
Actually, Need by priority :
1 - Add Engineerer for vehicle : http://units.tauniverse.com/?p=u&v=3661
2 - Enginereer for air : http://units.tauniverse.com/?p=u&v=528
3 - Add a second Geothermal like Behemoth. I'm thinking about flammer tower :)

(taken from n3wm1nd issues)

**Comment by pcdummy** [comment]
T4 Nano!
And behe :)

**Comment by skymyj** [comment]
Updating post

**Comment by skymyj** [comment]
Need Enginereer Vehicle pls

**Comment by skymyj** [comment]
Need Sea Mines

**Comment by skymyj** [comment]
Updated post

**Comment by nixtux** [comment]
3 - Add a second Geothermal like Behemoth. I'm thinking about flammer tower :) , k i will make this unit after t3 ship lab

**Comment by skymyj** [comment]
We are in June and already Christmas.

**Comment by skymyj** [comment]
This geo need to be very armored.

**Comment by nixtux** [comment]
Sky can you please not delete other peoples comments.

Thanks Nixtux

**Comment by skymyj** [comment]
Old and New suggestion for TLL : 
- Geothermal with Fire weapon
- T3 Air Transport : http://units.tauniverse.com/?p=u&v=355

**Comment by Antarac** [comment]
Geo's are often in the middle of the base.
Won't a flamethrower damage also own buildings then?

**Comment by skymyj** [comment]
It's the same for all behemoth, armored mex. 
You can play it like a fortress

**Comment by Antarac** [comment]
Flame Thrower Behemoth might be quiet vulnerable alone but why not.
