### ISSUE TITLE
Need Script to choose good weapon for TLL Jump Kbot

### ISSUE THREAD

**Issue by skymyj** [techannihilation/TA#23]
For TLL Jump Bot.. Too hard to use them with emp button.
I suggest : 2 modes & select what mode you want between : canon fire or emp bomb.
Easier to select 2 kbot for example on emp fire & rest with normal weapon.

The bomb are very OP when the explode. Too much "corlevlr_weapon" effect.

**Comment by nixtux** [comment]
That was the idea behind with bombs, emp like lever to clean way before you jump.

**Comment by skymyj** [comment]
I propose to delete button. They could shot bomb all 10-15s
Immunize them to EMP.
