### ISSUE TITLE
What do with tlldcsta.lua

### ISSUE THREAD

**Issue by nixtux** [techannihilation/TA#233]
So this unit is un-needed in its current roll and broken, first idea is rework as floating missing launcher
Feedback please

**Comment by skymyj** [comment]
Well. We could transform it into pulse rocket at 900 range for T1
Static artillery could be nice indeed

**Comment by nixtux** [comment]
K I will add weapon + fix script

**Comment by nixtux** [comment]
fixed script + added new weapon , but needs balancing https://github.com/techannihilation/TA/commit/6d152909a657b3d6bfbeb143eb650eaff5cc924a
