### ISSUE TITLE
Special damage for commander

### ISSUE THREAD

**Issue by skymyj** [techannihilation/TA#241]
With Silver, we have found these rules : 
- everything plasma over 1300 - set special damage ~66% vs commanders
- everything laser / lighting / missile over 900 - set special damage ~66%
- Fast units (velocity > 2) with laser or lighting or missile - set special damage to 50%

What do you think ?

**Comment by Antarac** [comment]
Means ~66% it's minus 66% or plus 66%?

How are people supposed to know which units
deal higher or lower damage to commanders?

Whats the reason behind this change?

**Comment by skymyj** [comment]
It's not a change. 
Some units have these rules and other not. 
So it's just a balance to have all units with same rules. It's ~66%

How players know ? We should create a Wiki with basic rules. 
For example, the autodestroy time for each type of unit....
