### ISSUE TITLE
Energy Make and Storage for all units with energy weapons.

### ISSUE THREAD

**Issue by ghost** [techannihilation/TA#248]
EnergyMake = 15% of EnergyPerShot
EnergyStorage = EnergyPerShot * 1.(3)

**Comment by nixtux** [comment]
imo for now all laser weapons??, they seem to have been the worst effected

**Comment by nixtux** [comment]
diff from before skymyj removed values https://www.dropbox.com/s/586i3sxp7q03cqh/diff%20%28copy%29.txt?dl=0

it looks like it only effects t2 units or greater

**Comment by skymyj** [comment]
Hello. 
Nixtux, you said last week, you would for each unit makes energy. If economy destroyed, it will be more easy to reconstruct things.

2 years ago, I began to deleted the energy production and you said me to stop that.

And now, I see this commit. I don't understand.

For me, the good algorythm will be : if energymake = energyuse => delete energyuse
And after, we could adjust the OP unit like T2.5 Arm invisible Kbot.

**Comment by nixtux** [comment]
Proposed Values for units with beam laser weapons

armpraet,  EnergyMake = , 150,  Energystorage = , 1300
armmanni,  EnergyMake = , 150,  Energystorage = , 1300
corsumo1,  EnergyMake = , 11,  Energystorage = , 97
monkeylord,  EnergyMake = , 300,  Energystorage = , 2600
armorco,  EnergyMake = , 150,  Energystorage = , 1300
cortyrnt,  EnergyMake = , 375,  Energystorage = , 3250
corbats,  EnergyMake = , 11,  Energystorage = , 97
corhover3g,  EnergyMake = , 11,  Energystorage = , 97
armkrmi,  EnergyMake = , 11,  Energystorage = , 97
coradon,  EnergyMake = , 150,  Energystorage = , 1300
cormddm,  EnergyMake = , 150,  Energystorage = , 1300
hyperion,  EnergyMake = , 225,  Energystorage = , 1949
fatshrew,  EnergyMake = , 9,  Energystorage = , 78
tllboat2,  EnergyMake = , 3,  Energystorage = , 26
tllbats2,  EnergyMake = , 18,  Energystorage = , 162
corerex,  EnergyMake = , 15,  Energystorage = , 130
speeder,  EnergyMake = , 2,  Energystorage = , 20
gorg,  EnergyMake = , 1,  Energystorage = , 13
devastator,  EnergyMake = , 150,  Energystorage = , 1300
corsumo,  EnergyMake = , 11,  Energystorage = , 97
armgor,  EnergyMake = , 165,  Energystorage = , 1430
corblackhy,  EnergyMake = , 11,  Energystorage = , 97
armcrus,  EnergyMake = , 1,  Energystorage = , 13
arm_furie,  EnergyMake = , 315,  Energystorage = , 2730
corkrog,  EnergyMake = , 225,  Energystorage = , 1949
armjag,  EnergyMake = , 150,  Energystorage = , 1300
corcrus,  EnergyMake = , 1,  Energystorage = , 13
armbanth,  EnergyMake = , 150,  Energystorage = , 1300
corasship,  EnergyMake = , 3,  Energystorage = , 26
corcrab,  EnergyMake = , 1,  Energystorage = , 13

**Comment by ksilversurfer** [comment]
yes yes yes :D

**Comment by Antarac** [comment]
Means it create more storage or less?

**Comment by ksilversurfer** [comment]
a bit more

**Comment by Antarac** [comment]
I just tested a few and some get less, some more.
I dont understand it enough to vote for it.
And also storage theme was so complicated lately
that i don't know why now again other storage changes =)
