### ISSUE TITLE
Icons to fix

### ISSUE THREAD

**Issue by ksilversurfer** [techannihilation/TA#249]
corck, armck - should be open, now are identical as dt
arm decoy fusion  - identical as fusion

**Comment by nixtux** [comment]
Its armclaw and cormaw btw :D

**Comment by nixtux** [comment]
All fixed btw, will be in next release

**Comment by nixtux** [comment]
Opps looks like I didn't push commit, will reopen

**Comment by ksilversurfer** [comment]
:D
