### ISSUE TITLE
Units to delete

### ISSUE THREAD

**Issue by skymyj** [techannihilation/TA#25]
Hey,
I think, time is coming to delete few units never used or with no interest for the game :

- Copter : Job already taken by other gunship planes units
- T1.5 Air transport : they counter T2 transports. For example, they can transport a Sumo :X
- T3 Air transport : Useless except If and only if they can transport massive until > 10K HP & < 100K HP. (I know that we are blocked by the engine or the system in term of weight. Mass unit have to be proportionnal to the HP or maxdamage.)

Please address this issue
Thanks

**Comment by ksilversurfer** [comment]
my votes:
delete copter
delete t1.5 trans
keep t3 trans

**Comment by ZweisteinT** [comment]
I used t3 transporter as cannon fodder :) They have high HP so send them into the flak line right before the krows or bomber can slip through :D Although that might not be the intended purpose...
A few years ago it was common to transport krogoths into enemy lines in order to bring the huge krogoth explosion in to the enemy def line and kill it by that...
So... currently t3 transporter cant transport t3?

**Comment by skymyj** [comment]
Yeah ! I like ths strategy. Good working too, with T2 Air Trans Core and better with TLL (7k HP :) )
Actually, they can't transport Krogoth, or bantha.

**Comment by nixtux** [comment]
They CAN transport bantha just not krog

**Comment by nixtux** [comment]
Also lifting a krogoth size unit would look unrealistic

**Comment by nixtux** [comment]
Also does a t2 trans lift every t2 unit I think not

**Comment by ZweisteinT** [comment]
I never used copters yet. But there are multiple copters. In my optinion i like to have so much variety in TA :D Also turtles and hovercrafts :) I heart people saying copters are too weak. So i will take a look into them in one of the next games :)

**Comment by skymyj** [comment]
Actually, the copter lab doesn't help them. 15KE when you saw hover or spider at 2Ke....

**Comment by skymyj** [comment]
But I didn't balance that thing, cause it's a lost cause for me :)

**Comment by nixtux** [comment]
But I didn't balance that thing, cause it's a lost cause for me :) -- is that the correct attitude to have when i comes to balancing :(

**Comment by skymyj** [comment]
Sure it's not the correct attitude. Sorry.
But I just see this unbalance and did't have time to change it. Was with rocket balance.

**Comment by Antarac** [comment]
Its kinda also a feature to have a factory that is not used that much as opposit
to stuff everybody builds. A great car looks even better next to a shitty one.

Are they to weak then if nobody uses it?

Choppers are usually the backbone of military transport and they are the only aircraft that cant crash if the pilot is good. Everybody recognizes a helicopter and looks in the sky when a copter is close.

I use sometimes choppers and almost never turtles for example.
Not all players play the same way.

Ten of the most expensive copters (~30000metal) stun big T3 units,
kill it, and some even survive the explosion.

I like the balance. They are slow and die fast but they do a lot damage.
Great to have some choppers in the base, far from enemy aa
cause they kill incoming ground units really fast before they reach the inside of the base.

All the work for it is done already and TA is to me so great cause of the wide variety of units.

**Comment by Antarac** [comment]
Make Choppers more interesting for the players?

Roping helicopter                Quickly drops units without landing.

Transport helicopter            Keeps many small units inside like ground and sea transporters
				            instead lifting single units like the transport planes from airport.

Radar jammer helicopter     Could make helicopters more attractive for sneak attacks.

Sniper helicopter                 It can stand still in the air and sniper robots.

Stealth helicopter                If it behaves similar like with ground units only difference
                                            is that they cant get stopped by water and cliffs.

AA helicopter                      Helicopter doesnt need to fly in circles like planes.

**Comment by ksilversurfer** [comment]
I like it, however to balance **Roping helicopter** in case he drops units from air is not easy task.
I think it should be able only to drop "light" units: Ak, peewee, flea, weasel... and maybe some light t2 units: zipper, pyro, radar units, jammer units, anti air units.

**Transport helicopter - ** not a big deal with him, but should have some high HP to be usefull.
Transport maaaany small/weak units.

**Radar jammer helicopter** - cool actually and kinda safe idea.

**Gauss sniper helicopter** - ohhh this one nice but... can be hard to balance !!
- should be be able to fire only from standing position to be balanced
- can be stealthy, but not cloakable - cloakable sniper in air can be too OP

**Stealth helicopter** - maybe change name to "Invisible Cloakable Radar Helicopter" ?
- it is cloakable but not stealthy
- radar should have short range (60% of t1 radar?)

**Cobalt aa helicopter** - nice one

Amazing ideas though !


 




 Very creative ideas though !
