### ISSUE TITLE
aspdbunk still relevant?

### ISSUE THREAD

**Issue by Bla1** [techannihilation/TA#252]
aspdbunk (Spider Bunker) isn't built by the arm construction spider, which I think it should be.

**Comment by ksilversurfer** [comment]
I vote to add it back, it has 2 weapons iirc
maybe change one weapon to paralyze?

**Comment by ksilversurfer** [comment]
looks like we can close it, Bla1 wasnt online since that time

**Comment by ksilversurfer** [comment]
and this weapon is not important
