### ISSUE TITLE
Categorys

### ISSUE THREAD

**Issue by nixtux** [techannihilation/TA#255]
We need a new categories, SURFACE, will fix many units targeting underwater units, example gunships with try and target unwater mex/MM
Also will fix https://github.com/n3wm1nd/TA/issues/749

**Comment by skymyj** [comment]
we need a Hover Class Too. 
Will Help for balancing T1.5 Ship anti swarm hover and other ships.

**Comment by nixtux** [comment]
Just to make sure you want a category or an armor class?

**Comment by skymyj** [comment]
Armor class please.

**Comment by skymyj** [comment]
I think hover category already exists !?
