### ISSUE TITLE
Energy and Metal Storage at Start

### ISSUE THREAD

**Issue by skymyj** [techannihilation/TA#256]
Actually widget giving extra storage is bad implemented.
When we begin a party, we start with 2K M & 2K E Storage at start. (commander fixed at 1K)

Is it possible to fix the widget, to have:
- +0 M&E Storage if we start at <=1000 resources
- +X M&E Storage if we start at 1000 + X resources

Thanks

**Comment by nixtux** [comment]
First it not done by a widget, second can I have a short explanation for your reasoning behind this change

**Comment by skymyj** [comment]
It just to develop the storage management. 
It will give more weight for storage structures.

If I kill a Com, actually, not need to make metal storage to all reclaim for example

**Comment by nixtux** [comment]
Just set stroage mode to commander then not team? Please check https://github.com/techannihilation/TA/blob/master/modoptions.lua#L211

**Comment by skymyj** [comment]
Isn't possible to set as default ?

**Comment by nixtux** [comment]
Nope, imo we need to leave default options as they are, atm all players are aware which settings are default, changing this will just upset players, which I don't want. Closing issue as there is a mod option available.
