### ISSUE TITLE
Labs Autofeed Feature request

### ISSUE THREAD

**Issue by ghost** [techannihilation/TA#262]
Request for a feature to set the desired number of one specific unit present on battlefield. When a unit is destroyed, lab automatically produces one new to keep the number set for that unit.

Example: I want 50 pewee on map. If 1 unit is killed, lab automatically must build 1 new pewee to replace the lost one and restore the total of 50 pewees present on battlefield.

Pros: overall gameplay improvement (no M and E waste, more similarity with real war)
Cons: none

by Casanova  :)

**Comment by ksilversurfer** [comment]
Thank you a lot for posting request of that !
We appreciate any help/suggestions/info from you Casanova mate : )

Keep going 👍 on and have fun on KING/BoS host 🗡  :D

**Comment by Antarac** [comment]
Sounds more like that would be a job for a widget, not for another commands for factorys.
