### ISSUE TITLE
T1.5 cannons

### ISSUE THREAD

**Issue by nixtux** [techannihilation/TA#273]
Please vote for adding thoses units back

**Comment by ksilversurfer** [comment]
I vote yes for adding those cannons, they were more often used than "Guardian - Medium Range Plasma Cannon".
Also medium plasma shields were more usefull when we had T1.5 Cannons.
Now medium "mini" shields are builded by players very rare.
Another cool thing about T1.5 Cannons was that they had stronger impulse boost on low trajectory (almost like guardian on high trajectory) - physics of exploding units was awesome !
