### ISSUE TITLE
cbuilderlvl2/abuilderlvl2 

### ISSUE THREAD

**Issue by nixtux** [techannihilation/TA#275]
description = "Makes Adv T1 Combat Units",  so why the hell can it build a advanced t2.5 tech ie corsumo1 corgol1 and to top it off a corkrog its bloody t3 tech. What to do with this mess

**Comment by skymyj** [comment]
Just Fix description : description = "Makes Adv Combat Units"

**Comment by ksilversurfer** [comment]
> What to do with this mess

imho **T1 Combat Engineer** should be able to build T1 and T1.5 and some extra mini adv units like mini catapult and mini vanguard, ahh and add new T1.5 Cannons to them.

Any T2 and T2.5 units move to **T2 Combat Engineer** (Freaker, Fark, Consul...)

and i vote also for removing Krogoth and Orcone from Engineers... its T3 units....

**Comment by skymyj** [comment]
I m fine to delete t3.5 from this unit

**Comment by nixtux** [comment]
This should be main into counterpart of T1 combatEngineer https://github.com/techannihilation/TA/issues/278

**Comment by Antarac** [comment]
I have notes about changing the name only
since i see never people complain about the unit
or what it builds.
