### ISSUE TITLE
<J5> tll combat aircon description is wrong "makes combat units" but it makes eco units

### ISSUE THREAD

**Issue by nixtux** [techannihilation/TA#278]

**Comment by nixtux** [comment]
We need to make this unit produce the same type of units as builderlvl2, As ive added 2 new units to tll t1/5 tech level, mini shield + long rapid fire gatling (low dps) both should be in this units buildmenu

**Comment by skymyj** [comment]
Nix, This change will kill the battle commander. 
Player could choose the Battle Com, and make this unit to have adv Mex. 
Now, just one solution : go to Eco Commander if you want be competitive.

Please, revert this commit. 
We just need a new engineerer Air TLL :  #22 : http://units.tauniverse.com/?p=u&v=528

**Comment by nixtux** [comment]
Nice find looks good for tll

**Comment by skymyj** [comment]
http://units.tauniverse.com/?p=u&v=351
Model for veh engi tll

**Comment by nixtux** [comment]
reverted with https://github.com/techannihilation/TA/commit/afe5c695c830018b9d011732b655f33073ac6c0e

and added in https://github.com/techannihilation/TA/commit/be68823b872cc4e5e222c4c7757e03b59f7bd4fa
