### ISSUE TITLE
T3 Mex Shields

### ISSUE THREAD

**Issue by nixtux** [techannihilation/TA#279]
With https://www.dropbox.com/s/0dg1a7zfnoxciw2/screen00045.jpg?dl=0
Without https://www.dropbox.com/s/s06iw2lrlhnqviv/screen00046.jpg?dl=0

Over 100 fps drop with only 50 shields on screeb

So any issue if i remove shields from t3 mex's

**Comment by ksilversurfer** [comment]
i have no issue with that - its weird that mexes have shield, i not liked that since forever

**Comment by skymyj** [comment]
Hello. For me it's good to delete them. 
Moreover, I never understood how they work.
Is the shield take all damage (missile, plasma, laser...) ? How much ? 

 Same for the FusAirstrike Resistant Fusion Reactor.

**Comment by ksilversurfer** [comment]
Well airstrike fusions shields are ok, shield of that fusion  needs energy to load, and protect quite well for some sime.
Then reaload back and take energy again until full.
So i vote to keep shields for airstrike fusions

**Comment by skymyj** [comment]
I said same for fusaistrike to understand how they work. Sorry

**Comment by nixtux** [comment]
Ok i will remove shields

**Comment by nixtux** [comment]
https://github.com/techannihilation/TA/commit/d2a2b0f3496b31503b8985f876af73fd05798ed4
