### ISSUE TITLE
Unit Energy Production Vote

### ISSUE THREAD

**Issue by Antarac** [techannihilation/TA#280]
There seem to be many discussions
about Armed Units, producing energy.

Discussions seem stuck so i vote to
change no more about it especially
not lesser energy production.

Reasons are as followed:
Every vehicle produce its own energy in real life.
Cars, Ships, Planes, Trucks and even your bicycle.
The more similar a game is to real life the more
easy its to accept and understand for Players.
Your car got radio and light and no laser to
blow up shit, but still it works that way.

If you loose your whole base and you can start
again behind your team mates its really a good
feature to get some extra energy.
We want to keep people playing for good balance,
fun and more and not to resign cause its hard
to build a base again.

If some things badly need to get changed try again
after a few weeks or month with fresh ideas.

Just in case no agreement can be found just leave it
as it is since it did not seem to hurt so far.

**Comment by nixtux** [comment]
Duplicate too https://github.com/techannihilation/TA/issues/248
