### ISSUE TITLE
Anti Nuke Rocket fails

### ISSUE THREAD

**Issue by Antarac** [techannihilation/TA#281]
Anti Nuke does not fly high enough after it got launched,
and it crashes into hills sometimes,
when it flys towards enemys nuke.

Happens only if you build Anti Nuke close to the Hill
but players treat it like a bug and get angry.

Make vertical start last longer and make rocket
a bit faster to balance this?

**Comment by nixtux** [comment]
So does this happen on all maps or just metalwall, imo the real issue is the wall are too high on that map. You never know that could have been why there so high.

**Comment by Antarac** [comment]
Here is a example that shows what i mean.
https://www.sendspace.com/file/7zevly

You can repeat the test with:
/cheat
/give 3 corsilo 1
/give 4 armamd 2

**Comment by nixtux** [comment]
iIm going to close issue, i wont change setting just for one map
