### ISSUE TITLE
Slow Command Buttons

### ISSUE THREAD

**Issue by Antarac** [techannihilation/TA#282]
Ingame command buttons that contain more options react really slow.
Like when you switch from "roam" to "maneuver" to "hold pos".
Is there a reason for it or can we just make that work faster please?
Cause if you need to change it quickly while fight it's not so cool.

**Comment by skymyj** [comment]
I agree. 
Before, Open/Close (O) and Jump (J) had a key. Is it possible them come back ? 
(I know for jump it's shift + J => but not really adapted)

Thanks

**Comment by nixtux** [comment]
J is used for canceling target on the move, im not going to replace a key everyone is already well versed in using.

**Comment by Antarac** [comment]
This Issue is about making existing buttons work faster,
not changing key shortcuts.

If no other people experience such problems i just close the issue.
