### ISSUE TITLE
small Shield balance

### ISSUE THREAD

**Issue by skymyj** [techannihilation/TA#284]
Ratio M/E normal vs small is 4 x more Energy for Normal Shield.
we should increase a little energycost for small shield and for mobile Core Shield.
8~9KE => 16KE

**Comment by ksilversurfer** [comment]
it's already been discussed and tested many times with Zweistein here: #277

**Comment by ksilversurfer** [comment]
so i vote n

**Comment by Antarac** [comment]
Core T1.5 Shield Building is so expensive
on metal that i gave up to build it.

So i vote no for making it even more expensive,
and if its only energy cost.

**Comment by skymyj** [comment]
Ok. Maybe, we could decrease metal and keep energy cost.
