### ISSUE TITLE
Guidelines For Pull Request

### ISSUE THREAD

**Issue by nixtux** [techannihilation/TA#294]
New guildlines for PR.

OK so from now on all balance PR must be discussed about in a bug report before the PR is made.
All pull request for balance changes must come with a valid description and reason behind the change or they will be ignored/closed.

This is to help everyone efficiency answer and less time wasted for all of us.

Please add any other comments as you see fit or any other guildlines you see fit and we can discuss this here.

P.S. all current PR need a valid description or i will be ignoring them until this is done.

P. S. Any PR for new units needs to have image of new model, so we can agree if it up to the standard, units/scripts need to be fully working and compatible with the techa.  

Regards Nixtux

**Comment by Antarac** [comment]
You mean with "bug report" to discuss it first as "Issue" and make after decision a "pull request"?

**Comment by nixtux** [comment]
Yeah i mean for balance issue please discuss in a issue before you make a PR.
