### ISSUE TITLE
Proposition for new T3/T3.5/T4 stuff

### ISSUE THREAD

**Issue by skymyj** [techannihilation/TA#296]
Winter is coming with new stuffs.
I thought for days. I think the best solution is that : 

![capture](https://user-images.githubusercontent.com/2990630/27132643-e6605f38-510f-11e7-85e9-fa71c3b284c7.JPG)
![capture2](https://user-images.githubusercontent.com/2990630/27132644-e661fe74-510f-11e7-990d-eb026b67b178.JPG)

**Comment by Antarac** [comment]
Let me try to write down what i see there.

TLL:
T2 Construction Planes, Vehicles, Kbots, Ships and maybe
even Turtles, can build T3 and T4 Factory if you can afford it.
T4 Factory produce T4 Units and T3 Builder for T3/T4 Buildings.
T3 Factory doesn't have the T3 Builder anymore.

ARM / CORE:
T2 Construction Planes, Vehicles, Kbots, Ships and maybe
even Turtles, can build T3.5 Factory if you have T3 RC.
If you have T4 RC the T3.5 Factory produces also T4 Units.
RC morphed to T4 builds as usual the T3 Builder for T3/T4 buildings.

**Comment by nixtux** [comment]
I've created 2 new units so for tll t3 mex, and tllbuilderlvl3, mex is already ingame

**Comment by nixtux** [comment]
So my idea for tll buildoption are tllhtbc > tll t4 Ship lab (this is what i'm going to make next) > tllbuilderlvl3 (done) > New units (lab + nano (done) + mex (done) etc)
