### ISSUE TITLE
Hero Explosions

### ISSUE THREAD

**Issue by Antarac** [techannihilation/TA#297]
Most Heros just need to move deep into enemys base and
the giant explosion leads to extinction of the whole base usually.
It doesn't really matter how much firepower they have.

I would suggest to make a few small explosions, and then
a last one that is a bit bigger, but ofc not as big as it is now.

With some random variables for time, explosion size and amount
combined with limits for it would make it look not same all time.
So for example between 1 and 5 seconds time,
2-7 small explosions and anyway the end explosion.

It's more realistic and would look better to have
several small explosions and a final detonation.

That comes closer to reality that first blow up some ammunition
depots and fuel tanks of units before the whole thing blows up.

Most important thing is, that you need a few
Heros to blow up, to wipe out a base completly.

Firepower of ships gets more important if
explosion doesn't kill the enemy straight away.

Game in T4 stage could last longer and chance is
higher other T4 units get used in the game.

**Comment by nixtux** [comment]
Btw can we add labels when we create new issue now, ive added labels for this already.

**Comment by Antarac** [comment]
I looked for it but dunno how or where.

**Comment by Antarac** [comment]
I followed the github help for it but i have no checkbox as it said.
Do i have no rights for it or am i just to stupid? =)

**Comment by Antarac** [comment]
I move my text to pull request #259 "Explosion balance" and close this issue.
