### ISSUE TITLE
T1.5 Wind Plant to big

### ISSUE THREAD

**Issue by Antarac** [techannihilation/TA#301]
I think the T1.5 Wind Plant should be a little bit smaller,
because it's really hard to defend that hughe Wind Parks.

It's cool that they are even stronger than Fusion, if Wind
is really strong, but you always run out of space kinda.

**Comment by nixtux** [comment]
That one fact is it achiles heal, imo it's a feature not an issue

**Comment by Antarac** [comment]
I see, reason enough to close this.
