### ISSUE TITLE
Remove "turn pages" for Command Buttons

### ISSUE THREAD

**Issue by Antarac** [techannihilation/TA#303]
How about to remove the Arrows for
turning the Pages?
 
Due to bigger screens and resolutions
since OTA it's lesser needed.
But even if you have a old pc like me
(1024x768 res), it wont matter.
Because units got maximum one line of
Commands on second page and these
would fit good in the space where the
"turn pages" arrows are placed.

Commander Jump for example is more
complicated due to turn pages.
To remove it, makes jump action lesser
complicated and also beginners could
do it more easy.
That would create more balance between
newbies and pro's and remove of jump,
like asked in #232, might be not necessary
anymore.

![vorschlag](https://user-images.githubusercontent.com/24976973/27259306-e1047c1a-540f-11e7-9476-aea3095ee39b.png)

**Comment by skymyj** [comment]
We should delete the Move button.

**Comment by Antarac** [comment]
You don't use it but you cannot expect that from other people.
There are reasons why you might need it even if it's not often.
It's about "turn pages", not delete Buttons.

**Comment by nixtux** [comment]
Yeah as I've said before I'm not removing the move button

**Comment by nixtux** [comment]
@Antarac this idea won't work if more than one units is selected as there menus get merged, I will check code and see how possible it will be

**Comment by Antarac** [comment]
True, and to be able to see all unit and building commands
in one menu is a great feature!

How about showing 5x5 icons like above and only change
last row into arrows if it gets more than 25 icons?
Just a suggestion but maybe it's to much work.
