### ISSUE TITLE
static long range emp is op

### ISSUE THREAD

**Issue by nixtux** [techannihilation/TA#307]
Ive seen many players complain about these units being op in the last few weeks.

**Comment by skymyj** [comment]
Maybe the TLL has better tange than ARM. But ARM EMP is ok for me imho.

**Comment by nixtux** [comment]
are you thinking tacnukes ?? there is also arm big bertha

**Comment by skymyj** [comment]
Indeed. I think players talk about big bertha. 

They are powerful versus T1 and T2 units. 
I think there are powerful but it's ok imho.
