### ISSUE TITLE
Proposal for new T4 units

### ISSUE THREAD

**Issue by skymyj** [techannihilation/TA#308]
It's good to add new units, but we have to have new job or feature units.

I propose New T4 Units with a unique job

**Comment by skymyj** [comment]
https://www.forgeworld.co.uk/en-FR/KX139-Taunar-Supremacy-Armour-with-Heavy-Rail-Cannon-Array

Bomb launcher :

Bomb x 16 : Range 2000.
Missile x 24 : Range 1400
Primary weapon ; Range 800

**Comment by skymyj** [comment]
T4 Carrier Ship.
Job : Control and mastery Air 

![a46ae00c9b9b45e22e2607a94a4f81df](https://user-images.githubusercontent.com/2990630/27332026-742befb2-55c0-11e7-97f4-d66be181bcfe.png)

2 T3 Flak
4 laser AA
4 long range missile
Radar
6 air repair pod

**Comment by skymyj** [comment]
Version 1 of long range T4 Kbot. 

![capture](https://user-images.githubusercontent.com/2990630/27332515-6dad2ae6-55c2-11e7-96f7-d9c73c5bcdca.JPG)

Plasma x 3 : Range 2000.
Missile x 24 : Range 1250
Primary weapon ; Range 800

Source : https://www.forgeworld.co.uk/en-FR/Tau-KX139-Ta'unar-Supremacy-Armour

**Comment by frju365** [comment]
These units seem to be very fine and nice. :) 👍 +1

frju365
