### ISSUE TITLE
Adjust Mortor

### ISSUE THREAD

**Issue by skymyj** [techannihilation/TA#309]
I think, I saw a commit few days ago, with adding mortar.
First thing : their job ? Vs Plasma canon T1 and T2 ? 
I remember we had already deleted these units. Why readded them ?
Moreover : (definition on wiki, is high trajectory for indirect shoot) => so the name actually is totally wrong with actual job.

I'm for adding new units, but we should make fun and usefull units.
So I propose weapon at 1800-2000 Range : 
a mortar, that shooting high trajectory plasma for T2.5 Units. (ARM)
Same effect than T1.5 Arm Riot Tank. Sound Tank

![capture](https://user-images.githubusercontent.com/2990630/27333788-5fc8f856-55c7-11e7-8ea0-02ef73c1685b.JPG)
Source : http://halofanon.wikia.com/wiki/X7896_Energy_Mortar

We could imagine a New weapon, with high trajectory Bomb like JetPack for T2.5 (TLL)
16 projectiles each 30 sec.
![capture](https://user-images.githubusercontent.com/2990630/27333909-ca0a0fac-55c7-11e7-90dd-908d1495c476.JPG)

We could imagine a long missile for T2.5 (CORE)
![capture](https://user-images.githubusercontent.com/2990630/27333973-07d1ba7e-55c8-11e7-829b-6a73b1832443.JPG)

**Comment by nixtux** [comment]
you need to checkout tll counterpart to these tllarch

**Comment by skymyj** [comment]
I didn't see yet this unit. But it's good thing.
Counterpart can be T2 Tachyon, T2 plasma, Air........ 
Now, if you want to putthis unit for T1.5, I think, it costs too much. Imho, I prefer tech. After, when resources are better, player will make the T2 canon with better range imo

**Comment by nixtux** [comment]
The unit for tll is rapid fire gatling type weapon

**Comment by nixtux** [comment]
I don't think the tll model would fix for that role change to be honest.

**Comment by skymyj** [comment]
Set this unit at T2.5 and increase range at 1650. 
Will be the good counterpart against cortotal and arm missile launcher at 1700 range

**Comment by nixtux** [comment]
Next release there is already a new units for t2 which is a counter to missile / rockets, that roll is already full.

**Comment by nixtux** [comment]
For the next release I wanted to add units to nearly all tech levels, t2 is done, t3+ in the works, the roll for thoses is to fill the t1 void, I do like the weapon idea but with lower range and t1.5 tech level

**Comment by nixtux** [comment]
I've even made a model for tll t1.5 energy cannon https://www.dropbox.com/s/whdrddj8ad45y8f/Screenshot_2017-06-22_23-40-21.png?dl=0

**Comment by skymyj** [comment]
Hey Nix. Really nice model.

**Comment by skymyj** [comment]
So, TLL will have 2 new plasma weapon ? 
The gatling and this new model ?

**Comment by skymyj** [comment]
Imho, we should delete the arm version mortar (uggly) and add this  https://www.dropbox.com/s/whdrddj8ad45y8f/Screenshot_2017-06-22_23-40-21.png?dl=0. 
We could change ammunition with high trajectory arm sonic weapon.

**Comment by skymyj** [comment]
The tllarch should cost less if you want players use it at T1 or T1.5
So need to reduce range to at 1200.

**Comment by skymyj** [comment]
Idea for Core Mortar : http://units.tauniverse.com/?p=u&v=639

**Comment by nixtux** [comment]
Tll energy gun is now textured

**Comment by nixtux** [comment]
Its ingame https://github.com/techannihilation/TA/commit/7b4f71716df7a755079ae5f0603b6485996bdb88

**Comment by skymyj** [comment]
Nix. Is it possible to delete the Arm Mortar and remplace it by Gatling ? 
I think, we should have Gatling for Arm, mortar for core (model is correct) and mortor for TLL (new model)

**Comment by nixtux** [comment]
Nope

**Comment by nixtux** [comment]
Ok all mortors are now high trajectory energy cannon. They will need balancing

**Comment by skymyj** [comment]
Just tested. 
Not saw tllmortor in T1 cons. But with combat engeneer. We need to put with T1 cons I think cause arm/core with T1 cons (even if RC needed).

For projectile, i'm ok. But for explosion, we need take same effect than sonic tank with less damage.
Is it possible ? Thanks

**Comment by nixtux** [comment]
What do you mean by effect, as that explosion matches projectile visual. Or are you on about sonic area damage?

**Comment by skymyj** [comment]
mortar_cannon = {
                                areaofeffect = 235,
				avoidfeature = false,
				burnblow = true,
				corethickness = 0.5,
				craterareaofeffect = 352.5,
				craterboost = 0,
				cratermult = 0,
				edgeeffectiveness = 0.15,
				energypershot = 30,
				explosiongenerator = "custom:diesmallwhite",
				firestarter = 0,
				impulsefactor = 0,
				intensity = 1.5,
				name = "Energy Projector",
				range = 1520,
				reloadtime = 2.5,
				rgbcolor = "0.5 0.5 1.0",
				size = 10,
				soundhitdry = "xplomed4",
				soundhitwet = "splssml",
				soundhitwetvolume = 0.5,
				soundstart = "sonicwv1",
				stages = 20,
                                turret = true,
				weapontype = "Cannon",
				weaponvelocity = 550,
				damage = {
					commanders = 20,
					default = 40,
					subs = 5,
},
}

+ Effect Sonic with adjust (less damage but same range).

**Comment by skymyj** [comment]
mortar_cannon = { radius = 95, damage = 200, duration = 60, rangeFall = 0.25, timeFall = 0.8, allyScale = 0.5, teamScale = 0.25},

**Comment by skymyj** [comment]
To test. But I think we have a good balance.

**Comment by skymyj** [comment]
Nix, are you ok with this ? 
Need script ? or just to add on lua file is enough ?

**Comment by nixtux** [comment]
Is this issue still valid?

**Comment by skymyj** [comment]
Yes. We need to add explosion like sound tank arm
