### ISSUE TITLE
Tll adv wind trap

### ISSUE THREAD

**Issue by nixtux** [techannihilation/TA#310]
We have the unit it's just not in any buildmenu, this needs to be added so tll eco commander has the same units as arm/core counterparts.

**Comment by skymyj** [comment]
No need imho. 
They already have solar wind.

**Comment by Antarac** [comment]
TLL is so different to other factions, i dunno what fits.

**Comment by ksilversurfer** [comment]
I like the idea of adv wind trap.

> No need imho.
> They already have solar wind.

I dont agree.

Tll adv solar wind is a counterpart of adv solar (in arm/core).
So Tll adv wind trap is ok, becouse it will be a counterpart of t1.5 adv wind (arm/core)

**Comment by skymyj** [comment]
I'm ok with you Silver.

**Comment by Antarac** [comment]
In case i would need to vote i would tend
also more to keep advanced wind solar.

If there are models already they could be
used for higher wind tech level so making
them wasn't lost time?
Increase it's size and use it for T3 wind then
since the fusion is so lonley in the build list?

**Comment by nixtux** [comment]
Fixed closing issue
