### ISSUE TITLE
TLL : Engineerer Vehicle

### ISSUE THREAD

**Issue by skymyj** [techannihilation/TA#315]
Nix added new T3 construction ship.

So, we will add the T3 construction vehicle (CV) in T2 lab. 

2 otions are possible : 
- T2 CV didn't change and the T3 CV becomes a fat engineerer with large radius and many HP. (low speed). (same buildmenu than other TLL Engineerer)
- T3 becomes T2 CV and T2 becomes a classical engineerer.

What did you prefer ? 

I vote option 1

**Comment by ksilversurfer** [comment]
i think that option 1 is better
