### ISSUE TITLE
Anti T3/T4 weapon

### ISSUE THREAD

**Issue by skymyj** [techannihilation/TA#319]
All T2 can construct them with unlocking by T3 RC or Lab for TLL.
These weapon are final defense vs bigger units.

I propose to move them on T3 cons.

On party, they cost >30K metal. I think a player has most interest to make them after develop T4 eco. 
And it's more logic to have these weapon after in life game.

**Comment by nixtux** [comment]
Nope once there in t3 imo it's too late, you need them before t3

**Comment by skymyj** [comment]
These weapon was totally unbalanced. 
We had increase cost x 2. 
So, it's like Gatling with T1. You can't invest 34K metal to make def quickly.
You will make them after have good Eco. 
A player could invest 35K at T2 just to try to destroy ennemy base with lol canon for example. Here, it's just def.
