### ISSUE TITLE
Sound from weapon mookeylord

### ISSUE THREAD

**Issue by skymyj** [techannihilation/TA#320]
Is it possible to have a new sound. 

My ears can't anymore :)

**Comment by Antarac** [comment]
It's not bad, but it's loud, in my opinion.

**Comment by Antarac** [comment]
Monkeylord is and also weapon looks dangerous so
his hard,  loud sound fits perfectly somehow.

But i must admit that the Laserbeam is permanently
and the sound would fit more for single shots i think.
