### ISSUE TITLE
New T1 Combat TLL job

### ISSUE THREAD

**Issue by skymyj** [techannihilation/TA#323]
Actually this unit it's a little useless. Except mini shield, does't give many thing instead Arm/Core. 
Cause, no T1.5 and No morph for Tll.

I propose to add 1 new unit. I don't know wich again. 
- Maybe 1 or 2 T2 unit with unlocking with T2 lab
- Helepolis with unlock with T2 Lab.

**Comment by nixtux** [comment]
There is upg tll Web, well there is but you want to remove it why?

**Comment by skymyj** [comment]
No I dont want to delete it. 
We should add an adv hlt too

**Comment by Antarac** [comment]
Adding more Defense like HLT sounds good.

**Comment by skymyj** [comment]
Nix made new adv hlt ;)

**Comment by Antarac** [comment]
Cool, even better =)

**Comment by nixtux** [comment]
Tll very heavy laser tower https://www.dropbox.com/s/wezc82cuj94m5ki/Screenshot_2017-06-26_03-07-22.png?dl=0
