### ISSUE TITLE
Add morphing for TLL units

### ISSUE THREAD

**Issue by skymyj** [techannihilation/TA#324]
Tll didn't have X.5 unit. But they should morph like Arm / Core.
There were already some structures (HLT, Plasma, AA turret)

I propose : 
Tank : 
- Artillery T1 => T2 =>> T3
- Medium Plasma T1 => Heavy T2
- Lighting T2 => Ligthing T3
- Rocket T2 => Rocket T3

Kbot :
- Plasma T1 => Plasma T2 => Artillery (heavyimpact) T3
- Bind lighting T2 => Riot T3
- Rocket T1 => Amphibious Rocket T2

**Comment by ksilversurfer** [comment]
Yes i agree that all factions should be able to have morph ability.

**Comment by nixtux** [comment]
Fixed
