### ISSUE TITLE
Invert Faction with  T3 armsiege and Command vehicle

### ISSUE THREAD

**Issue by skymyj** [techannihilation/TA#325]
Many years, I'm said, that command vehicle is an arm faction. 
Cause 2 turrets with plasma like millenium ship or Hero.

Is it possible to inverse faction with armsiege ? 
Balance will be the same cause it's 2 artillery vehicle at same range and stats (more HP for command vehicle but cost more too)

Armsiege looks like more to a Goliath with large Radius for weapon.

![armmcv](https://user-images.githubusercontent.com/2990630/27658845-b26bf960-5c51-11e7-85ae-0ecd8317a34d.png) ![armsiege](https://user-images.githubusercontent.com/2990630/27658846-b290413a-5c51-11e7-9950-188b161f0ec1.png)

**Comment by nixtux** [comment]
It's called armmcv in the first place, so yeah I'm up for fixing this discrepancy.
