### ISSUE TITLE
Lots of unused TLL xta content. 

### ISSUE THREAD

**Issue by Thorgram** [techannihilation/TA#329]
Alot of this comes from M1Garland. Alot of these files are still raw i have a few .bos .cobs but i know your an expert at that as well as making models into real 3d objects such as 3dos. As being alone I just don't have time to bring these all to life but a lot of these models work great as T3-T4. There are a good number of sea boats that work TLL since some models leave some to be desired. Please take a look I'll add some pictures in just a moment in another post.
Also there is another zipfile folder inside, just realized this now, just being sloppy.

https://www.dropbox.com/s/jwiggtvzdmuh1qe/tllxtarawfiles3dobjectsplzlook.zip?dl=0

**Comment by Thorgram** [comment]
Here is but just a few models, I can glady retexture any models properly put back together as a .3do if you like what you see, you just have to convert it properly from wings3d.
![tll2017electriccannonvtoltank](https://user-images.githubusercontent.com/15385508/27720583-ec4405aa-5d1f-11e7-9d28-d89c6b85fb62.jpg)
![tll2017heronew](https://user-images.githubusercontent.com/15385508/27720601-fee0164a-5d1f-11e7-8475-aa43123fbf99.jpg)
![tll2017mobilebigboy](https://user-images.githubusercontent.com/15385508/27720610-0f56927e-5d20-11e7-8c8d-60e8bfc400f8.jpg)
![tll2017onaboat](https://user-images.githubusercontent.com/15385508/27720617-21f4c838-5d20-11e7-8e16-648beaad63c8.jpg)
![tll2017supertitan](https://user-images.githubusercontent.com/15385508/27720626-2ef39b18-5d20-11e7-8f87-0ff85e5d2b29.jpg)
![tll20174leggedpewpew](https://user-images.githubusercontent.com/15385508/27720637-422a0ac8-5d20-11e7-8529-ff0ee384e5a9.jpg)

**Comment by Antarac** [comment]
Unit on 3rd picture looks good! Heavy T3.5/T4 Tank =)

**Comment by skymyj** [comment]
Wow :) 
All these units are very beautifuls. 
For sure, we had now T4 for TLL Kbot. 
The third picture is awesome with tank. 
Really thank you Thorgram

**Comment by skymyj** [comment]
On your dropbox, didn't find the third model (platform vehicle). 
Can you send again pls ?

**Comment by skymyj** [comment]
Can you share the 3DO model with T4 Tank (third picture)
![roaster_powaa](https://user-images.githubusercontent.com/2990630/34102080-1b15f3a8-e3e8-11e7-9cf5-91527f6bf3cd.PNG)

**Comment by skymyj** [comment]
Close it
