### ISSUE TITLE
Giant Stolen AK used by Thrifty Arm Players

### ISSUE THREAD

**Issue by Thorgram** [techannihilation/TA#330]
Ill keep this short and sweet. There is this advanced t2.5 ARM unit that is just a GIANT ATTACK KBOT AKA THE LEGENDARY ONE AND ONLY AK. Somehow It managed to change sides. I swear to Trump himself this thing has got to go, do you want me to make you another model, I just want it gone, that is all.
![giantarmcorestolentechnology](https://user-images.githubusercontent.com/15385508/27720981-fa61c700-5d22-11e7-86c1-1c9dcb7564af.jpg)

**Comment by skymyj** [comment]
Ah ah. Never seen was AK Bot :)
I'm for your idea !

**Comment by Antarac** [comment]
Ofc add it to core, don't throw it away if its a core unit.

**Comment by skymyj** [comment]
Hey Thorgasm ! 
can you change this unit with a Pewee ? 
Thanks !

**Comment by skymyj** [comment]
What do you think about this model ? 
![akmech](https://user-images.githubusercontent.com/2990630/34101836-565bcd26-e3e7-11e7-9a84-6b46f131b502.PNG)

**Comment by skymyj** [comment]
![capture](https://user-images.githubusercontent.com/2990630/34101886-86aad8d2-e3e7-11e7-82c1-81f31ffd29a6.PNG)
