### ISSUE TITLE
Issue for new units

### ISSUE THREAD

**Issue by skymyj** [techannihilation/TA#333]
Add second AA for colossus. We need 2 independant AA.
Increase size for Arm and TLL LAb.
Add Flammer for Fatshrew
Increase size of your new T4 Kbot. (the main blue plasma canon looks not nice).

**Comment by nixtux** [comment]
AA is already done
Flamer wont works, it will damage passenger making them pointless

**Comment by skymyj** [comment]
Well, and if you add angle ? Only shoot on front ?

**Comment by skymyj** [comment]
And there is a setting to no damage allies unit ? No ?

**Comment by skymyj** [comment]
I'd like add the same thing for command vehicle : 
Add second weapon script to have 2 independants plasma canon like millenium.
Thanks

**Comment by nixtux** [comment]
Once passages disembark they are given an attack command to the unit which attacked mother, which could be in any direction. So angle/front won't work. 
And what do you mean by does look not nice?? Screenshot please more info

**Comment by skymyj** [comment]
Ok. So I suggest to remplace flammer tower : 
- 1 giant catapult missiles * 30
- 1 giant catapult bomb * 30 (high trajectory, like jetpack TLL Kbot)

**Comment by skymyj** [comment]
![capture](https://user-images.githubusercontent.com/2990630/27821347-3ed15ec8-60a2-11e7-8b58-4cc3bbdf70fb.JPG)

**Comment by skymyj** [comment]
If collidefriendly = false for flammer. Could work ?

**Comment by nixtux** [comment]
Nope would look unrealistic, and catapult type missile would look strange as the weapon is a laser type turret.

**Comment by nixtux** [comment]
Need more info on this (the main blue plasma canon looks not nice)

**Comment by skymyj** [comment]
I think; it's just the reload is too high. 
We need big projectiles with low relead instead the lighting weapon has good relead.

**Comment by skymyj** [comment]
For Fatshrew, if we keep the laser weapon, we need a blue beam laser like doomsday/ Tachyon.
The 2 laser weapon can't shhot behind it. 160° on front
