### ISSUE TITLE
Range Anti Nuke system for TLL carrier

### ISSUE THREAD

**Issue by skymyj** [techannihilation/TA#347]
I think, its range is very low vs other mobile antinuke.

**Comment by nixtux** [comment]
Which units are you comparing?

**Comment by skymyj** [comment]
Between turtle and all carrier

**Comment by nixtux** [comment]
Why compare thoses, Tllturtle has increased range due to no upg version that's the real issue imo

**Comment by skymyj** [comment]
Tllturtle has increased range due to no upg version => we should think the same for carrier.
I close this issue cause : #346
