### ISSUE TITLE
Crawling Bomb Story

### ISSUE THREAD

**Issue by Antarac** [techannihilation/TA#352]
Due to a lot of discussions about crawling bombs i write here how the story started.
It was me attacking somebody on map red triangle with advanced crawling bombs.
Since they are amphibious the advanced crawling bombs came out of the water.
There was no chance to kill them before they are on the isle.
And on the Isle means they are already inside the base.
He was wiped out quickly and i understood that it made him upset cause no chance to defend it.
That time we played often red triangle and others did it as well.
That was leading to discussions about advanced crawling bombs.
Somehow the reason why discussion started got lost, and lots of changes are discussed.

Only reason i see that is against remove of amphibious ability is that he might missed the counter strategy like depthcharge. But i actually doubt it would have worked.

Cause there were no problems about advanced crawling bombs till that i would suppose to only discuss to remove the amphibious ability.

Other player suggest that it is to op that combat engineer freaker can build it and that you need no factory for it.
So we could discuss also to remove crawling bomb and advanced crawling bomb from freaker.

**Comment by ksilversurfer** [comment]
iirc in OTA crawling bombs were in T2 Kbot Lab
reference http://totalannihilation.wikia.com/wiki/Adv._Kbot_Lab_(CORE)
I like that idea

here freaker build them - i dont like that.

**Comment by skymyj** [comment]
In real world and in strategic games, army without expand will die. 
All units except TSAR have many counters. 
For crawler mines, subs or torpedo could kill them. And even, if they are too many crawling bombs, and some pass, the fact to concentrate all production resources is a mistake.
You just did well Antarac and find the good strategy to adopt. I hope your opponent will learn.

But I'm for delete the Adv Crawling bomb for Core enginereer.

**Comment by Antarac** [comment]
Good example why amphibious is op
for advanced crawling bomb and also
op being built without factory.
https://www.sendspace.com/file/uaws1d

I know there are some counter strategys but
as you can see in the replay it piss off people
so much that its worth to think about it!

**Comment by nixtux** [comment]
Is this issue still valid?

**Comment by Antarac** [comment]
I'd say yes.

**Comment by ksilversurfer** [comment]
its not valid
