### ISSUE TITLE
Unit Morph and Research Center

### ISSUE THREAD

**Issue by Antarac** [techannihilation/TA#354]
If i have a T1 unit it needs ofc enough XP to morph.
If i have T2 research center i still can only morph with enough XP.
How about to unlock the morphs into T1.5 or T2 if you have T2 Research Center?

**Comment by skymyj** [comment]
Well, actually, a unit can morph into X.5 without Research Center. 
Goal is to give bonus for battle games. I'm 100% for this system.

Now, I'm 100% for a new system we could add to the first. 
If you have the Construction Lab X, you can upgrade some units into T X-1 into TX.
Goal is to have update all your units in function of your Lab production.

Example : you have 10medium tank. After battle, 4 died, and you moprh 4 others into Armbull. After a time, you make T2 Lab. At this moment, you can morph the last 2 tank into armbull.

I think, we have to make diffrenciation between construction lab, research center and morphing with XP.

**Comment by Antarac** [comment]
How about this example:
You have 10 medium Tanks. After battle, 4 died, and you morph 4 others into Armbull. After a time, you make T2 RC. At this moment, you can morph the last 2 Tanks into Armbull.

or if needed i could live with this:
You have 10 medium Tanks. After battle, 4 died, and you morph 4 others into Armbull. After a time, you make T2 RC or T2 Lab. At this moment, you can morph the last 2 Tanks into Armbull.

Reasons:
You need RC to unlock Units in Labs, so it makes more sense to let RC also unlock the morphs.
That a Kbot lab unlocks Vehicle morphs sounds a bit strange.
Why should labs unlock stuff since it's meant for production?
It's a hidden feature you cannot know and it might cause irritation.

But i must also say that if labs unlock stuff it makes it possible to play partly without RC.
To avoid the explosion or save the metal for it or if you dont need Tx.5 units, etc.

**Comment by skymyj** [comment]
Why not. RC could unlock the XP ask.

**Comment by nixtux** [comment]
Too much work v output
