### ISSUE TITLE
Fusilage Sound

### ISSUE THREAD

**Issue by Antarac** [techannihilation/TA#355]
Fusilage tank should throw out a big bullet shell after shooting since the sound is like that.

**Comment by Antarac** [comment]
Commander should be able to build T2 Metal Extractor after
he is upgraded second time, since he is T2 then, isn't it?

**Comment by skymyj** [comment]
Will be so cool ! 
I think, we should rework some sounds for many units.

**Comment by Antarac** [comment]
This Issue is not about changing sounds!
Fusilage Tank sounds like a hughe sniper rifle.
So it needs to throw out a bullet shell,
to fit to the sound of course.

**Comment by skymyj** [comment]
Sorry. Didn't good translate :X 
I'm for too change projectiles into laser or other plasma model at very high speed.

**Comment by Antarac** [comment]
I don't want to change anything
about Fusilage Tank in this Issue.

I only want to add a empty bullet
shell that get thrown out of the
tank when he shoots.

If you wanna change it completly
i can close this Issue and you make
a new one about the changes you want.

But Fusilage Tank is cool so i don't
understand why you wanna change
it into laser or plasma.

I fear that Unit ingame which tells
me its good =)

**Comment by skymyj** [comment]
Ok for me. I really didn't understand.. 
Indeed, you are right with bullet shell.

**Comment by Antarac** [comment]
Ok, cool =)

**Comment by Antarac** [comment]
Can we close this?
