### ISSUE TITLE
Commander T2 Metal Extractor

### ISSUE THREAD

**Issue by Antarac** [techannihilation/TA#356]
Commander should be able to build T2 Metal Extractor after
he is upgraded second time, since he is T2 then, isn't it?

Wont be to op and replace T2 Construction Units i guess
since he cannot build all other T2 stuff like Anti Nuke etc.

The Second Commander Upgrade cost similar than a T2
Factory plus T2 Construction Unit which would fit also.

**Comment by skymyj** [comment]
I don't know if it's good or bad idea. The Assault commander is a group from Eco and Battle.
The high cost is because it's just a very powerfull unit protected by jump and shield. I think we can't see and compare his cost vs Lab + T2 cons.

**Comment by Antarac** [comment]
I understand what you mean but if you invest into
commander instead T2 Con you miss the shields,
anti nuke, and many other stuff you seriously need
to win.

It's only good if you wanna play a "commander only"
based game which usually leads anyway to losing.
I do that when i play against newbies to build only
with commander and morph it.
That limits me a lot and makes the game fair.
And i have fun with it since i love Commanders =)

To give Commander more abilities that don't make him
OP is good cause it makes him more attractive overall.
Gives it kinda more character.

**Comment by skymyj** [comment]
You can close it.
