### ISSUE TITLE
Commander Geo

### ISSUE THREAD

**Issue by Antarac** [techannihilation/TA#357]
Commander cannot build anymore Geo on higher level.
I miss that often if base blows up and i have Geo spots
but commander cannot build it anymore.

**Comment by skymyj** [comment]
Indeed, we could add for Star and Supreme commander. I vote yes.

**Comment by Antarac** [comment]
Let's set up an example:

Mini Geo for Start Commander and Battle Commander
Normal Geo for Eco Commander and Assault Commander
Moho Geo for Star Commander and Supreme Commander

If im right TLL got even atomic geo so that means
moho geo for Star Commander and atomic geo for
Supreme Commander.

Good like that?

**Comment by skymyj** [comment]
You can't destroy a technology tree. If assault have Normal Geo, Star should have too or bigger.

**Comment by Antarac** [comment]
But thats what i wrote.
So for Core:
Start Commander and Battle Commander have T0.5 geo.
Assault Commander and Eco Commander have T1 geo.
Star Commander have T2 geo.
Supreme Commander have also T2 geo, since there is no bigger one.

**Comment by skymyj** [comment]
You can close it.
