### ISSUE TITLE
Venom nerf

### ISSUE THREAD

**Issue by Antarac** [techannihilation/TA#359]
Smurfpro said a while ago:
"The 'Venom - heavy laser hovercraft'
is to strong and needs to be nerfed."

I must admit it's really strong so what
do you guys think?

**Comment by skymyj** [comment]
Hey. why not, but can you compare this unit with an other with stats ? 
We will have a better vision to knwo what nerf.
Thanks.

**Comment by Antarac** [comment]
Dunno which one to take to compare.
Here is the replay where smurf said it.
It starts at minute 35 with Venom.
https://www.sendspace.com/file/uaws1d

I post same video for crawling bomb issue,
cause it contains big example for that as well.
