### ISSUE TITLE
Show Behemoth range before morph

### ISSUE THREAD

**Issue by Antarac** [techannihilation/TA#360]
When i have a Geo and i hover with
mouse cursor over the morph button,
to morph it into a Behemoth, it would
be really useful if it shows the attack
radius of Behemoth.

**Comment by nixtux** [comment]
So far I've added morph stats widget, its like unit stats but it auto shows on mouse over morph button, showing stats of potential morph

**Comment by Antarac** [comment]
Ok cool, i gonna check it out!

**Comment by nixtux** [comment]
https://github.com/techannihilation/TA/commit/fc1f699926be3c1bd00fb3962dbfb72a4e2703ab

All morphed units now show weapon range on mouseover of buildicon
