### ISSUE TITLE
Start 0 remove

### ISSUE THREAD

**Issue by Antarac** [techannihilation/TA#361]
When game starts there is always written on map "Start 0", "Start 1", etc.
I always delete it at start cause it blocks the view a little bit.
In my eyes its useless so can we delete that?

**Comment by nixtux** [comment]
Just disable Start Point Adder widget
or i could make it auto remove marks after say 5 seconds ?

**Comment by Antarac** [comment]
Ah, thats a widget :-s Well, i gonna turn it off then.

Sometimes it is shown in my base, other time it's in ally base.
I don't know what makes this useful.
In my opinion you could delete it.

Since i don't understand it i can not really tell whats good,
but to remove it after few seconds sounds good somehow.
