### ISSUE TITLE
2718 VS 2700

### ISSUE THREAD

**Issue by Antarac** [techannihilation/TA#363]
Values like build time, Healthpoints and others,
are often uneven numbers like "2718" and get changed
a lot into even numbers like "2700".

People are used since OTA to this style and a change
has no obvious advance or at least i cannot see one.

People that started to work on this must have
had reasons as well, why they use only uneven numbers.
To change what they done back in days means
also lots of work.

If all scripts have even numbers it makes chance
higher that in one frame are shitloads of scripts
working and in next frame just a few.
But this doesn't count for numbers like HP ofc.

You wont start to build a robot out of 2000kg metal.
You would design the robot first and at the end you
will know you need 2011kg metal.

Ask yourself if it's more of a spleen, to change all
the numbers, instead a actual good change.

Uneven numbers are just more natural.
Players accept more easy things that are similar to real life.

**Comment by skymyj** [comment]
Like Queen, I have one vision : https://www.youtube.com/watch?v=-OGd4gplxQM
I think with high values, "unity" should be 5 and 0 only. 
We could imagine than Kg doesn't exist and be remplaced by a new weight system (multiple 5).
It's just more easier to read 27500 than 27507.

**Comment by Antarac** [comment]
It was not about Kg or Tons, it was just a
example, why numbers are not always straight.

It's like that since OTA.
You change something that
is like that since 20 years kinda.

If you read such numbers while gaming
it's more "unconscious" so it wont matter.
Brain filters such little things out mostly.
If there is cost 34619 i recognize only 34k.

**Comment by lll8D** [comment]
I totaly agree with Antarac. Simplifying numbers will give the feelign of a fake balance.

**Comment by ksilversurfer** [comment]
i agree too

**Comment by Antarac** [comment]
Agreed
