### ISSUE TITLE
Anti Tac Nuke

### ISSUE THREAD

**Issue by Antarac** [techannihilation/TA#364]
Whats the reasons why there is no Anti Tac Nuke yet?
People often moan about it.

<BrainFart> lame
<BrainFart> i have anti nuke
<BrainFart> but no anti tactical
<[KING]Antarac> there is no anti tac nuke in ta
<BrainFart> fuck that's lame
<[KING]Antarac> you need to destroy the enemys tac nuke to stop it

**Comment by nixtux** [comment]
see https://github.com/n3wm1nd/TA/issues/531, removed valid tactic imo

**Comment by Antarac** [comment]
Last half year i lost 2 players due to tac nuke.
Even more experienced players fall for it, not only newbies.
Seriously, i do not really build it anymore, cause it makes people upset so much.

It's like the moaning about energy storage,
but it is spread more over time,
so we don't recognize it that much.
