### ISSUE TITLE
Anti Air Rocket Intelligence and Framerate

### ISSUE THREAD

**Issue by Antarac** [techannihilation/TA#366]
If you have shitloads of aa,
that fires a lot rockets at once,
there are many rockets that miss
the target for some reason.

This is no problem but the rockets life really long!
It takes ages till they hit the ground and get deleted.
For slow Computers like mine it means, frames get
lower from one second to another.

A mix of the following ideas could
help that frames drop not that bad
and also improve the rockets a lot:

If rocket loose target set a random time from
like 1 - 10 seconds to make the rocket explode
to drop amount of rockets a little bit over time.

Make rockets fall faster towards ground so they
get deleted earlier.

Delete the smoke from a rocket when it goes
down to earth and its jet engine is already off.

Rockets could have proximity fuse to explode even
if it doesn't hit the plane directly but that cause maybe
even more lag cause more scripting.
This would make rockets look more intelligent and
decrease amount of rockets without target also.

Intelligent rockets that look for a new target like
a "fire and forget" rocket.
Maybe add that only to big rockets like the T2
long range AA defense.

**Comment by nixtux** [comment]
I need a list of which units this effetcs

**Comment by Antarac** [comment]
All static and mobile units that fire rapidly rockets.
If you say still valid i will try to make a list
