### ISSUE TITLE
Auto Mex Upgrade waypoint lines

### ISSUE THREAD

**Issue by Antarac** [techannihilation/TA#367]
If i tell my Commander to Upgrade all mex
in an area it doesn't show waypoint lines
where he gonna go first, second, third, etc.

**Comment by skymyj** [comment]
+1 like

**Comment by nixtux** [comment]
having a quick look at the gadget it only select one mex at a time to upgrade, so no way of getting list of waypoints sorry

**Comment by Antarac** [comment]
How about showing that single one?
Better than nothing.
