### ISSUE TITLE
Assault Commander T1.5 tidal

### ISSUE THREAD

**Issue by Antarac** [techannihilation/TA#368]
Assault Commander miss the T1.5 Tidal in build list.

**Comment by skymyj** [comment]
Assault com didn't have adv wind too. 
At this level, assault comannder makes fusion.
But we can add adv Tidal if you want. 

I vote B.

**Comment by Antarac** [comment]
You wrote last time that Assault Commander
bring together the stuff from Battle and Eco
Commander so it feels like it's missing.

If i loose good buildings in build list after
i upgrade commander it's no upgrade really.

**Comment by skymyj** [comment]
I'm ok with you. 
We should add adv tidal ad wind.

**Comment by skymyj** [comment]
You can close it. 
Assault com have T1 stuff now.
