### ISSUE TITLE
Laser Fence

### ISSUE THREAD

**Issue by Antarac** [techannihilation/TA#372]
Build at least 2, or even more Pillars,
that get connected with each other
to create a laser fence between them.

Pillars have a maximum radius to
get connected with other pillars.

You need to destroy the pillars
to turn the laser fence off.

Pillars need energy ofc to keep
the laser running all time.

Enemy Units can drive through the
laser fence but take lots of damage.

Enemy Units and own defense can
shoot trough the laser fence since
it is no solid material.

**Comment by skymyj** [comment]
I love this idea

**Comment by Antarac** [comment]
I got it from "Tiberian Sun".
![leserfence](https://user-images.githubusercontent.com/24976973/28239049-d07199a6-6962-11e7-8f41-e76f720af8c4.gif)

**Comment by Antarac** [comment]
I got it from C&C Tiberian Sun.
This is a picture from a mod,
but it's same thing.
![leserfence](https://user-images.githubusercontent.com/24976973/28239068-2e287c04-6963-11e7-99b6-804f34608bb7.gif)

**Comment by nixtux** [comment]
Too much work Involved
