### ISSUE TITLE
Robot Gate

### ISSUE THREAD

**Issue by Antarac** [techannihilation/TA#373]
A big gate that only open for allied units.
To block the way like with dragon teeth
but able to open it to get out.

![shumber-sliding-gates-4a](https://user-images.githubusercontent.com/24976973/28148447-1319d440-6787-11e7-88b3-1bac486a640d.jpg)

**Comment by skymyj** [comment]
I prefer laser fence

**Comment by Antarac** [comment]
Laser fence is separate and got nothing to do with this.
Laser fence can also switch laser off if ally drive trough.
So it's already a gate. This gate is mean't heavy armored.
I got the idea from C&C not AOE :-P

**Comment by nixtux** [comment]
i tryed gates before with sea, too many issues they wont be getting added

**Comment by Antarac** [comment]
I thought about a gate like this:
![gateanim](https://user-images.githubusercontent.com/24976973/28239417-0b0beea0-696c-11e7-991f-b68cede53c56.gif)
![gate](https://user-images.githubusercontent.com/24976973/28239419-1008e85e-696c-11e7-8a4d-dda15c8a441f.png)

If it move into ground, and collision get turned off i can hardly imagine problems
