### ISSUE TITLE
Robot Obelisk

### ISSUE THREAD

**Issue by Antarac** [techannihilation/TA#375]
A really big Obelisk made of metal.
Cost 1000000 metal and 1000000 energy and has 1000000 Health.
More of a gadget or status symbol.
Can be used to block a pass or to build insane walls in fun games.
A spark of a Robot Religion.

https://en.wikipedia.org/wiki/Obelisk

**Comment by skymyj** [comment]
Why not. but cheaper and for T4 cons.

**Comment by Antarac** [comment]
Of course for T4 but not cheaper.
It needs to be really hard to build this
otherwise it's not that cool to build it.

Status symbols are never cheap.
