### ISSUE TITLE
armorco

### ISSUE THREAD

**Issue by nixtux** [techannihilation/TA#381]
why is such a nice unit gone, its even on one of the load screens, this must come back.

**Comment by Antarac** [comment]
Like this one?
http://units.tauniverse.com/?p=u&v=1123

**Comment by nixtux** [comment]
Opps minor typo I mean this beast of a unit https://github.com/techannihilation/TA/wiki/armorco

**Comment by skymyj** [comment]
Didn't understand the post. 
You want to see more this unit ?

**Comment by nixtux** [comment]
I want to see it, looks like you removed it from build options long ago

**Comment by skymyj** [comment]
Armorco is actually played. I Didnt remove it. 
But fury is just more played.
A sollution could be to unlock this unit or to move fury into t4 unit.

**Comment by Antarac** [comment]
Yeah, people use it but not often.

**Comment by nixtux** [comment]
Ok darn look like my code for finding unbuildable units needs work, closing
