### ISSUE TITLE
Testing engine/game 

### ISSUE THREAD

**Issue by nixtux** [techannihilation/TA#384]
We need some test games with new engine and new game, all new units are buildable now so have some fun.

**Comment by skymyj** [comment]
Sure. We will test

**Comment by nixtux** [comment]
You can once there is a working host

**Comment by nixtux** [comment]
OK host really is working now

**Comment by skymyj** [comment]
Will test tomorrow. Now time to go bed. See you

**Comment by skymyj** [comment]
You should talk to silver to test on this server

**Comment by nixtux** [comment]
ok host is really working now
