### ISSUE TITLE
Add T1.5 Air for Core

### ISSUE THREAD

**Issue by skymyj** [techannihilation/TA#389]
I found this unit : http://units.tauniverse.com/?p=u&v=1476
It will be perfect for T1.5 unit.
![1476](https://user-images.githubusercontent.com/2990630/28319078-2745132c-6bcd-11e7-8655-323373a2472a.JPG)

**Comment by nixtux** [comment]
I have a better unit for core, this should be for tll

**Comment by skymyj** [comment]
Good :)

**Comment by nixtux** [comment]
From left to right, arm bomber, core cutlass, and tll gunship https://www.dropbox.com/s/vmxv00bwkwmgpt6/Screenshot_2017-08-12_12-10-44.png?dl=0

**Comment by nixtux** [comment]
Ok arm unit will be kamikaze drone, cutlass will be bladewing big brother, and tll not sue yet, feedback please

**Comment by skymyj** [comment]
Tll could be lighting gunship

**Comment by skymyj** [comment]
No tll t1.5. I suggest to move into t1 engineer battle. 
Description could be commander escort.

**Comment by nixtux** [comment]
Yeah sounds good, for blastwing it could be emp kamikaze unit or normal blast?

**Comment by skymyj** [comment]
Same stats than t1.5 arm

**Comment by skymyj** [comment]
For kamiaze, its t1.5 or t2?

**Comment by nixtux** [comment]
All t1. 5

**Comment by nixtux** [comment]
Lightning weapon on gunships has visual issues the units move to fast, so weapon origin looks off, I did try reducing beam time but that didn't really fix issue

**Comment by skymyj** [comment]
So green beam laser

**Comment by nixtux** [comment]
Closing xD
