### ISSUE TITLE
Add Fortress Air for TLL

### ISSUE THREAD

**Issue by skymyj** [techannihilation/TA#390]
Will be perfect : Remplace rocket by tesla or lighting.
![2958](https://user-images.githubusercontent.com/2990630/28319267-b178276e-6bcd-11e7-880f-74387837bec5.JPG)
http://units.tauniverse.com/?p=u&v=2958

**Comment by Antarac** [comment]
Looks quiet filigree, with that skinny wings,
for a flying fortress, but why not.
