### ISSUE TITLE
Shield for exoarm

### ISSUE THREAD

**Issue by skymyj** [techannihilation/TA#403]
This unit need to have same shield than Fatshrex (bigger than preatorian and monkey). 
Thanks

**Comment by nixtux** [comment]
You need to revert weapon changes to origins thay are way too expensive now and can't stay

**Comment by nixtux** [comment]
You have also removed a weapon, these are t4 units, they should have at least 5 weapons  or a special feature otherwise they will boring

**Comment by nixtux** [comment]
The special feature should never be when you start firing your fps drop

**Comment by nixtux** [comment]
shield added, and weapons reverted please re-balance damage now
