### ISSUE TITLE
New Adv ECO Commander for better balance

### ISSUE THREAD

**Issue by skymyj** [techannihilation/TA#409]
Often we hear that the commander is OP. 

The thing is 90%, players choose the ECO commander to develop quickly economy. 
Then, they could morph into Assault and this unit with jump, and shield can easely destroy many units.

My idea is to add a new commander to have a better balance. If a player chooses the Eco commander, then, he could morph into Adv Eco commander. With all T2 Ecoing structures. These stats will the same than ECO or Standard commander. Instead of battle commander, who could morph into assault commander. With low resources.

I think, we will have better balance for the commanders, and the choice between ECO or BATTLE will be more impact for the rest of the party.

![capture](https://user-images.githubusercontent.com/2990630/28516829-d27984c8-7062-11e7-8a8f-788d96a565b8.JPG)

**Comment by Antarac** [comment]
Sounds good so far.

**Comment by skymyj** [comment]
For good balance : 

T0 : No change
T1 (Eco) : No change
T3/T4 (Battle) : No change
Morph T1 into T Fus = 5K Metal and 100K Energy
Morph T3/4 into Assault Com = 6,5K Metal and 50K Energy (same ratio then T0 into T3/4)
T5 (Assault) = Decrease cost at 9250M and 77KE (to have good value with morph)
T6 No change
T7 No change Except : New structure in Panel Menu. I'm thinking about T3 Extractor / Fus / Storage

**Comment by Antarac** [comment]
If i get it right you mean like that to add a Advanced Eco Commander:

                                              Start Commander
                                            /                             \
                  Eco Commander                              Battle Commander
                                           |                                |
Advanced Eco Commander                               Assault Commander
                                            \                            /
                                             Star Commander
                                                          |
                                         Supreme Commander

**Comment by skymyj** [comment]
Eco Com                                            Battle
|                                                         |
Fusion Com                                        Assault Com
----------------------|-------------------------------
                                 |
                          Star Com
                                 |
                       Supreme Com

**Comment by Antarac** [comment]
Well, we seem to mean same thing except you called it
"Fusion Commander" and i called it "Advanced Eco Commander".

All T2 Units are also called "Advanced" so i would recommend that
but name can be discussed if the feature will be implemented i guess.

**Comment by skymyj** [comment]
Why not. We should do same between battle and assaut com. Adv battle
