### ISSUE TITLE
Mouseover build option stats

### ISSUE THREAD

**Issue by nixtux** [techannihilation/TA#410]
Ok so now we have info on mouseover of build option, what sort of info would be useful? Sand what current info is pointless

**Comment by nixtux** [comment]
Current stats that shown https://www.dropbox.com/s/1sws3u8ufyq6zfg/Screenshot_2017-07-23_05-53-12.png?dl=0

I've added build option for lab with costs will post image in a while

**Comment by nixtux** [comment]
https://www.dropbox.com/s/qo75p6qv97bbr4i/screen00083.jpg?dl=0

**Comment by skymyj** [comment]
I think Mass could be deleted.
Is it possible to add the explosion and selfdestroy type ?

**Comment by nixtux** [comment]
yeah mass can go it was added before i created a widget to show if units are loadable

**Comment by nixtux** [comment]
Mass is gone now

**Comment by nixtux** [comment]
its already does explosions types https://github.com/techannihilation/TA/blob/master/luaui/widgets/gui_mouseover_unit_stats.lua#L533
