### ISSUE TITLE
Angle Shoot for Lighting

### ISSUE THREAD

**Issue by skymyj** [techannihilation/TA#411]
If you compare TLLBIND and TLLBLIND (or Colossus), 

Bind have to be in front of target to shoot.
For Blind and colossus, the lighting can start behind unit. No sense. 
Is it possible to solve this problem ?

**Comment by nixtux** [comment]
Can I have a screenshot of this in action with a working unit and none working unit please.

**Comment by skymyj** [comment]
![screen00006](https://user-images.githubusercontent.com/2990630/28538731-97112ab0-70af-11e7-840c-917abec9c181.jpg)

**Comment by nixtux** [comment]
Script fixes needed for both units
