### ISSUE TITLE
New T2 Morph propositions

### ISSUE THREAD

**Issue by skymyj** [techannihilation/TA#413]
I propose to morph somes units from T1 into T2 : 
- Metal extractor T1 and T1.5 => T2
- Radar T1 (dust idea)
- Jammer T1 (dust idea)
- Energy Storage
- Metal Storage

For Metal extractor, I propose a long time like 60. This time will balance the facility to morph.

**Comment by nixtux** [comment]
hmm i will test t1>t2 mex as they are normaly placed close to labs or orther units , as there morph could cause issue with labs not working or units not firing ( dues to hitsphere + footprint + aimsphere increase)

**Comment by skymyj** [comment]
Great ;)

**Comment by skymyj** [comment]
Have you tested ?

**Comment by skymyj** [comment]
You can close
