### ISSUE TITLE
Tllsideneck

### ISSUE THREAD

**Issue by nixtux** [techannihilation/TA#415]
Why is it not buildable https://github.com/techannihilation/TA/blob/master/units/tllturtle_lab.lua#L46
when other labs have AA eg https://github.com/techannihilation/TA/blob/master/units/cortlab.lua#L52

**Comment by Antarac** [comment]
He might just not seen it since he commented other Issues so far.

**Comment by nixtux** [comment]
https://github.com/techannihilation/TA/commit/6f581ad76ff3e8dba7a06a248ccadd593ef4a8e9#diff-d0d65faff1d7c926c76f06718cbd179f
Skymyj why was it removed??
