### ISSUE TITLE
Need ARM T2 Shield vehicle

### ISSUE THREAD

**Issue by skymyj** [techannihilation/TA#416]
For inspiration : http://taesc.tauniverse.com/unitguide/unit_armspot.html

**Comment by Antarac** [comment]
You wanna use the FART model for the
Shield Vehicle or make a similar Vehicle?
For which Faction is it?

**Comment by skymyj** [comment]
Yep

**Comment by Antarac** [comment]
We got a new Faction named "Yep"? =)

**Comment by skymyj** [comment]
For arm. Cause they have t2 antinuke kbot.
Inverse for core, shield bot and antinuke vehicle

**Comment by Antarac** [comment]
Ok, makes sense.

**Comment by skymyj** [comment]
Good new. I have made them. 
What did you think ? 
![shield veh 02](https://user-images.githubusercontent.com/2990630/33339397-44b1e5ba-d479-11e7-97d1-ea087bee0051.PNG)
![Uploading shield veh.PNG…]()

**Comment by Antarac** [comment]
Looks good, maybe a little additional detail like an Antenna or something since surface looks so "even"

**Comment by skymyj** [comment]
Here zip to test it : [ARMSHIELDGEN.zip](https://github.com/techannihilation/TA/files/1513583/ARMSHIELDGEN.zip)

The wheels don't move but can be improved after.

**Comment by skymyj** [comment]
#709

**Comment by skymyj** [comment]
All files here : [ARMSHIELDGEN.zip](https://github.com/techannihilation/TA/files/1545170/ARMSHIELDGEN.zip)

**Comment by skymyj** [comment]
New upload : [ARMSHIELDGEN.zip](https://github.com/techannihilation/TA/files/1545949/ARMSHIELDGEN.zip)

**Comment by skymyj** [comment]
![capture](https://user-images.githubusercontent.com/2990630/34122629-668627e6-e42d-11e7-8f11-dfcc7cc415bd.PNG)
