### ISSUE TITLE
ARMCOREBUILDERS models

### ISSUE THREAD

**Issue by Thorgram** [techannihilation/TA#420]
These units were included in an tll beta where arm and core also had high tech builders.

[tech3kbotcons.zip](https://github.com/techannihilation/TA/files/1174527/tech3kbotcons.zip)

**Comment by skymyj** [comment]
Looks like to a turtle with only 2 legs :X 
Nix, I think we found the engineer turtle.

**Comment by skymyj** [comment]
We found a turtle plasma shield  tooo

**Comment by nixtux** [comment]
but turtles have 4 legs ?

**Comment by skymyj** [comment]
Well you are right. Like spiders have 8 legs, and most of them have 6 :X 
One of these models, have 4 legs. So, take this model for engenner. 
For other, transform it into shield kbot and will build by T2 Kbot TLL.
