### ISSUE TITLE
Delete the adv T1 radar

### ISSUE THREAD

**Issue by skymyj** [techannihilation/TA#423]
I think we should delete these units. 
Look like too much to normal radar with not really interest imho.

**Comment by Antarac** [comment]
I got a note to give Advanced Radar to the Battle Commander.

**Comment by skymyj** [comment]
You are right. If we keep this unit, we have to add for battlecom

**Comment by Antarac** [comment]
I think deleting units is a hughe mistake for many reasons.

Give it to Battle Commander so it gets built
automatically cause it's the one available.

**Comment by skymyj** [comment]
I think that same models have to be deleted or remplaced. 
That is why we remplaced arm/core t1 engineer.

**Comment by Antarac** [comment]
I don't mind to "replace" the model as
long as the unit doesn't get deleted.

**Comment by nixtux** [comment]
i don't mind re-texturing them but making a new model is too much work

**Comment by nixtux** [comment]
Re-textured units and added in a morph unlock chain of t1>t1.5>t2
