### ISSUE TITLE
Info Window

### ISSUE THREAD

**Issue by Antarac** [techannihilation/TA#425]
The Info Window in left bottom of screen just
disappeared for me since i played the test ta version.
Now it is also completly gone if i play
on other servers older TA version.
Same for Owl984.

**Comment by nixtux** [comment]
Delete spring/luaui/configs/TA.lua ,it's a bug with the widget

**Comment by nixtux** [comment]
I will add a check so it never saves too low negative numbers

**Comment by Antarac** [comment]
Ok, thx mate!

**Comment by nixtux** [comment]
Should be fixed with https://github.com/techannihilation/TA/commit/6d9d38ac3d4366e15153882f6b331b3633fddc8f
