### ISSUE TITLE
Commander build radius

### ISSUE THREAD

**Issue by Antarac** [techannihilation/TA#427]
In other games i seen many commander that have a bigger radius to build.
It actually is quiet comfortable and makes some things easier like building stacked buildings.
Since Commander is a special unit he should have a bigger build radius than others.
I mean way bigger than now like double radius.

**Comment by nixtux** [comment]
so 3x build power (ish) and massive hp compared to other t1 units is not a bigger enough buff already ?
imo this changed would make them so OP

**Comment by Antarac** [comment]
I ask for it, cause i experienced in
other games, that it just makes it
easier to build, cause pathfinding
is not always good.

Basically i thought about to make
it bigger for all ground units, i just
started with mention the Comm.

**Comment by nixtux** [comment]
Closing issue, won't happen
