### ISSUE TITLE
Gatling Gaat Gun Size

### ISSUE THREAD

**Issue by Antarac** [techannihilation/TA#428]
Gatling Gaat Gun model is bigger than the size shown when you build.

**Comment by nixtux** [comment]
Which gatling gun, unitname and faction please

**Comment by Antarac** [comment]
corvhlt - Gatling Gaat Gun - Very Heavy Laser Tower

**Comment by nixtux** [comment]
It's the same footprint as corhlt for a reason, the morph gadget, having footprint grow is a pita for this gadget, visual units will overlap

**Comment by Antarac** [comment]
So just changing the ground part of the model or close the issue is an option then as it seems.
