### ISSUE TITLE
MonkeyLord Weapon

### ISSUE THREAD

**Issue by skymyj** [techannihilation/TA#43]
Imho, his weapon is a little uggly.

What do you think about a Beam with 20s reload with large radius. 
Same than Valiant Miniion weapon. (but with red beam).

**Comment by nixtux** [comment]
Also barrel angle is off.

**Comment by ksilversurfer** [comment]
if you can make it nicer why not :)

**Comment by nixtux** [comment]
script fixed in https://github.com/techannihilation/TA/commit/c69322106be086352a2ce970ad1e3b94b3307151

**Comment by skymyj** [comment]
#98

**Comment by Antarac** [comment]
Dont change the Monkeylord! :O
