### ISSUE TITLE
To less Units

### ISSUE THREAD

**Issue by Antarac** [techannihilation/TA#430]
Many units got deleted over time in
TA as far as i know.
I understand there were reasons but it
makes game lesser attractive if unit
count get lower.
Since there come many new big units
i would suggest to also add a few back
to game that got deleted.
It would make the new update look even bigger.
Maybe some units were actually
not so bad and could get used.

Modify existing units to add them back
to TA and give them a reason to exist.

Add some units to fill holes in the
system to morph units with xp.

Add a builder for choppers.

Increase size of unused T1 or T2 units with
nice model and use them as T3 or T4.

It's not always bad if some units might be
quiet useless cause there will be always
units that feel more useless than others.

**Comment by nixtux** [comment]
The reasons for the one i have deleted in the past where either they where replaced by better looking units, or just deleted due to being darn right ugly (the old dev likes adding shit), or deleted due to bad game play reasons.

**Comment by Antarac** [comment]
I see, so only option is to make new units.
