### ISSUE TITLE
Round up !

### ISSUE THREAD

**Issue by skymyj** [techannihilation/TA#432]
If you see last version of BA. They have all rounded !

The unity is 0 or 5. 

So I'm very happy to be not in wrong direction. 
It's just a logic thing for increase the ergonomy of this game.

On the Panel Menu, all cost are visible. We should do the same thing if possible for you Nix.

Thanks.

**Comment by nixtux** [comment]
Yeah and everyone moaned about that shit idea....

**Comment by skymyj** [comment]
![sans titre](https://user-images.githubusercontent.com/2990630/28778815-31d30d24-7601-11e7-9dd5-4b72f7e09c1c.png)

whatever. The cost in panel menu is very good idea.

**Comment by nixtux** [comment]
We already have cost in tooltips and if you mouseover an icon for more than 2 sec you get far more information, I dont see the point of adding even more info over icons

**Comment by Antarac** [comment]
Just cause others did it,
it doesn't mean it's good.
Pictures get lost underneath the
numbers and with it the overview.

Write a widget if you really wanna
do it so everybody can choose to
turn it off?
But please don't implement that
permanently.

**Comment by nixtux** [comment]
Closing, clean up issue
