### ISSUE TITLE
Unique Geothermals, Core combat Engineer model, TLL Bladesmith Katar

### ISSUE THREAD

**Issue by Thorgram** [techannihilation/TA#433]
[tllkaterday.zip](https://github.com/techannihilation/TA/files/1188509/tllkaterday.zip)

**Comment by nixtux** [comment]
Link is broken

**Comment by Thorgram** [comment]
Try now

**Comment by nixtux** [comment]
hmm katar, is perfect for what i need apart from the blades i may have to rework him, thanks

**Comment by skymyj** [comment]
close it
