### ISSUE TITLE
Next TA version Idea

### ISSUE THREAD

**Issue by ghost** [techannihilation/TA#434]
- that new units i hoped to be T5 - more fun
- we need move TSAR to T5 even
- make t3 sheilds stronger or less energy espensive in usage
- to make TA more simple : **unlock lvls only by RC**, reduce costs of t2,t3, etc.. labs

**Comment by ksilversurfer** [comment]
- to make TA more simple : unlock lvls only by RC, reduce costs of t2,t3, etc.. labs - its not bad, look: to get t1.5 you need RC 1.5, to unlock T2 you need RC 2, ... so on - it will force you to use more low level units
also RC should not be xplosive as now, and should have more hp

**Comment by ksilversurfer** [comment]
[22:26:40] <[KING]Silver> pls comment https://github.com/techannihilation/TA/issues/434
[22:26:48] <[KING]Silver> please
[22:32:10] <oldman_keijjoo> ye i like it

**Comment by ksilversurfer** [comment]
[22:32:26] <oldman_keijjoo> just make morphing a bit faster

**Comment by ksilversurfer** [comment]
[22:32:26] <oldman_keijjoo> just make morphing a bit faster

**Comment by nixtux** [comment]
T3 Shields +1
Tsar move +1
For morph speed I could do modoption?

**Comment by ksilversurfer** [comment]
ye would be cool!

**Comment by skymyj** [comment]
I'm for delete all explosions for RC.
When you said move in T5, how will be? New RC, new cons? Im for add hero lab in t5.

**Comment by skymyj** [comment]
For morph speed, in lua files it's possible?

**Comment by ksilversurfer** [comment]
[15:39:16] <oldman_keijjoo> hey
[15:39:24] <oldman_keijjoo> if u gonna make that techs open by morphing
[15:39:32] <oldman_keijjoo> put a passive option to morph aswell
[15:39:37] <oldman_keijjoo> now its active and cant be paused

**Comment by ksilversurfer** [comment]
kejooo like it and me too,
not sure why you not?

**Comment by Antarac** [comment]
I vote yes...
...to make RC Explosion smaller, maybe like 2/3 lesser than now.
...that nano morph belong to RC only not to be also unlocked by factorys like now.
...to make the RC morph to T4 faster cause you need lots metal anyway, which takes time also.
...to remove the builder from RC and add it to a factory cause people dont find it on their own. They need to get told about it so it proofs that it's to complicated.
...after more units got added to T3/T4 it looks not so empty anymore in opposit to lower Tech levels so start T5 with TSAR as first unit for it.
