### ISSUE TITLE
New T4 Units rebalance - goal is +30% more strength than Super Bantha

### ISSUE THREAD

**Issue by ghost** [techannihilation/TA#444]
_Cost = EnergyCost * 0.016 + MetalCost
UnitStrength = ((DPS * Maxdamage)/Cost)
UnitResistance = maxdamage * maxvelocity_

### Actuall units balance:
**_Super Krogoth_**
**Prototype Super-Heavy Assault Kbot**

buildcostenergy = 1680000,
buildcostmetal = 167000,
cost =~ 193880
buildtime = 1200000,
maxdamage = 750000,
maxvelocity = 2,
dps = 6000 + 5250 + 960 + 15000 = 27210

UnitResistance  = 1500000
(unit resistance means how far it can go into enemy base)
UnitStrength = 105258

Conclusion:  
- VERY VERY strong unit with very high DPS

----------------------------------------------------------------------------------------
**_Super Bantha_**
**Very Heavy Assault Mech**

buildcostenergy = 1035000,
buildcostmetal = 96000,
cost =~ 112560
buildtime = 1250000,
maxdamage = 420000,
maxvelocity = 1.4,
dps = 740/0.4 + 960 + 15000/3 = 7810

UnitResistance = 588000
(unit resistance means how far it can go into enemy base)
UnitStrength =  29141 

Conclusion:  
- this unit we take as reference	 
- Lets make new T4 units 30 % stronger than Super Bantha
- Ultimately UnitStrength for new T4 units will be 38000
----------------------------------------------------------------------------------------

 **_Exoarm_**
**Experimental High Power Shield Kbot**

buildcostenergy = 1195000,
buildcostmetal = 98000,
cost =~ 117120
buildtime = 1250000,
maxdamage = 385000,
maxvelocity = 1.6,
dps = 400 + 5000 + 400 + 4000 = 9800

UnitResistance = 616000 + (!)StrongShield(!)
(unit resistance means how far it can go into enemy base)
UnitStrength = 32214 (max we can go is ~ 38000)

Conclusion: 
- cost have to be higher, 
- shield energy usage is too low,
----------------------------------------------------------------------------------------
 **_Dreadnought_**
**Experimental Heavily Armored Riot Kbot**

buildcostenergy = 601000,
buildcostmetal = 87650,
cost =~ 97266
buildtime = 850000,
maxdamage = 600000,
maxvelocity = 1.1,
dps = 3200(QUATRO_GUN) + 1400(tesla) = 4600

UnitResistance = 660000 + Anti air missiles
(unit resistance means how far it can go into enemy base)
UnitStrength  = 28375 (max we can go is ~ 38000)

Conclusion:
- cost have to be higher to match other new T4 units
- if higher cost we need boost DPS
- and maybe also HP again
----------------------------------------------------------------------------------------
**_Fatshrew_**
**Experimental Fast AutoRepair Siege Hexapod**

buildcostenergy = 1250005,
buildcostmetal = 109200,
cost =~ 129200,08
buildtime = 1000000,
maxdamage = 360000,
maxvelocity = 1.2,
dps = 1250+3000+480 = 4730

UnitResistance = 432000 + allterrian + (!) 2000hp/s autoheal (idle 60s) (!)
(unit resistance means how far it can go into enemy base)
UnitStrength = 13179 (max we can go is ~ 38000)

Conclusion: 
- Unit is weak, however it is allterrian and has autoheal feature
- Needs more DPS

**Comment by ksilversurfer** [comment]
**I need suggestion here for new values!!!**
Units have to be 30% stronger than Super Bantha

**Comment by skymyj** [comment]
Thanks for your work.
Dont forget than fatshrew have 6 passengers.
You should Reduce speed for krogoth2.
The visual effect for allterrain fatshrew is strange. I d like to delete this feature for all pod.
