### ISSUE TITLE
Commando

### ISSUE THREAD

**Issue by nixtux** [techannihilation/TA#453]
Change commandos roll to me the same as BA

**Comment by skymyj** [comment]
What do they do on BA ?

**Comment by nixtux** [comment]
Paratrooper unit, no damage from trans, they can build mines etc http://imolarpg.dyndns.org/trac/balatest/browser/trunk/units/commando.lua

**Comment by skymyj** [comment]
I'm for deelte them.
No use here.

**Comment by Antarac** [comment]
Nixtux' idea sounds good to me.
Change it or let it be but do not delete it!

**Comment by skymyj** [comment]
You can close it

**Comment by ksilversurfer** [comment]
can we add mines to it?

**Comment by skymyj** [comment]
You can close it

**Comment by Antarac** [comment]
Back in time when i played ba i used that unit sometimes cause of it's special abilitys.
