### ISSUE TITLE
More Constructors

### ISSUE THREAD

**Issue by Antarac** [techannihilation/TA#469]
How about adding more Constructors to the Factorys.
Many Factorys like Core Helicopter, T3 Vehicle, T3 Kbot got no Constructors.
Build lists would look more complete with Constructors.
They might just build the usual Tech Level stuff and nothing more.
If i have a Factory and i need builders it is somehow
disappointing if the Fac have no Constructors.

**Comment by skymyj** [comment]
T3 Cons added for all category. 
Add armorgate : https://snag.gy/jJ3isP.jpg

**Comment by skymyj** [comment]
![image](https://user-images.githubusercontent.com/2990630/35192917-0b5844ac-fe9b-11e7-8547-1e3e6718b793.png)
