### ISSUE TITLE
Tabi/tzar

### ISSUE THREAD

**Issue by nixtux** [techannihilation/TA#47]
I've been ask my many players if I can add thoses weapons back, I have no problem myself if there back if only available via a modoption.

Thougbt please

**Comment by skymyj** [comment]
I'm for with the option mod.
But, we should add 1 weapon for each faction.

Is it possible to change these weapon. (except one) ?

We will have : 
- tzar : don't change anything
- Tabi : Drop many laser projectiles with large Aoe (Pass over all).
- TLL : A Planetary Missile strike

**Comment by PenguiN560** [comment]
I'm for with the option mod too. It was funny total weapons.

**Comment by ksilversurfer** [comment]
mod option is ok

**Comment by ksilversurfer** [comment]
ye change weapons effects if you want

**Comment by nixtux** [comment]
There Back
