### ISSUE TITLE
T1.5 Shield unused

### ISSUE THREAD

**Issue by Antarac** [techannihilation/TA#473]
T1.5 Shield is cool but nobody uses it.
I would often like to use it but i cannot afford it mostly.
Put the T1.5 shield into T1 builder menu unlocked by
Researchcenter like the new Gatling Gun.

**Comment by skymyj** [comment]
I'm for ! And no need to have Research Center. 
It could be for all T1.

**Comment by nixtux** [comment]
Yeah move to t1 labs with rc lock for now

**Comment by ksilversurfer** [comment]
Idea is good !
