### ISSUE TITLE
Butcher Size

### ISSUE THREAD

**Issue by Antarac** [techannihilation/TA#474]
I recommend to decrease the size of "The Butcher" core defense .
25% smaller than now and it still got the size of an Advanced Fusion.

**Comment by skymyj** [comment]
Why did you recommend that ?
Thanks

**Comment by Antarac** [comment]
"The Butcher" is often hard to build cause of the size.
Especially if you wanna build a few.
There are not many different T3/T4 Defenses.
People seem to build it not often maybe it gets more used then.

**Comment by skymyj** [comment]
We have increase size of TLL DMC. I think, size reprensents the HP value (+65K). 
It's a powerful weapon and i see size here like a weakness of this powerful unit.
