### ISSUE TITLE
Airport units spin

### ISSUE THREAD

**Issue by Antarac** [techannihilation/TA#475]
Planes should not spin while building and at liftoff.
Makes also more sense to choose direction of airport,
if planes liftoff into same direction.
Core T3 Airport planes dont spin and it feels better.

**Comment by nixtux** [comment]
So which unit does?

**Comment by Antarac** [comment]
Basically it's not the units,
its the airport with the spinning
table where units spin on it,
while being built.
For Core it's T1 and T2 airport
where all units spin while being built.
When a plane is finished being built
it lifts of in the direction it just faces.

**Comment by ksilversurfer** [comment]
actually i dont undersand this issue

**Comment by Antarac** [comment]
The planes dont use the airport start ramp but there is one tho. They just start flying in random directions once they are built. If you make planes use the start ramp the player could decide the start direction when he builds the airport. More tactical options, more realistic plane behaviour at start. 
Basically all planes do a vertical liftoff so no difference to choppers or spaceships.
T3 airport looks like its built for vertical liftoff planes only but not T1 and T2.

You might could use the concept as well for plane repair pad.
Plane repair pad looks like a helicopter pad actually.
