### ISSUE TITLE
T1.5 mex size

### ISSUE THREAD

**Issue by Antarac** [techannihilation/TA#478]
If you upgrade from T1 mex to T1.5 mex it's hard to see
if its reclaim or upgrade since mexes have same size.
So when the half visible T1.5 mex is to see
when you auto upgrade its hard to recognize.
How about making t1.5 mex a little bit bigger
cause it would fit and look good.
Bit bigger than T1 mex but still smaller than T2 mex.

**Comment by nixtux** [comment]
Won't happen, it's already retextured + has lups effect
