### ISSUE TITLE
Morph Constructors

### ISSUE THREAD

**Issue by Antarac** [techannihilation/TA#479]
Make Constructors able to morph into better
Constructor if Research Center is upgraded enough.
So T2 Research center unlocks T1 Constructors
to morph to T2 Constructor.

**Comment by skymyj** [comment]
I'm not for. Cause, it will advantage good players who know play. Exemple : I make T2 Lab. Then I launch Morph. I reclaim Lab. 
I think, we have to decrease cost by 25 from T2.

**Comment by skymyj** [comment]
T2 Research Center is to unlock T.X. Not to unlock T1 T2 T3 or T4

**Comment by Antarac** [comment]
The Tactics to reclaim the Lab after
building a T2 Con exists already.
But it got nothing to do with this.

Ofc you need a RC and no Lab if you
morph a T1 Constructor into T2 Constructor.
But that means you will have no T2 Factory
to build units and you will also have no
Combat Engineer to build T2 Defense.

It opens new ways to play but it is no advantage like you said.
You need a RC that unlocks T2 kinda so it would
need a T2.5 RC to unlock the Constructor morph.
It would be a new feature but only for techers i'd say.

**Comment by skymyj** [comment]
> 

T2 Research Center is to unlock T.X. Not to unlock T1 T2 T3 or T4
--

If you add a new feature, I think we just add more difficulty to understand how RC work, for who ?

**Comment by Antarac** [comment]
Labs do unlock Nano Tower morph and they are no RC and neither T.X. aren't it?
How to unlock the Constructor morph by Factory?
