### ISSUE TITLE
Replay

### ISSUE THREAD

**Issue by nixtux** [techannihilation/TA#48]
He seems to start attack at 28-29 mins
35mins + there is a spike in widget:MapDrawCmd, but even thoses widget disabled the game still lags. 
Update even with luarules/luaui disabled the game still lags. 

Link to replay https://www.dropbox.com/s/mbncjycugmaxoqk/20170209_014039_techno%20lands%203v3%20v2_103.sdfz?dl=0
Link to chat log http://pastebin.com/EhmKys36

**Comment by pcdummy** [comment]
http://rene.jochums.at/downloads/replays.tar.bz2

**Comment by nixtux** [comment]
http://pastebin.com/EhmKys36

**Comment by nixtux** [comment]
Replay from spec/player http://www.filedropper.com/20170209014042technolands3v3v2103

**Comment by nixtux** [comment]
replay in question is 220170209_014039  -- in here http://rene.jochums.at/downloads/replays.tar.bz2

**Comment by nixtux** [comment]
at 35mins + there is a spike in widget:MapDrawCmd
but even the widgets that use thoses the game still tags

**Comment by nixtux** [comment]
He start at 28-29 mins

**Comment by nixtux** [comment]
Fixed in engine https://github.com/spring/spring/commit/5e84a729399f13a143d72d9163d0d7773e3ce4a4
