### ISSUE TITLE
Increase cost of T1.5 AK

### ISSUE THREAD

**Issue by Antarac** [techannihilation/TA#483]
With my T1.5 AK zergling rush strategy i
were able to wipe out 90% of my enemys.
Increase metal cost of T1.5 AK by 10%.

**Comment by skymyj** [comment]
Same for adv pewee ?

**Comment by ksilversurfer** [comment]
Increase metal cost of T1.5 AK by 10%. - agree

**Comment by ksilversurfer** [comment]
and peewee too ofc

**Comment by ksilversurfer** [comment]
actually even 15% can be ok
