### ISSUE TITLE
The Butcher missing

### ISSUE THREAD

**Issue by Antarac** [techannihilation/TA#485]
I cannot find "The Butcher" here:
https://github.com/techannihilation/TA/wiki/Units

**Comment by skymyj** [comment]
Search : 
corboucher | The Bucher | Anti Experimental Cannon

**Comment by Antarac** [comment]
corboucher | The Bucher | Anti Experimental Cannon
Will somebody change the names of this list if i find wrong ones like in this case:
"The Bucher" instead "The Butcher" and "corboucher" instead "corbutcher"
