### ISSUE TITLE
Slow Combat Engineer Vehicle

### ISSUE THREAD

**Issue by Antarac** [techannihilation/TA#486]
The Core Combat Engineer Vehivle "corassis"
needs ages to open it's lid to build.
Make it way faster since a Combat Enginner
should react not that slow to start to build.

**Comment by skymyj** [comment]
Sure. But it has more range and heal too. 
There was a vote about it. 
But why not to rechange again.

**Comment by Antarac** [comment]
Sadly i don't know about old changes.
I just post what i think is good.
