### ISSUE TITLE
Square base crater

### ISSUE THREAD

**Issue by Antarac** [techannihilation/TA#487]
If buildings explode they leave craters with form of a square.
Shouldn't it be round craters since explosions are not in form of a square?
![screen00035](https://user-images.githubusercontent.com/24976973/29661253-be7848aa-88c3-11e7-8efd-6b8a864cc2a0.jpg)

**Comment by nixtux** [comment]
No closing issue

**Comment by Antarac** [comment]
Cause of map polygon amount?
