### ISSUE TITLE
Mountain steepness widget

### ISSUE THREAD

**Issue by Antarac** [techannihilation/TA#493]
You start play a game,
build a big group of tanks,
you drive far,
tanks get stuck on terrain...
You think damn map,
game might be lost...

What if there would be a way to know it,
before you build tanks?

How about a widget that shows a symbol
next to mouse cursor or in info window.
Your mouse cursor hovers over the map and you
press for example CTRL key and it shows the symbol:

A greenTank symbol for ground that is even enough for vehicles.
A yellow Kbot symbol for steep parts that work only with Kbots.
And a red spider for cliffs.

**Comment by skymyj** [comment]
Good idea even if amphibious can climb low mountain

**Comment by ksilversurfer** [comment]
ok this can be usefulll and idea is nice

**Comment by Antarac** [comment]
Yeah, nice idea but will it happen or close it?
