### ISSUE TITLE
Pinchy Tail

### ISSUE THREAD

**Issue by Antarac** [techannihilation/TA#495]
The Texture of last part of the Tail from unit Core
"Pinchy - All-Terrain experimental Engineer"
looks a bit strange.
At least on lowest graphic settings.

**Comment by nixtux** [comment]
Can I have a screenshot please

**Comment by nixtux** [comment]
Can I have a screenshot please

**Comment by Antarac** [comment]
Yes, give me some minutes.

**Comment by Antarac** [comment]
![screen00051](https://user-images.githubusercontent.com/24976973/30114296-c157dafa-9317-11e7-803e-2b3e2869443e.jpg)

![screen00052](https://user-images.githubusercontent.com/24976973/30114303-c759e98e-9317-11e7-92e9-ba68ce913d1a.jpg)

**Comment by skymyj** [comment]
I will fix that #860

**Comment by skymyj** [comment]
Most important than tail is the nano tower bug. Stay inside pinchy and turn inside body :X

**Comment by skymyj** [comment]
![image](https://user-images.githubusercontent.com/2990630/36111000-f29a3380-1024-11e8-90bf-9c44c57b9476.png)

**Comment by skymyj** [comment]
you can close it

**Comment by Antarac** [comment]
When i posted this issue there was no pinchy builder =)
Did you fix both issues sky?
