### ISSUE TITLE
Hero's occupy same space

### ISSUE THREAD

**Issue by Antarac** [techannihilation/TA#496]
Whats the reason Capitals like Core
"Devastator" have no Collision Box?

**Comment by nixtux** [comment]
https://github.com/techannihilation/TA/wiki/cdevastator this unit?

**Comment by Antarac** [comment]
Yes, is it possible to add a collision box so they don't fly into each other?

**Comment by nixtux** [comment]
Ah you mean can they occupy the same area, for that the collide tag needs to be set false, which has it downside, extra cost from calculations, I will need to test performance change

**Comment by Antarac** [comment]
Thought about that too but usually people just build a handful of Capitals, not a few hundred like with Planes or Small Units.

**Comment by Antarac** [comment]
People build not many of these
in usual games so i'd guess it's ok.

But what will happen if Capital with
Collision fly right trough an Air Screen
with hundreds of Fighters?
