### ISSUE TITLE
Adv Nuke

### ISSUE THREAD

**Issue by skymyj** [techannihilation/TA#508]
Is it possible to have new models for these structures ? 
(T2.5 ICBM)
Other textures, or bigger ?!

Thanks

**Comment by nixtux** [comment]
Bigger is a no due to potential issue, but re-textured is a yes

**Comment by skymyj** [comment]
Same request for Anti nuke static and mobile.

**Comment by nixtux** [comment]
The only issue is time xD

**Comment by skymyj** [comment]
I will work on this

**Comment by skymyj** [comment]
And what about add the fast nuke for TLL too ?
