### ISSUE TITLE
New screens to start game

### ISSUE THREAD

**Issue by skymyj** [techannihilation/TA#513]
With all last changes, I think it's important to have a new identity. 
So I propose to have new screens or pictures at start loading.
If you are agree, we could launch a "play concour". the best 3 screenshots will be added on new release ?

Other Advantage : Have a better link with players ! Add fun to the community.

**Comment by Antarac** [comment]
Sounds Great!

**Comment by frju365** [comment]
I agree totally !

**Comment by Antarac** [comment]
Yeah, bring it on!
Good time for it!
