### ISSUE TITLE
Bug with T2.5 units.

### ISSUE THREAD

**Issue by skymyj** [techannihilation/TA#515]
I have problems with T2.5, T3.5 units. when I select a unit T2.5, the panel menu vanishes. I have to reload Widget to reappear it. And the T2.5 units are always locked even if I have T2 RC.

Do you know why ?
![capture](https://user-images.githubusercontent.com/2990630/30239248-907235fa-9558-11e7-824b-3aefa6eb0c2f.png)

**Comment by nixtux** [comment]
Already fixed
