### ISSUE TITLE
WTF is!?

### ISSUE THREAD

**Issue by skymyj** [techannihilation/TA#52]
On Blue Map. 
Many explosions from bugs.
At 1h05min30s begins
SDZ : https://1drv.ms/u/s!AgjKPxaKD1zLiiJEVKvVMKYNAuOU

![capture1](https://cloud.githubusercontent.com/assets/2990630/22858493/9791d6a8-f0bf-11e6-8c9c-689b43e77cff.PNG)

**Comment by ksilversurfer** [comment]
its orion t3 arm bomber, just simple attack
