### ISSUE TITLE
Tech Annihilation Soundtracks

### ISSUE THREAD

**Issue by ghost** [techannihilation/TA#520]
Please post Royalty Free or Creative Commons music here, post link to the song so we can check licence.

My first fav list:

https://entropyaudio.bandcamp.com/track/honour-2
https://entropyaudio.bandcamp.com/track/annihilation-2
https://entropyaudio.bandcamp.com/track/we-stood-as-titans
https://entropyaudio.bandcamp.com/track/eye-of-the-storm
https://entropyaudio.bandcamp.com/track/man-and-the-machine
https://entropyaudio.bandcamp.com/track/salvation-is-distorted
https://entropyaudio.bandcamp.com/track/aftermath
https://entropyaudio.bandcamp.com/track/across-this-ravaged-world
https://entropyaudio.bandcamp.com/track/bring-the-fight-to-them
https://entropyaudio.bandcamp.com/track/hold-the-line
https://entropyaudio.bandcamp.com/track/the-end-has-come
https://entropyaudio.bandcamp.com/track/into-the-maelstrom
https://entropyaudio.bandcamp.com/track/legion-2
https://entropyaudio.bandcamp.com/track/dark-rites-2
https://entropyaudio.bandcamp.com/track/relentless
https://entropyaudio.bandcamp.com/track/the-engine-breathes
https://entropyaudio.bandcamp.com/track/scifi-guitar
https://entropyaudio.bandcamp.com/track/arriving-at-the-station
https://entropyaudio.bandcamp.com/track/b-i-t-c-n-a-i-a-m-a
https://entropyaudio.bandcamp.com/track/to-the-frontier

Need to be sorted btw

**Comment by ksilversurfer** [comment]
Second list (more dark):
https://keosz.bandcamp.com/track/adverse
https://keosz.bandcamp.com/track/paragon
https://keosz.bandcamp.com/track/arrival
https://keosz.bandcamp.com/track/outgoing
https://keosz.bandcamp.com/track/6-keosz-crush-them

**Comment by Antarac** [comment]
The beats per minute are to low for me to play.
Game is fast, music tact is slow.
