### ISSUE TITLE
Pririty for TA : Units missing !

### ISSUE THREAD

**Issue by skymyj** [techannihilation/TA#530]
With all new changes, some units very important are missing. 

All factions : 
- T3 Cons Vehicle and air
- Sea LLT 

TLL : 
- Adv Metal Maker (T1.5)
- Adv Metal Maker (T3)
- T4 Rapid assault Kbot (as corkrag or armraz)
- Battle Geothermal (I see flammer with low range and max Hp)
- T3 and T4 Rapid Bertha
- T3 Bertha
- T1.5 Immolator (Bertha)
- Increase size of Hailstorm

**Comment by skymyj** [comment]
Hey. 
I worked on 3 vehicle construction for Adv T3 Cons. 
I test them and all work. 
If you want to test them : I attach zip file. 
[ECV.zip](https://github.com/techannihilation/TA/files/1513546/ECV.zip)

**Comment by nixtux** [comment]
WARNING LONG GONE ARE THE DAY OF ADDING OTA SCRIPTS TO SPRING, All script need fixes before there added or corpse won't work and every explosion trigger needs an extra tag added, don't add any units until this is fixed.

**Comment by skymyj** [comment]
Sure Nix. If you accept models, ideas, could you help me to fixes these files ?

**Comment by skymyj** [comment]
New files with OTA script : T3 Ship, Air, Vehicle ARM / CORE + TLL Vehicle

**Comment by skymyj** [comment]
New model for TLL GEO Armored : https://1drv.ms/v/s!AgjKPxaKD1zLlR3vRi7gr2LP9Ru1
