### ISSUE TITLE
HailStorm issue

### ISSUE THREAD

**Issue by skymyj** [techannihilation/TA#548]
Hailstorm became T4 Artillery. 
Goal is to shoot at long range (like Vulcain or Buzz) and high damage.

- First issue : 
Actually, he can't shoot over 2000 Range even if, range sets at 5300. 

- Proposition : 
Due to the T4 categorie Kbot and powerfull, is it possible to increase size by 20% ?

Thanks

**Comment by nixtux** [comment]
1. Don't just buff range without velocity increase, anyways he was supposed to be a low range high damage unit. I dislike the massive range increase

**Comment by skymyj** [comment]
TLL is missing a Lol Canon. Do you want to add this unit ? PA added one.
So, I think to add this job for the hailstorm while  there is no T3/T4 rapid plasma.

**Comment by nixtux** [comment]
One I don't care what PA has or has not, but we do need a lol cannon counterpart but not a mobile unit.
