### ISSUE TITLE
Add secondary weapon for Howie

### ISSUE THREAD

**Issue by skymyj** [techannihilation/TA#55]
When I saw this weapon no used, I think we could add a small AA missile x 2. It will not change balance imho.
![capture](https://cloud.githubusercontent.com/assets/2990630/22863189/e2da9dee-f13b-11e6-9ace-3b656389d4ab.PNG)

**Comment by nixtux** [comment]
Your extra lucky today the script part,  is there for thoses as an extra weapon.

**Comment by skymyj** [comment]
:) we are connected
