### ISSUE TITLE
MDS

### ISSUE THREAD

**Issue by skymyj** [techannihilation/TA#563]
Is it possible to move them for enginneer ?

**Comment by nixtux** [comment]
Mds?, move to or from?

**Comment by skymyj** [comment]
Move to into engineers. 
Air T2 cons didn't have them

**Comment by skymyj** [comment]
Nix. MDS can't stop starburst vs armbanth for example.

**Comment by skymyj** [comment]
So Nix, what is your decision ? 
Can I work on this ? Move all MDs to engineers ?

**Comment by ksilversurfer** [comment]
i vote yes, having them in t2 cons is not handy
