### ISSUE TITLE
Rework Ligthing (Main weapon) for TllRoaster (T2 veh)

### ISSUE THREAD

**Issue by skymyj** [techannihilation/TA#572]
This lighting is really uggly. 
Moreover, many units have now the new and nice beam lighting (tesla tank (morphing from roaster), bind, blind, llt). 

I propose to equip the roaster with them for ~same balance. 
The big change will be the quick reload and less energycost for beam (500 for TLL for 8s Vs 1000 for Arm mobile Tachyon).

I balanced this unit (cost was not enough high vs Arm Mobile Tachyon : https://github.com/techannihilation/TA/blob/master/units/armmanni.lua)

**Comment by nixtux** [comment]
The new visual is more expensive, I've already had to fix tll t3 tanks weapon you changed, it had way too many projectiles and didn't match damage.

**Comment by skymyj** [comment]
The TLL T3 tank is good balanced. Damage matches at 50% at long range. And increase at medium range.

Last time, I heard Mrweak say, the lighting was really nice and beautiful. 
Now, it's units with high cost. So, if there are 10 units, it's good. I don't think, the particules cost will change many things with lags..

**Comment by nixtux** [comment]
I fixed damage hp and visual here https://github.com/techannihilation/TA/commit/9e8afd825af77a114fcb3b57cafc46af8d0336a3#diff-6e3b128e83ab8070a7c166a991967b8b

**Comment by skymyj** [comment]
Ok. Good. I thought you want to reverse weapon type.. 
It's a big stats increase. To test.

**Comment by nixtux** [comment]
No just keep projectile count down its costly
