### ISSUE TITLE
Coastal Wave Powerplant

### ISSUE THREAD

**Issue by Antarac** [techannihilation/TA#590]
How about a new kind of tidal powerplant?

![pic1](https://user-images.githubusercontent.com/24976973/32415175-b011fe9a-c235-11e7-892c-b3fd3dbaf440.jpg)
![pic2](https://user-images.githubusercontent.com/24976973/32415176-b38d81b6-c235-11e7-8116-8d2c1d88849d.gif)

**Comment by skymyj** [comment]
I think it's too complicated. 
I'm not sure that engine understand to make on ground near the water.
