### ISSUE TITLE
Fusion Comm Metal Maker

### ISSUE THREAD

**Issue by Antarac** [techannihilation/TA#591]
Fusion Commander got T2 underwater metal maker but no T2 land metal maker.

**Comment by skymyj** [comment]
Yes they have.
But i don't understand, there is a bug. Don't appear for core only. Arm works

**Comment by skymyj** [comment]
https://github.com/techannihilation/TA/pull/595/files

Done

**Comment by skymyj** [comment]
I bugged

**Comment by skymyj** [comment]
You can close it. Resolved.
