### ISSUE TITLE
TLL Commander Symbol

### ISSUE THREAD

**Issue by Antarac** [techannihilation/TA#592]
TLL commander symbol got a black line on left side.
(When you zoom far away and model gets exchanged by symbols) 

![screen00061](https://user-images.githubusercontent.com/24976973/32415223-64fee2a0-c236-11e7-9aab-0532e51db92e.jpg)

**Comment by nixtux** [comment]
Fixed by silversurfer with this commit https://github.com/techannihilation/TA/commit/82805ff23cba5cea98f18b9f433aa91484519c12#diff-8b9f6bb1e873f201a005eed9c8ef5653
