### ISSUE TITLE
Compare Fido balance vs Morty vs Troll

### ISSUE THREAD

**Issue by ksilversurfer** [techannihilation/TA#608]
[12:52:48] <[KING]AutoHost1> <[PiRO]klapmongool> o lol
[12:57:05] <[KING]AutoHost1> <[PiRO]klapmongool> mortyy too strong
[12:57:12] <[KING]AutoHost1> <[PiRO]klapmongool> fido
[13:01:25] <[KING]AutoHost1> <[PiRO]klapmongool> lolwtf

Odd I never had issue with fido balance, but lets check it

**Comment by skymyj** [comment]
I think the arti TLL is weaker.
I wil l watch all stats

**Comment by skymyj** [comment]
Well. They are ~balanced. 
Just, the ratio Energy cost for Core is too low. Need to increase.
Hard to balance these 3 units, cause all stats are differents. Fido is quick and resistant and low range, mortor are weak, slow but high range, and tll are very resistant but slow.

**Comment by ksilversurfer** [comment]
nah dont increase cost for core, i thought that arm Fido is bit op, not core
