### ISSUE TITLE
Pinchy is a crayfish and TllDoc is a doctor

### ISSUE THREAD

**Issue by skymyj** [techannihilation/TA#611]
And where does a crayfish live ? In water. 
I'm for add the amphibious movement class for this unit in addition to all-terrain (like Turtle).

For TLLDoc, I'd like to add a feature like Autorepair (tlldoc) instead of amphibious movement class.

**Comment by nixtux** [comment]
Nope and nope

**Comment by skymyj** [comment]
Ah :) you are alive :) 
I knew that this issue will do jump you from your chair
