### ISSUE TITLE
Razorback weapon

### ISSUE THREAD

**Issue by skymyj** [techannihilation/TA#613]
Many ARM units fire a blue laser from main weapon : 
- T1.5 aexxec
- T2.5 armcd 
- T3.5 Juggernault

I propose to change red beam laser by this blue laser.

**Comment by ksilversurfer** [comment]
I like red lasor of razorback, but if you want blue and nix agree then i can agree :P

**Comment by skymyj** [comment]
![capture](https://user-images.githubusercontent.com/2990630/32855462-fcc37ab6-ca41-11e7-894c-066945d1b2b0.PNG)

**Comment by ksilversurfer** [comment]
looks not bad, i agree
