### ISSUE TITLE
tll turtyle anti sub can't have sonar

### ISSUE THREAD

**Issue by skymyj** [techannihilation/TA#668]
I add the line but can't work. 
https://github.com/techannihilation/TA/blob/master/units/tllleatherback.lua

Help.

**Comment by ksilversurfer** [comment]
hmmm i will check this

**Comment by Antarac** [comment]
So the Turtle got sonar and you want to remove it?
Sounds good since only hughe ships should have their own sonar in my opinion.

**Comment by skymyj** [comment]
On lua files, there is a sonar. In real life not. 
All anti sub should have a sonar.

**Comment by Antarac** [comment]
I see.
I'm ok with that change.
