### ISSUE TITLE
Ratio for metal extractor

### ISSUE THREAD

**Issue by skymyj** [techannihilation/TA#675]
We have problematics with balance. 
We need have 4 levels for Mex.

Ratio : T1 = 1 --- T1.5 = T1 x 2 ----- T2 = T1 x 6 ---- T3 = T1 x 24  ------ T4 = T1 x 72
T1.5 Ratio vs T1 : 2
T2 Ratio vs T1 : 6
T3 Ratio vs T2 : 4
T4 Ratio vs T3 : 3

**Comment by Antarac** [comment]
Can you post also how it was until yet so we can compare past/future?

**Comment by skymyj** [comment]
Sure. ATM it's : 
Ratio : T1 = 1 --- T1.5 = T1 x 2 ----- T2 = T1 x 6 ---- T3 = T1 x 36
T1.5 Ratio vs T1 : 2
T2 Ratio vs T1 : 6
T3 Ratio vs T2 : 6

**Comment by nixtux** [comment]
There is nothing wrong with the current ratios, stop re inventing the wheel

**Comment by skymyj** [comment]
FI : I'm not reinventing the wheel, but it's the community. 
Now I accept your opinion. No problem.

**Comment by skymyj** [comment]
If everyone is ok for new extractor. There is 2 models here : 
[MAS.zip](https://github.com/techannihilation/TA/files/1522066/MAS.zip)

**Comment by skymyj** [comment]
So, with new T3 Cons, I propose these new balanced ratios : 
NO CHANGE FOR ALL except new T3 at 16 RATIO.
Ratio : T1 = 1 --- T1.5 = T1 x 2 ----- T2 = T1 x 6 ---- T3 = T1 x 16 ------ T4 = T1 x 36

For example for a 2m/S for a T1 mex, it gives : 
T1.5 = 4m/s
T2 = 12m/s
T3 = 32m/s
T4 = 72m/s
