### ISSUE TITLE
Super unit

### ISSUE THREAD

**Issue by skymyj** [techannihilation/TA#680]
With Keiji and Silver, we talked about super units : T4 T4.5 T5 T5.5 T6 

- Take strong T1.5 unit  => kill light T2 (T1.5 heavy tank vs armfast or corpyro) but will be annihilated by T2 classic. (vs Bull)
- Take strong T2.5 unit => Kill light T3 (Krogtaar armraz) but will be annihilated by T3 classic (vs Bantha). 
- Take strong T3.5 unit => Kill light T4 (Krogoth vs armraz1) and balanced fight vs medium T4 (Moonkey)
- IMHO : T4.5 (Krog and furie) killed by T5 Hero.

To resume : 
- I think, we need keep the T4.5 unit with new Furie1 and Krogoth1.
- I'm not to have T5 Furie and Krogoth and T5.5 Hero. (main reason about sense and lab missing).
- I'm for decrease all stats for T4.5 units. Fatshrew and Exoarm and maybe unlock them.
- T4.5 : have to be 750K HP, 13K dmg/s, Speed = same than V0 version (0,9 for furie and 1.2 for krogoth)

**Comment by ksilversurfer** [comment]
yes agree

**Comment by skymyj** [comment]
With last changes you done Silver, is it possible to : 
- have same range / damage for starburstlauncher krog1 / Furie1 (for T3, range = 1050 and damage 250. You can't have same value for T4.5 Furie. Increase to 1600 and 960dmg/S with reload 1s like Krog). Maybe decrase other weapon to balance.
- Less speed for both (0,9 for furie and 1.2 for krogoth)

**Comment by ksilversurfer** [comment]
1.  Maybe you are right here
2.  Furie1 with speed 0.9 it will look horrible, Krog1 need min 1.3 or will look like moving in place

**Comment by skymyj** [comment]
Understood. Best is to change bos settings to slow down leg. 
Now, solution ca nbe to increase speed (atm config), but decrease again HP. Very hard to stop them :X
