### ISSUE TITLE
The spice of life

### ISSUE THREAD

**Issue by nixtux** [techannihilation/TA#697]
So some units between faction have nearly the same balance this shit had to stop now.....
Eg the metal, energy, buildtime
T2 kbot lab
https://github.com/techannihilation/TA/blob/master/units/armalab.lua
https://github.com/techannihilation/TA/blob/master/units/coralab.lua
https://github.com/techannihilation/TA/blob/master/units/tllalab.lua  (buildtime only) 
Compared too ba
https://github.com/CommanderSpice/Phoenix-Annihilation/blob/master/units/armalab.lua
https://github.com/CommanderSpice/Phoenix-Annihilation/blob/master/units/coralab.lua

Please stop now with this and start fixing it

**Comment by ksilversurfer** [comment]
1 000 000% Agree
Skymyj we need make all factions more different not more the same..
I merged a lot , but i feel bad now, we need rework it - i say it seriously.

**Comment by ksilversurfer** [comment]
Skymyj pls think about it

**Comment by skymyj** [comment]
Spice of Life : I'm for and maybe we did mistakes. 
1 : I don't remember have balanced lab. 
2 : your example is bad chosen : 
**TA**
armalab : 72466E 4107M 45524T 
coralab : 71845E 4117M 45519T
Difference : 621E 10M 5T

**BA**
coralab : 16247E 2850M 16819T
armalab : 14678E 2911M 16224T
Difference : 1569E 61M 594T

Explain me the Spice of Life in this example.

**Comment by nixtux** [comment]
No its not badly chosen, you energy is nearly 3x different ,  metal 6x and buildtime woo 120x for buildtime, need I say more....

**Comment by nixtux** [comment]
T2 vehicle labs are even worse, all need fixing.....

**Comment by skymyj** [comment]
I will not change anything without validation for these rules : 
ARM : Metal decrease by 2%. Decrease buildtime by 5%
CORE : Energy decrease by 10%. Increase buildpower by 25.
TLL : Increase buildtime by 10% and buildpower by 50.

Change values if you want, but I will not lost time to remake commits.

**Comment by nixtux** [comment]
Where did thoses values come from a hat?, I don't remember seeing any thread where thoses values were decided by all other devs, don't worry I will fix issue if you not prepared to

**Comment by skymyj** [comment]
Yes please. I'm not skilled to fix this issue.

**Comment by Antarac** [comment]
http://totalannihilation.wikia.com/wiki/CORE
CORE units are generally stronger than ARM units, but they have lower speeds and take longer to build. 

http://totalannihilation.wikia.com/wiki/ARM
ARM units are generally more agile and quicker to build than CORE units, but they have weaker armour and less firepower, making them rely on a more strategic approach to the war.
