### ISSUE TITLE
We are on TOP

### ISSUE THREAD

**Issue by ghost** [techannihilation/TA#703]
Too keep it:

 - We should make T4.5 / T5 units more expensive -  i mean super vulcan, and TSAR
(By 25% more)
 - We need rebalance **T3 Veh units** - they are now too weak!!!!

Thanks

**Comment by ksilversurfer** [comment]
https://snag.gy/LaE8Ob.jpg

**Comment by ksilversurfer** [comment]
And huge +++ for Nixtux for game performance

**Comment by skymyj** [comment]
Yep ! congratulation !

**Comment by skymyj** [comment]
About t3 vehicle : I think they are good balanced. If you change T3 veh, then you have to change t2 kbot, t2 tank, all units...
 I think, we have worked for years to have pretty good blance until here. It just T4/T5 to balance correctly with all T1 T2 T3 units.

**Comment by skymyj** [comment]
Ok too increase again the cost of TSAR and Rapid Bertha. Maybe 10%.
For T4, I propose to unlock Fatshrew and exoarm. If we do, we should decrease their strenght and cost too to have max 90KM.
