### ISSUE TITLE
Testing before PR

### ISSUE THREAD

**Issue by nixtux** [techannihilation/TA#705]
So helepolis has not been tested at all now there are 4 errors/warning in infolog.txt for this one unit, I spent a lot of time fixing all this errors/warning, please test your work or I will revert it

**Comment by nixtux** [comment]
At this rate it will end up as messy as EVO rts infolog.txt.......

**Comment by ksilversurfer** [comment]
yes i noticed that errors too, yeah i should check skymyj pr locally before merge.
I will next time.
Skymyj pls try fix that errors, if you cant i will later today.

**Comment by skymyj** [comment]
I do programmation in school and in my personnal life but it's not my job.
I can learn quickly. But I need advices and more pedagogical approach please.

Best could be to make some prints (video..) and show things we have to focus.
We lost all less time.
Thanks.
