### ISSUE TITLE
Fix Color of New Icons

### ISSUE THREAD

**Issue by ksilversurfer** [techannihilation/TA#707]
armarpe - should be red
ferret  - should be blue
armmine7 - should be blue
armtys - should be red
apache - should be red

**Comment by skymyj** [comment]
Hepolis red and unexisting

**Comment by ksilversurfer** [comment]
you mean *helepolis - should be yellow

**Comment by skymyj** [comment]
Yep. Helepllis is core unit. Red

**Comment by ksilversurfer** [comment]
ah i thought it will be tll

**Comment by ksilversurfer** [comment]
so
helepolis - should be red :D

**Comment by nixtux** [comment]
All fixed closing issue
