### ISSUE TITLE
Can I begin to work on T3 Vehicule/Air Constructor ?

### ISSUE THREAD

**Issue by skymyj** [techannihilation/TA#710]
I'd like to share my new skills to improve game. 
Do you have project to give me ? If no, can I begin to work on T3 cons ? 
Thanks.

**Comment by ksilversurfer** [comment]
FIX:
`[f=-000001] Warning: WeaponDefs: Unknown tag "ballistic" in "helepolis_core_juggingcan"
[f=-000001] Warning: WeaponDefs: Unknown tag "minbarrelangle" in "helepolis_core_juggingcan"
[f=-000001] Warning: WeaponDefs: Unknown tag "rendertype" in "helepolis_core_juggingcan"
[f=-000001] Warning: WeaponDefs: Unknown tag "startsmoke" in "helepolis_core_juggingcan"`

**Comment by skymyj** [comment]
Error: [GetFeatureDef] could not find FeatureDef "core_juggernaught_dead"

**Comment by ksilversurfer** [comment]
ofc you can, i dont care

**Comment by nixtux** [comment]
Fix https://github.com/techannihilation/TA/issues/697

**Comment by nixtux** [comment]
Also see https://github.com/techannihilation/TA/issues/294

**Comment by nixtux** [comment]
Merging but we must replace core with a better model
