### ISSUE TITLE
Add New model T4 Air

### ISSUE THREAD

**Issue by skymyj** [techannihilation/TA#731]
[ARMWING.zip](https://github.com/techannihilation/TA/files/1572651/ARMWING.zip)
Video : https://1drv.ms/v/s!AgjKPxaKD1zLlQtLoAGfQObd4Gn-
![capture 1](https://user-images.githubusercontent.com/2990630/34170760-64c4cd08-e4ec-11e7-8aa2-a29a43695816.PNG)
Possible to add morph from a T3 fighter. Or unlock with T4 RC from T3 Air Lab.
Mission : Air superioty.

**Comment by skymyj** [comment]
Reactor doesn't work, cause no check the good widget

**Comment by nixtux** [comment]
Are thoses two domes on the front fusion then?

**Comment by skymyj** [comment]
I think yes.
3 options : 
- I could delete them
- Keep them. Nice model
- Keep them => we could transform fusion into small shield generator (vs flak) ?

**Comment by nixtux** [comment]
1. Sounds better to me
2. That effect won't look good on a moving unit
3. 2 shields is too much

**Comment by skymyj** [comment]
Ok. I will dlete them and add a PR this evenning. 
So, we will add this unit only by Morph. The footprint unit is too big to add in Air Lab.

I have another model for Core : 
![image](https://user-images.githubusercontent.com/2990630/34722848-c68de328-f548-11e7-817d-ee77b569abf1.png)

**Comment by skymyj** [comment]
What do you think ?
![capture](https://user-images.githubusercontent.com/2990630/34748186-a001e512-f59b-11e7-81e1-252182603036.PNG)
