### ISSUE TITLE
Unbuildable units

### ISSUE THREAD

**Issue by nixtux** [techannihilation/TA#734]
[f=-000001] unbuildable unit , armfark1
[f=-000001] unbuildable unit , consul1
[f=-000001] unbuildable unit , armdark
[f=-000001] unbuildable unit , aspdbunk
[f=-000001] unbuildable unit , armvisit
[f=-000001] unbuildable unit , ametalmakerlvl1
[f=-000001] unbuildable unit , cmetalmakerlvl1
[f=-000001] unbuildable unit , armorca
[f=-000001] unbuildable unit , armshltx1
[f=-000001] unbuildable unit , armabad
[f=-000001] unbuildable unit , tllsideneck
[f=-000001] unbuildable unit , armmedt
[f=-000001] unbuildable unit , corgant1
[f=-000001] unbuildable unit , corhevsenan
[f=-000001] unbuildable unit , tllfnanotc3
[f=-000001] unbuildable unit , tawf015
[f=-000001] unbuildable unit , corfast1
[f=-000001] unbuildable unit , vaporiser
[f=-000001] unbuildable unit , tawf116
[f=-000001] unbuildable unit , armcbomb
[f=-000001] unbuildable unit , corrag
[f=-000001] unbuildable unit , tllbats2
[f=-000001] unbuildable unit , cortermite

**Comment by skymyj** [comment]
flea1 I think too

**Comment by nixtux** [comment]
Should be working/in armabad, tllsideneck, corrag, tawf015, tllfnanotc3
To Reuse armorca, tllbats2, armdark, armvisit

**Comment by nixtux** [comment]
Tllfnanotc3 is now buildable

**Comment by nixtux** [comment]
Armvisit now buildable

**Comment by Antarac** [comment]
Still valid?
