### ISSUE TITLE
Why all these units have radar?

### ISSUE THREAD

**Issue by ksilversurfer** [techannihilation/TA#735]
Why all these units have radar?
Some of them should not have imo...

https://demo.chevereto.com/images/2017/12/23/1ht.jpg

```
armawac
armcav
armhorg
armkrmi
armmark
armpeep
armraptor
armscab
armscab1
armscpion
armseer
armsehak
armsh175
coramph
corawac
corfink
corhelo
corhunt
cormabm1
corvoyr
corvrad
nsaagriz
r75v
requ1
taipan
tlldivine
tllhickatee
tllobserver
tllprob
tllrsplane
tlltraq
watcher
```

**Comment by skymyj** [comment]
Many units in this list have a radar object in 3do texture

**Comment by skymyj** [comment]
But some should not have like requ1

**Comment by ksilversurfer** [comment]
agree with : 
armcav - jump unit, it should have radar
armhorg - it has radar model on front, so ok can have radar
armkrmi - jump unit,  it should have radar

imo these units should NOT have radar:
armraptor - why it need radar?
armscab - why it need radar?
armscab1 - why it need radar?
armscpion - i dont see reason it should have radar
coramph - same for this
cormabm1 - why it need radar?
nsaagriz - we have mobile radars, so why it need to have radar?
requ1 - why it need radar?
tlltraq - we have mobile radars, so why it need to have radar?

**Comment by skymyj** [comment]
Can you reopen it ? 
Need to delete radar cordoom too.

**Comment by ksilversurfer** [comment]
Nah, if you want create new issue with copy of that.
I dont work on TA issues or pr anymore.
Pls dont ask me why.
