### ISSUE TITLE
T1 AA Kbot Arm

### ISSUE THREAD

**Issue by skymyj** [techannihilation/TA#743]
ATM, this unit is broken between 3do model and cob file. 
The unit shoot but no weapon visible.
Here the good way to fix that.

**Comment by skymyj** [comment]
![armjeth](https://user-images.githubusercontent.com/2990630/34487313-1a50e7c8-efd4-11e7-951b-8e650c4e327b.PNG)
[armjeth.zip](https://github.com/techannihilation/TA/files/1597821/armjeth.zip)

**Comment by nixtux** [comment]
Sorry but what is broken? Send why a zip file, make it hard/impossible to diff and see what you changing

**Comment by skymyj** [comment]
The 3do model and cob file can't show us the missile launcher like original TA game. 
With he new 3do and cob file, we can see the gates/cover open and we see missile launcher.

**Comment by nixtux** [comment]
K if that the case, can you add as pr?

**Comment by skymyj** [comment]
#748
