### ISSUE TITLE
For a better Balance for BattleShip

### ISSUE THREAD

**Issue by skymyj** [techannihilation/TA#752]
Is it possible to delete the sleep between 3 bursts for main weapon ? 

Like Geo Behemoth, Ship shoots 3 times, then wait 4s. On widget, damage is 600, but in real it's 280~320.
The TLL Battleship fires continually and it is OP.

Can I delete the sleep time in Bos/Cob file ? 
For Behemoth, there is no prob, cause, no other unit like it.

**Comment by nixtux** [comment]
Unitname please

**Comment by skymyj** [comment]
armbats corbats

**Comment by nixtux** [comment]
For tll unit

**Comment by skymyj** [comment]
tllviking

**Comment by skymyj** [comment]
if possible, we should change the tllmodel. There is better. #741

**Comment by nixtux** [comment]
It's untextured + no script

**Comment by skymyj** [comment]
![image](https://user-images.githubusercontent.com/2990630/34848447-1287247e-f71f-11e7-9cd0-78114135e526.png)
We have all

**Comment by skymyj** [comment]
[tllviking.zip](https://github.com/techannihilation/TA/files/1624234/tllviking.zip)
