### ISSUE TITLE
Remove unused game options

### ISSUE THREAD

**Issue by ghost** [techannihilation/TA#776]
Please comment what do you think about that.

Its not important but would be nice to have less commands in list !list bsettings

I marked red that I think can be removed and hardcoded as default.

https://snag.gy/vjZR9e.jpg

--update

**Comment by skymyj** [comment]
Please, keep the terraforming.

**Comment by nixtux** [comment]
Faction changer can be allways on, progressive mining can go, announce eco lead can go

**Comment by ksilversurfer** [comment]
still an active issue, to be done

**Comment by Antarac** [comment]
Terraforming is one of the greatest things in this engine!
Do not delete that please!!!

Anyway be careful with deleting options.
Just cause you don't use it means not that others don't use it.

**Comment by ksilversurfer** [comment]
still valid
