### ISSUE TITLE
Simle fix for all shields

### ISSUE THREAD

**Issue by ksilversurfer** [techannihilation/TA#777]
- add all shields here unit_cobbutton.lua and here cob_buttons.lua
  to use "Shield on"/"Shield off" button
- remove "function gadget:CommandNotify(id, params, options)" from lups_shield.lua
  becouse we dont want use ON/OFF button anymore.
- remove "onoffable" from shields defs
- update all bos scripts to use Shield()

If agree i can start working - tested on armgate works !
turn on/off shield deactivate energy usage and fx

**Comment by nixtux** [comment]
You still need part of command notify in lups_shield.lua, just remove the on/off part the other check cob button command id to turn the shield part off, but go ahead
