### ISSUE TITLE
T2 Tll Trans - pls help

### ISSUE THREAD

**Issue by ksilversurfer** [techannihilation/TA#800]
nerf it same way as here? https://github.com/techannihilation/TA/commit/e42ab1ebe040fac56aede9f22fb8d50495524cf5

Or just increase cost?

tllrobber (https://github.com/techannihilation/TA/blob/master/units/tllrobber.lua)

**Comment by skymyj** [comment]
Yes

**Comment by ksilversurfer** [comment]
hmm i will make it slower than core but with more hp

**Comment by ksilversurfer** [comment]
some values suggestion sky? need to be slower than core but should have more HP and should be more
expensive (at momment it is)

**Comment by skymyj** [comment]
ok

**Comment by nixtux** [comment]
Fix in, https://github.com/techannihilation/TA/commit/87e4f98f6edf62b33938d916a9b9c19ec063e2f3#diff-337db94d19811ac67887c34165c2c92e
