### ISSUE TITLE
Para drop

### ISSUE THREAD

**Issue by nixtux** [techannihilation/TA#836]
Make it a mod option, please vote

**Comment by nixtux** [comment]
You could even set damage percentage

**Comment by skymyj** [comment]
I vote for a 50% HP left after trans is destroyed.

**Comment by nixtux** [comment]
Or we could disable weapons for a set time after drop

**Comment by skymyj** [comment]
Why not. Or EMP while 5S.

**Comment by ksilversurfer** [comment]
yes agree, 50% hp and 5sec emp

**Comment by ksilversurfer** [comment]
after talking with players they prefer only 50% hp, not emping

**Comment by ksilversurfer** [comment]
now is 80% hp left and 5sec emp... lets see how game will be.
50% hp is waaay too much, ppl said that i killed units when i set 8sec and 75% :P
