### ISSUE TITLE
Models Bug

### ISSUE THREAD

**Issue by skymyj** [techannihilation/TA#848]
Many units suffers from this error : 
![image](https://user-images.githubusercontent.com/2990630/35821731-4634b9e6-0aaa-11e8-894b-9e5aff0dec06.png)

**Comment by nixtux** [comment]
Can you explain what the issue is ?

**Comment by skymyj** [comment]
Many units after moving have a "clone" that follow them. This clone is at default position like you see in picture. Maybe it's caused by the map (technoland 5vs5)

**Comment by nixtux** [comment]
Short replay of issue needed

**Comment by ksilversurfer** [comment]
not fixed

**Comment by skymyj** [comment]
![image](https://user-images.githubusercontent.com/2990630/36066989-a22d51e6-0eb4-11e8-8577-2265d35e8b4f.png)
Video coming

**Comment by skymyj** [comment]
Video here : https://1drv.ms/f/s!AgjKPxaKD1zLlg_lYOtIOaUY4Cqv

**Comment by nixtux** [comment]
Need reply to.debug issue

**Comment by skymyj** [comment]
I didn't see anymore.
