### ISSUE TITLE
Change the Morph Multiplicater Mode

### ISSUE THREAD

**Issue by skymyj** [techannihilation/TA#850]
This post to delete or change this option. 

Cause : 
- This option destroys all balance in this game. TLL is totally up cause no Tech Center.
- New players can't play with this option and they have totally useless.
- Average and Good Players with no information (even if a message is shown at launch) are frustrated
I think, you could add at Christmas if you want more fun games but not as an permanently option.

So I'd like to keep this option but for good reason : Decrease Cost or XP unlock or both for battle units only. It will give more battle and less simcity.

**Comment by ksilversurfer** [comment]
so remove Morph Multiplier, but add option XP Multiplier?
or just remove coms, techcenters, and geos from morphmultiplier?

**Comment by skymyj** [comment]
just remove coms, techcenters, and geos from morphmultiplier? => yes
