### ISSUE TITLE
Change afusionplant model

### ISSUE THREAD

**Issue by skymyj** [techannihilation/TA#853]
I propose to change the ATM T3/T4 Fusion by this model : 
Video : https://1drv.ms/v/s!AgjKPxaKD1zLlg3aNB8UkgUyVtbk
![image](https://user-images.githubusercontent.com/2990630/35931244-66e84758-0c34-11e8-9eab-3e3ffee200b8.png)

**Comment by nixtux** [comment]
No replacement for core?, looks great btw

**Comment by skymyj** [comment]
I like the core model. I think, no need to remplace it.

**Comment by nixtux** [comment]
The issue i see is this model looks too high tech v current core model

**Comment by nixtux** [comment]
http://taesc.tauniverse.com/unitguide/unit_corsfus_upgrade.html

**Comment by skymyj** [comment]
the core model is impressive by this size and with the colors texture. Very agressive.
I will push a commit now.

**Comment by skymyj** [comment]
Yes, i had already work on this. But model is uggly and it looks lile to a storage :X 
See screenshot : 
![image](https://user-images.githubusercontent.com/2990630/35939448-75fd3038-0c4c-11e8-8564-eef4e14d3c97.png)

**Comment by skymyj** [comment]
Atm, the model T3/T4 from TA is really good. And lups effect is nice

**Comment by nixtux** [comment]
cfusionplant is just a scaled up version of another unit, which is poor work needs to be fixed imo. And as I already stated looks lower tech that the proposed model for arm

**Comment by skymyj** [comment]
Ok, I will rework this c Fusion Plant.

**Comment by skymyj** [comment]
Result for cFusionplant: 
![image](https://user-images.githubusercontent.com/2990630/35967328-d2733fd2-0cc0-11e8-8e3c-5ef48d55248e.png)

**Comment by ksilversurfer** [comment]
looks super coool!

**Comment by skymyj** [comment]
#854
