### ISSUE TITLE
arm kbot 1.5 tech

### ISSUE THREAD

**Issue by ZweisteinT** [techannihilation/TA#86]
Hey guys :) All arm kbot 1.5 tech sucks!

aexxec: very slow, very low range. It can be outmicroed by any other t1 unit. therefore aexxec only good vs static defenses due to high hp of aexxec.

armcrack: artillery rocket. Rockets do not aim during flight. therefore only usable against static defenses.

hardened pewee: that one is ok. only unit for fighting enemy army. buuuut.... its a cheap and weak unit. so it sucks for real battle :)

**Comment by skymyj** [comment]
Hello Zweistein. 

For aexxec, there are really strong on defense vs porc or static as you said.
It's their job. It's alright for me.

For Arm/Core Artillery, I'm for : 
- remplace rocket by t1 kbot rocket with 4 bursts and more range.
- add velocity for rockets

**Comment by ZweisteinT** [comment]
Yeah i understand aexxec has a certain role. What i dont like about it is that arm 1.5 has two unit with the same role: Anti static defense. 

Lets say your enemy goes 1.5 vehicles. Then he has really good fighting units and you have no chance with your kbots even though you invested nearly the same ressources. 

What about we divide roles as this: 2 fighting units and 1 anti static defense unit in each 1.5 lab.

**Comment by ksilversurfer** [comment]
I agree with Zwei, that would be better.

**Comment by skymyj** [comment]
So to resume : 
For Fighting T1.5 Core Unit :
- Gladiator (Long Range)
- AK v1 (Short Range)

For static Def : 
- Missile Launcher
_______________________________________

For Fighting T1.5 Arm Unit :
- Missile Laucnher (T1 Kbot with 4 rocket at long range - same as gladiator. Increase HP)
- Pewee v1 (Short Range)

For static Def : 
- Aexxec

**Comment by ZweisteinT** [comment]
yes sounds nice. We boost the missile launcher until its competitive :D

**Comment by skymyj** [comment]
#93

**Comment by skymyj** [comment]
With this balance, no need to delete core unit. I decrease strengh/cost of galdiator.

**Comment by skymyj** [comment]
Time to close this issue ?
