### ISSUE TITLE
Add Jump feature to Macross

### ISSUE THREAD

**Issue by skymyj** [techannihilation/TA#91]
This unit has a dorsal jetpack. we could imagine missile launcher too...

So, my proposition is to remplace all Terrain by jump Feature. Result is the same. Can pass over obstacles.

**Comment by skymyj** [comment]
![macross](https://cloud.githubusercontent.com/assets/2990630/23300416/b74f320e-fa85-11e6-9406-82541a04962b.png)

**Comment by ZweisteinT** [comment]
For variety its a good idea to change "all terrain" with "jump" for higher tech level units. Jump feature never used by players yet :/ Although we have to be careful, as its not the same. 

- You can jump right into a defense line, while all terrain have to move slowly in and eat damage meanwhile.
- While in jump in general you dont eat damage. So you can jump out and save your units from dying i guess. Reminds me on Starcraft 2 Blink Stalker :D
- Can you jump everywhere? like on top of techno lands platform?

**Comment by skymyj** [comment]
Can you jump everywhere? like on top of techno lands platform? => yes

**Comment by nixtux** [comment]
Hmm so how will this look realistic the amount for force needed to make a unit that size move is amazing, you sure the unit can take the force of take off.

**Comment by skymyj** [comment]
The JepPack are just amazing on this unit. 
we could add class with low speed for Jump that translate the weight.

**Comment by ksilversurfer** [comment]
Yes it looks like it have something like jetpack on back, but its too big unit to be equipped with jump feature :

- Macross with jump will be potentially OP on certain maps

- Not many people using jump, mostly pro players

- As all-terrian was actually usefull and well balanced

- It will be looking very unrealistic

________________________
Dr. Silver aka Kakashi, MD
Official Master Balancer,

**Comment by skymyj** [comment]
It will be looking very unrealistic => https://www.youtube.com/watch?v=EBqDyAvv-_M
