### ISSUE TITLE
TLLExtractor : Add new Icon please

### ISSUE THREAD

**Issue by skymyj** [techannihilation/TA#92]
Nix, can you add this icon for TLLMEX and Tllmex1 in Lua file and in unitpicture ? 

Thanks

![tllmex](https://cloud.githubusercontent.com/assets/2990630/23305961/743a810a-faa1-11e6-83bc-2de3baedfc8e.png)
![tllmex1](https://cloud.githubusercontent.com/assets/2990630/23305962/7449848e-faa1-11e6-9ed7-5425c9cee7b2.png)

**Comment by nixtux** [comment]
Fixed
