### ISSUE TITLE
Proposition for  New units

### ISSUE THREAD

**Issue by skymyj** [techannihilation/TA#921]
Are you ok to integrate : 

SEA LLT : 
![armfllt](https://user-images.githubusercontent.com/2990630/36543665-b598ada0-17e4-11e8-8d02-525614931989.png)
![corfllt](https://user-images.githubusercontent.com/2990630/36543668-b65e9a1a-17e4-11e8-9948-face01e66990.png)

T4 ARM Ressurect Spider
![corspid](https://user-images.githubusercontent.com/2990630/36543802-25e62920-17e5-11e8-92a3-5eedbdb1a831.png)

T4 Tactical Core Pod
![cortac](https://user-images.githubusercontent.com/2990630/36543805-26d773de-17e5-11e8-8df3-136ba8f59654.png)

T4 TLL Shield and EMP Kbot
![armaspid](https://user-images.githubusercontent.com/2990630/36543902-676e6222-17e5-11e8-824c-e97fe72c93a3.png)

**Comment by nixtux** [comment]
No tll sea llt, hint tllradarns base

**Comment by skymyj** [comment]
Sure. I could use the base.

**Comment by ksilversurfer** [comment]
nice units sky!
