### ISSUE TITLE
XP gains

### ISSUE THREAD

**Issue by skymyj** [techannihilation/TA#936]
Please, is it possible to set at 0 XP, after morphing unit. 
ATM, they keep XP gains from last status. 

We had already fix that. Why revert ?

**Comment by nixtux** [comment]
It's not been touched in the last 5 years, look https://github.com/techannihilation/TA/commit/8becbd3d6d1fd2a3704e7055424336c678b351b8

**Comment by skymyj** [comment]
And is it possible to set at 0 XP after Morph ?

**Comment by ksilversurfer** [comment]
yes possible

**Comment by ksilversurfer** [comment]
done
