### ISSUE TITLE
Are you ready for T2 TLL Hover ?

### ISSUE THREAD

**Issue by skymyj** [techannihilation/TA#945]
Idea is to give all existing Core models  to TLL except Goliath Hover maybe. 
Add new models for Core like them : 
![corhtank](https://user-images.githubusercontent.com/2990630/36702413-55064a3a-1b57-11e8-96a8-0ab53d476fa3.png)
![corhlas](https://user-images.githubusercontent.com/2990630/36702414-552d66ec-1b57-11e8-9d26-5503882176d6.png)

**Comment by skymyj** [comment]
![image](https://user-images.githubusercontent.com/2990630/36702545-c9b933c4-1b57-11e8-8c78-2e6a067ff2b8.png)

**Comment by skymyj** [comment]
TLL have turtle too :X 
Don't know if it's a good idea or not.

**Comment by nixtux** [comment]
Moving all core models is a bad idea imo
