### ISSUE TITLE
Anti Spam Tactics

### ISSUE THREAD

**Issue by ZweisteinT** [techannihilation/TA#95]
Hi!

What are good anti scout spam tactics for arm?

I think core has all those laser units like sumo, aks, etc. so they can stop spams more easy. 
Arm with all their bullets dont hit them as well. Static defense lasers like llt are not the answer, because at some point you need to push. So are there any tactics i am missing or can we find a solution? Like an arm-anti-spam unit with 5 lasers!

Other direction would be to somehow prevent players from being able to spam scouts like crazy. It first affects game performance. And secondly removes all those tactical abilities. Long range weapons just hit those damn scouts and all those "specialized" units, high armored+short range, low armored+longrange, etc... are basically countered by those spams and the fun of tactical variety is neglected.

**Comment by skymyj** [comment]
Zeus Unit ???

**Comment by skymyj** [comment]
Maverick are good too :)

**Comment by ksilversurfer** [comment]
actually we talking about something like "ultimate anti flea/weasel spam"
it dont need have to be equipped with hight dps, rather it should have multi lasor weapon to kill as many fleas at one time as possible.

**Comment by nixtux** [comment]
Juno is anti spam weapon

**Comment by ZweisteinT** [comment]
We tested...

Juno is bad. Even with 6 junos, timed to permanentely shoot the field, you cant stop a scout spam. You need TWO!!! juno shots per scout. Second: juno shoots your own units, too. 

Zeus dont hit scouts. 

Maverick kinda do hit them. its ok. 

But best seem to be warrior. Anyway, strange you need the t1 "tank" to be able to deal with scouts.

**Comment by ksilversurfer** [comment]
it is fixed :) thx to Nixtux
