### ISSUE TITLE
keijjos whining list

### ISSUE THREAD

**Issue by ksilversurfer** [techannihilation/TA#954]

**Comment by keijj0** [comment]
So many things, so little time. 

Lets start with tll eco, tll needs their fusions to convert the same say as energy drillers, as in only switch on when energy is above conversion slider.
Second thing is the conversion ratios, t1 mex is better than arm/core and units are more expensive aswell, but at t2 things go worse, mexes produce less than arm/core and metalmakers have shit conversion ratio. I would like to see 1 = 1 t2 mexes and improve tll t2 metalmaker to 95% of arm/core. Fusions have conversion ratio of 0.01 while arm/core t2 is 0.015, so i want the fusions to have 0.0135 ratio, you could make fusions 5% more expensive or increase their build area cos they are really small compared to arm/core. Similar things should apply to t3 eco. 

Tll t2 popup laser is kinda shit, i would change just beamlaser to lasercannon so damage isnt reduced by range

**Comment by skymyj** [comment]
For Fusion convert, there is already the #941 
For TLL popup laser, it can be done easely
For Ratio MEX, I'm ok. These ratio provides from 2012 balance when TLL have low cost T2 construtors and no T1.5 MEX

I'd like add one thing : Add an adv Mex T1.5

**Comment by skymyj** [comment]
Ratio TLL is more metal and less energy. So, we need to have MEX > ARM/CORE. 
ATM RATIO : (COST M/E ARE ~ SAME)
T1 ARM/CORE : 0.001 --- T1 TLL : 0.0012
T2 ARM/CORE : 0.006 --- T2 TLL : 0.005 

I propose :
T1 ARM/CORE : 0.001 --- T1 TLL : 0.0012
T2 ARM/CORE : 0.006 --- T2 TLL : 0.0066

Instead, they have less ratio from energy conversion.

**Comment by keijj0** [comment]
If so then every mex should be iproved, but i would still upgrade conversion ratio at least a bit

**Comment by ksilversurfer** [comment]
should we merge that ? https://github.com/techannihilation/TA/pull/941

**Comment by skymyj** [comment]
Yes

**Comment by keijj0** [comment]
Few updates on whining
The big units(especially ultimate fusions and t4 cons) being clickable by far outside their model makes stuff almost impossible to select next to them. And reverse issue is arm/core t1/t2 airlabs(only thing i can remember being hard to select) which are really hard to select without selecthing the unit what its building currently
Arm kbots: warrior is too strong atm and most ppl agree with it, i suggest removing raider resistant from it(no t1 unit should have it) and nerfing acceleration and turnspeed by 5-20 % and see how it goes. The 2nd thing is exxec, the heavy lasercannon "kbot" which is on tracks. It is almost completely useless for its price anyways, low range and really low speed combined with low turningrate makes it kiteable by any unit what outranges it. Imo it should be removed or completely redone

**Comment by keijj0** [comment]
I think we need some place where ppl can report bugs, if they are too lazy to register here

**Comment by skymyj** [comment]
For exxec, I klnow they are useless on a flat map. As you said, low range and low speed = death 90% except if you play vs losbellos or dust :)
But they have many HP like corcan. They are "tank" gameplay. Their job is to lead an attack with other units or to defend a way vs rapid unit. I think, they have a good job. Now they are maybe under powered. Maybe, increase HP or add an autorepair feature like maverick.
