### ISSUE TITLE
Need info what vignette effect was used in icons so i can add icons we need !

### ISSUE THREAD

**Issue by ksilversurfer** [techannihilation/TA#957]

**Comment by ksilversurfer** [comment]
ppl already talking that its not finished dev version :(

**Comment by nixtux** [comment]
for file in *.png;do;convert -bordercolor none -border 3 -background none \
   -alpha background -channel A -blur 0x10 -level 0,0%% -trim +repage "$file" "$(basename "$file" .png).png";done

**Comment by nixtux** [comment]
Which icons are needed ?

**Comment by ksilversurfer** [comment]
your commit fixed white icons and is ok, i just checked ota icons and we need a lot of them
i need make a list...

for new icons:
tllnanotc3 is wrong faction
tllhyrde1 is wrong faction

**Comment by skymyj** [comment]
need icons for : 
- the sea llt
- the t3 mex
- the t4 air
- the t4 MM
- cormcv

**Comment by nixtux** [comment]
It would be great if someone could zip up all the missing ota icon

**Comment by ksilversurfer** [comment]
working on it now

**Comment by ksilversurfer** [comment]
Part 1
[ota_icons_1.zip](https://github.com/techannihilation/TA/files/1779926/ota_icons_1.zip)

![ametalmakerlvl3](https://user-images.githubusercontent.com/35111293/36962991-e7752388-2051-11e8-8075-124f8681ed10.png)
![arm_mech_lab](https://user-images.githubusercontent.com/35111293/36962992-e79c819e-2051-11e8-93ec-01dd98efd707.png)
![armefus](https://user-images.githubusercontent.com/35111293/36962993-e7c308fa-2051-11e8-9771-5525ebb5e51e.png)
![armemex](https://user-images.githubusercontent.com/35111293/36962995-e7ea90d2-2051-11e8-81fc-ac9a7c6c34ef.png)
![armfllt](https://user-images.githubusercontent.com/35111293/36962996-e81139a8-2051-11e8-92c2-f8b5c024ecff.png)
![cmetalmakerlvl3](https://user-images.githubusercontent.com/35111293/36962997-e83be52c-2051-11e8-8b96-aa5d0d885d3f.png)
![coremex](https://user-images.githubusercontent.com/35111293/36962998-e87fe27c-2051-11e8-85dd-8654d40d7571.png)
![corfllt](https://user-images.githubusercontent.com/35111293/36962999-e90bbfc2-2051-11e8-91df-2635b77aa682.png)
![cormcv](https://user-images.githubusercontent.com/35111293/36963000-e954647a-2051-11e8-89ec-0518d50d45b7.png)
![corshock](https://user-images.githubusercontent.com/35111293/36963002-e9b02aee-2051-11e8-8d42-f2de1d1623d8.png)
![fatshrew](https://user-images.githubusercontent.com/35111293/36963003-ea009074-2051-11e8-9340-16c188a33160.png)
![monkeylord](https://user-images.githubusercontent.com/35111293/36963004-ea3fd2d4-2051-11e8-917b-39c394b65945.png)

**Comment by ksilversurfer** [comment]
I cant find icon for afusionplant, skymyj can you share it?

**Comment by skymyj** [comment]
Not exist. I create the unit.

**Comment by ksilversurfer** [comment]
ah you made it from this?
![armsfus](https://user-images.githubusercontent.com/35111293/36963485-b473836a-2053-11e8-8c89-6e485c101b1f.png)

**Comment by ksilversurfer** [comment]
do you have icon for tllmetalmakerlvl3?

**Comment by ksilversurfer** [comment]
icon for tllgeo_armored pls skymyj

**Comment by ksilversurfer** [comment]
ok i made it
[afusionplant.zip](https://github.com/techannihilation/TA/files/1780440/afusionplant.zip)
![afusionplant](https://user-images.githubusercontent.com/35111293/36970384-b434a34c-2068-11e8-8ca6-a73b217bfbf7.png)

**Comment by ksilversurfer** [comment]
on green
[afusionplant_v2.zip](https://github.com/techannihilation/TA/files/1780460/afusionplant_v2.zip)
![afusionplant](https://user-images.githubusercontent.com/35111293/36970619-7a25fae2-2069-11e8-8a5f-7823eae060a4.png)

**Comment by skymyj** [comment]
Nice work Silver. 
For Tll Geo, it's a creation too.
For Tllmetalmaker, it's here : http://units.tauniverse.com/?p=u&v=582

**Comment by nixtux** [comment]
Tll t3 maker needs to be replaced looks like a fusion.

**Comment by ksilversurfer** [comment]
Final version, more natural and good sharp balance
![afusionplant](https://user-images.githubusercontent.com/35111293/36973068-c6dd1c46-2071-11e8-84c7-db6c218aac27.png)
[afusionplant_v3.zip](https://github.com/techannihilation/TA/files/1780623/afusionplant_v3.zip)

**Comment by ksilversurfer** [comment]
tllmetalmakerlvl3 :D 
![tllmetalmakerlvl3](https://user-images.githubusercontent.com/35111293/36974291-70e2e550-2076-11e8-8bcf-d59a68fb9306.png)
[tllmetalmakerlvl3.zip](https://github.com/techannihilation/TA/files/1780736/tllmetalmakerlvl3.zip)

**Comment by ksilversurfer** [comment]
Nixtux convert this pls: 
[ota_icons_1_upd.zip](https://github.com/techannihilation/TA/files/1780768/ota_icons_1_upd.zip)

**Comment by ksilversurfer** [comment]
done :D
