### ISSUE TITLE
tllmetalmakerlvl3

### ISSUE THREAD

**Issue by nixtux** [techannihilation/TA#965]
Looks like a ugly fusion, we need a new model imo

**Comment by skymyj** [comment]
Proposition : 
![image](https://user-images.githubusercontent.com/2990630/42594760-79ea5bc6-8550-11e8-8cde-bc05ef4867a5.png)

**Comment by skymyj** [comment]
![image](https://user-images.githubusercontent.com/2990630/42594835-b3f5037a-8550-11e8-8904-e66adad03304.png)

**Comment by skymyj** [comment]
And like this ? 
![image](https://user-images.githubusercontent.com/2990630/42595306-285a462a-8552-11e8-8774-0fe180fba93b.png)

**Comment by skymyj** [comment]
![image](https://user-images.githubusercontent.com/2990630/42595440-953fc260-8552-11e8-9913-d0dc3840438a.png)

**Comment by skymyj** [comment]
Issue closed with : 
![image](https://user-images.githubusercontent.com/2990630/66114450-24ce4680-e5cf-11e9-9640-c1d4cc6aef2b.png)
![image](https://user-images.githubusercontent.com/2990630/66114477-31529f00-e5cf-11e9-83f3-22d2d04d480a.png)
