### ISSUE TITLE
Hitspheres

### ISSUE THREAD

**Issue by nixtux** [techannihilation/TA#966]
Many units have oversized hitspheres, names them here please

**Comment by skymyj** [comment]
cortac
monkeylord

**Comment by nixtux** [comment]
Cortac? No such unit

**Comment by skymyj** [comment]
CORARBRITATOR sorry

**Comment by nixtux** [comment]
Done, more please

**Comment by skymyj** [comment]
Pinchy
tllthumper
tlltorp
tllrlrpc
tllroaster1
armstratus
Black Lily (t3.5 core bomber)
tllmohogeo
armbull2

**Comment by skymyj** [comment]
tllgeo_armored
corshock (increase the hitsphere)
ametalmakerlvl3
cmetalmakerlvl3
HERO TLL (valiant)

**Comment by skymyj** [comment]
tlllab

**Comment by ksilversurfer** [comment]
My list:
 - corevp - too small hitsphere, better make it box shape

**Comment by skymyj** [comment]
armgate1

**Comment by skymyj** [comment]
corint1 armbrtha1

**Comment by nixtux** [comment]
https://github.com/techannihilation/TA/issues/1178
