### ISSUE TITLE
Increase size for TSAR

### ISSUE THREAD

**Issue by skymyj** [techannihilation/TA#967]
These weapon cost x3 the price of lol canon and there are smaller. 

I propose to increase size x 2. Goal could be to reduce their usage too.
Need to much space to make them properly.

What do you think ? 
![image](https://user-images.githubusercontent.com/2990630/36945324-738c02ca-1fac-11e8-9c9b-8649f6f6ec1c.png)

**Comment by ksilversurfer** [comment]
i like this idea

**Comment by nixtux** [comment]
All I can see this doing is making big flat maps getting played even more

**Comment by skymyj** [comment]
![image](https://user-images.githubusercontent.com/2990630/37257879-41978820-256f-11e8-8910-3ef5931e2437.png)

**Comment by skymyj** [comment]
![image](https://user-images.githubusercontent.com/2990630/37258359-104ce898-2577-11e8-969e-cccdbbb0e747.png)
