### ISSUE TITLE
Delete vengence and remplace by this kbot

### ISSUE THREAD

**Issue by skymyj** [techannihilation/TA#975]
to response to this post : #330
![image](https://user-images.githubusercontent.com/2990630/37051246-31d3c860-2176-11e8-862b-4cd291bdba7f.png)

**Comment by skymyj** [comment]
Or by this : 
![image](https://user-images.githubusercontent.com/2990630/37051314-6381cae2-2176-11e8-8bbb-80c2f3ce8281.png)

**Comment by nixtux** [comment]
I dislike the first unit as a replacement for vengeance. Personally I see nothing wrong with vengeance

**Comment by ksilversurfer** [comment]
omg noo, pls leave AK-X1 alone it is ok unit !
if you want add this new unit to TLL
