### ISSUE TITLE
High impulse shockwave weapon

### ISSUE THREAD

**Issue by ghost** [techannihilation/TA#978]
Please comment if you like the idea. If so i will start working on that ! :D 
What it do?
Each cannon when fire generate high shockwave that repel units on desire distance, but do 0 dmg.

![corwith](https://user-images.githubusercontent.com/35111293/37103110-c5cc8f6c-2229-11e8-84a7-191297065d69.png)

**Comment by skymyj** [comment]
In other mod, they use a beam to repulse units. 
They can make (hand rail / banister) that catapult friendly unit to reach position between 1K & 2K Range.

**Comment by skymyj** [comment]
In other ideas, there is another weapon that give slow down effect on unit (less reload and movement)

**Comment by Antarac** [comment]
You mean your own units get pushed a little bit aside if a big cannon like bertha is shooting?
If you are able to connect this with the units weight, the cannon type and size would be awesome i guess =)

**Comment by ksilversurfer** [comment]
its still active and valid

**Comment by Antarac** [comment]
Well, if its active comment my comment? =)

**Comment by ksilversurfer** [comment]
still valid idea
