### ISSUE TITLE
Increase size for helldriver

### ISSUE THREAD

**Issue by skymyj** [techannihilation/TA#987]
Could be good to increase by 1.2

**Comment by skymyj** [comment]
![image](https://user-images.githubusercontent.com/2990630/37177498-e5546fde-231f-11e8-819a-981ff0ccf28a.png)

**Comment by nixtux** [comment]
Why?

**Comment by skymyj** [comment]
Caue they have more HP and mass

**Comment by keijj0** [comment]
I agree, being pw-sized t2.5 which isnt spy dont seem logical

**Comment by ksilversurfer** [comment]
agree to to scale up
