### ISSUE TITLE
Commando diseapear ?

### ISSUE THREAD

**Issue by skymyj** [techannihilation/TA#989]
I think I didn't see commando for arm from T2 engineers. 
Is it ok ?

**Comment by ksilversurfer** [comment]
Commando is core unit

**Comment by skymyj** [comment]
So, for arm, there is a new unit ?

**Comment by skymyj** [comment]
I have an unit, if needed.

**Comment by ksilversurfer** [comment]
would be cool skymyj

**Comment by skymyj** [comment]
![image](https://user-images.githubusercontent.com/2990630/37372329-a66d1f7c-2712-11e8-83b9-34448de0ee8b.png)
![image](https://user-images.githubusercontent.com/2990630/37372346-b87817f8-2712-11e8-83ec-a0e5f6b2e7e8.png)

**Comment by ksilversurfer** [comment]
not bad, i think is ok.

**Comment by ksilversurfer** [comment]
one player suggested name for arm commando: Rambo

**Comment by skymyj** [comment]
Ok. I will add this evenning. 
If you have time, you can create the lua files with armrambo.

**Comment by ksilversurfer** [comment]
can you share me 3d model? so i can make icon for it
