### ISSUE TITLE
New morph/ideas for TLL T1

### ISSUE THREAD

**Issue by skymyj** [techannihilation/TA#992]
I propose to add new version 2 for : 
- Private / Private 1
- Rocket / Rocket 1 / Amphibious Rocket T2
- Plasma / Plasma1 / Artibot T2
- Remplace Green Beam by Lighting for Iguana (and delete the barrel move)
- Medium Tank / Medium Tank 1
- Missile launcher / Missile Launcher 1
- Remplace weapon for Light Tank (Red beam by lighting weapon)

From history faction, TLL has no beam.
We should delete the green beam from HLT and pop-up too.

**Comment by ksilversurfer** [comment]
yes nice ideas

**Comment by nixtux** [comment]
Replace laser with lightning cannon will cause balance issue to to lightning cannons dealing full damage whatever the range. How many times have I said this before....

**Comment by ksilversurfer** [comment]
yes thats why i worry about,

**Comment by skymyj** [comment]
And? You decrease the damage and it will be balanced. Beam will be better at low range and inverse at high range. It's not the spice of life?

**Comment by skymyj** [comment]
I'd like to add the ligh for private too. With a good balance, could be very interesting.
