### ISSUE TITLE
Shield Vehicle for ARM

### ISSUE THREAD

**Issue by skymyj** [techannihilation/TA#997]
Second proposition for Shield Veh T2 : 
![image](https://user-images.githubusercontent.com/2990630/37494462-2a9fbcf4-28a9-11e8-9aaa-590a26189b5b.png)
![image](https://user-images.githubusercontent.com/2990630/37494468-33bd784e-28a9-11e8-8ad1-806a671bced2.png)
![image](https://user-images.githubusercontent.com/2990630/37494473-3e765be8-28a9-11e8-8019-c8d0898fda3b.png)

**Comment by skymyj** [comment]
New proposition with same base : 
![image](https://user-images.githubusercontent.com/2990630/37613416-45685e04-2ba8-11e8-836d-d19ece902788.png)
(The sphere will be replaced by luia)

**Comment by nixtux** [comment]
New addition to unit does.not fit imo

**Comment by skymyj** [comment]
Ok. I will rework.

**Comment by skymyj** [comment]
![image](https://user-images.githubusercontent.com/2990630/37729996-cbd74ca6-2d3e-11e8-8a9c-d7d66b701214.png)

**Comment by skymyj** [comment]
Can i have a feedback ? Thanks.

**Comment by skymyj** [comment]
Found a nice model.
Need to work on it before to show

**Comment by skymyj** [comment]
![image](https://user-images.githubusercontent.com/2990630/50604929-efba8980-0ec0-11e9-9fcf-80f8a1753f4a.png)

**Comment by skymyj** [comment]
![image](https://user-images.githubusercontent.com/2990630/50605074-72dbdf80-0ec1-11e9-8280-eb2714558a60.png)
